# Generated automatically from Makefile.in by configure.
# $Id$

top_srcdir = ../../..
top_builddir = ../../..
libsrc_dir = contrib/src/applet

TARGET_LIBNAME=libwx_msw_applet-2.5

LIBVERSION_CURRENT=0
LIBVERSION_REVISION=0
LIBVERSION_AGE=0


HEADER_PATH=$(top_srcdir)/contrib/include/wx
HEADER_SUBDIR=applet

HEADERS=applet.h appletwindow.h

OBJECTS=applet.o appletwindow.o
DEPFILES=$(OBJECTS:.o=.d)

APPEXTRADEFS=-I$(top_srcdir)/contrib/include

include $(top_builddir)/src/makelib.env

-include $(DEPFILES)
