# Purpose: makefile for #NAME example (Unix)
# Created: #DATE

CC = gcc

PROGRAM = #NAME

OBJECTS = $(PROGRAM).o

# implementation

.SUFFIXES:	.o .cpp

.cpp.o :
	$(CC) -c `wx-config --cflags` -o $@ $<

all:    $(PROGRAM)

$(PROGRAM):	$(OBJECTS)
	$(CC) -o $(PROGRAM) $(OBJECTS) `wx-config --libs`

clean:
	rm -f *.o $(PROGRAM)
