# Purpose: makefile for #NAME example (BC++ 16bit)
# Created: #DATE

!if "$(WXWIN)" == ""
!error You must define the WXWIN variable in autoexec.bat, e.g. WXWIN=c:\wx
!endif

WXDIR = $(WXWIN)

TARGET=#NAME
OBJECTS=$(TARGET).obj

!include $(WXDIR)\src\makeprog.bcc

