#
# File:		makefile.b32
# Author:	Julian Smart
# Created:	1999
# Updated:	
#
#
# Makefile : Builds wxTree sample for 32-bit BC++

WXDIR = $(WXWIN)

TARGET=test
OBJECTS=$(TARGET).obj wxtree.obj

!include $(WXDIR)\src\makeprog.b32

