#
# File:		makefile.b32
# Author:	Patrick Halke
# Created:	1995
# Updated:	
# Copyright:	(c) 1993, AIAI, University of Edinburgh
#
# "%W% %G%"
#
# Makefile : Builds 32bit wxtree library for 32-bit BC++

WXDIR = $(WXWIN)

TARGET=test
OBJECTS=$(TARGET)

!include $(WXDIR)\src\makeprog.b32

