#
# File:		makefile.nt
# Author:	Julian Smart
# Created:	1993
# Updated:	
# Copyright:	(c) 1993, AIAI, University of Edinburgh
#
# "%W% %G%"
#
# Makefile : Builds wxTree class library (MS VC++).
# Use FINAL=1 argument to nmake to build final version with no debugging
# info

# Set WXDIR for your system
WXDIR = $(WXWIN)
TREEDIR = $(WXDIR)\utils\wxtree
THISDIR = $(WXDIR)\utils\wxtree\src
EXTRALIBS=$(TREEDIR)\lib\wxtree.lib
DOCDIR=$(WXDIR)\docs
LOCALDOCDIR=$(WXDIR)\utils\wxtree\docs

!include $(WXDIR)\src\ntwxwin.mak

PROGRAM=test
 
OBJECTS = wxtree.obj
PROGOBJECTS = $(PROGRAM).obj
LIBTARGET=$(TREEDIR)\lib\wxtree.lib

all:    $(LIBTARGET)

$(PROGRAM):    $(PROGRAM).exe

wx:
        cd $(WXDIR)\src\msw
        nmake -f makefile.nt FINAL=$(FINAL)
        cd $(THISDIR)

wxclean:
        cd $(WXDIR)\src\msw
        nmake -f makefile.nt clean
        cd $(THISDIR)

$(LIBTARGET): $(OBJECTS)
	-erase $(LIBTARGET)
	$(implib) @<<
-out:$(LIBTARGET)
-machine:$(CPU)
$(OBJECTS)
<<

$(PROGRAM).exe:      $(DUMMYOBJ) $(WXLIB) $(PROGOBJECTS) $(LIBTARGET) $(PROGRAM).res
	$(link) @<<
-out:$(PROGRAM).exe
$(LINKFLAGS)
$(DUMMYOBJ) $(PROGOBJECTS) $(PROGRAM).res
$(LIBS)
<<

wxtree.obj:      wxtree.h wxtree.$(SRCSUFF) $(DUMMYOBJ)
        $(cc) @<<
$(CPPFLAGS) /c /Tp $*.$(SRCSUFF)
<<

$(PROGRAM).obj:      $(PROGRAM).h $(PROGRAM).$(SRCSUFF) $(DUMMYOBJ)
        $(cc) @<<
$(CPPFLAGS) /c /Tp $*.$(SRCSUFF)
<<

$(PROGRAM).res :      $(PROGRAM).rc $(WXDIR)\include\wx\msw\wx.rc
    $(rc) -r /i$(WXDIR)\include -fo$@ $(PROGRAM).rc


clean:
        -erase *.obj
        -erase *.sbr
        -erase *.exe
        -erase *.res
        -erase *.map
        -erase *.pdb
        -erase $(LIBTARGET)

DOCSOURCES=$(LOCALDOCDIR)\wxtree.tex $(LOCALDOCDIR)\classes.tex

html: $(DOCDIR)\html\wxtree\tree.htm
hlp: $(DOCDIR)\winhelp\wxtree.hlp
pdfrtf: $(DOCDIR)\pdf\wxtree.rtf
ps: $(WXDIR)\docs\ps\wxtree.ps

$(DOCDIR)\winhelp\wxtree.hlp:         $(LOCALDOCDIR)\wxtree.rtf $(LOCALDOCDIR)\wxtree.hpj
        cd $(LOCALDOCDIR)
        -erase wxtree.ph
        hc wxtree
        move wxtree.hlp $(DOCDIR)\winhelp\wxtree.hlp
        move wxtree.cnt $(DOCDIR)\winhelp\wxtree.cnt
        cd $(THISDIR)

$(LOCALDOCDIR)\wxtree.rtf: $(DOCSOURCES)
        cd $(LOCALDOCDIR)
        -start /w tex2rtf $(LOCALDOCDIR)\wxtree.tex $(LOCALDOCDIR)\wxtree.rtf -twice -winhelp
        cd $(THISDIR)

$(DOCDIR)\pdf\wxtree.rtf: $(DOCSOURCES)
        cd $(LOCALDOCDIR)
        -copy *.bmp $(DOCDIR)\pdf
        -start /w tex2rtf $(LOCALDOCDIR)\wxtree.tex $(DOCDIR)\pdf\wxtree.rtf -twice -rtf
        cd $(THISDIR)

$(DOCDIR)\html\wxtree\tree.htm:         $(DOCSOURCES)
        cd $(LOCALDOCDIR)
        -mkdir $(DOCDIR)\html\wxtree
        -start /w tex2rtf $(LOCALDOCDIR)\wxtree.tex $(DOCDIR)\html\wxtree\tree.htm -twice -html
        -erase $(DOCDIR)\html\wxtree\*.con
        -erase $(DOCDIR)\html\wxtree\*.ref
        cd $(THISDIR)

$(LOCALDOCDIR)\wxtree.dvi:	$(DOCSOURCES)
	cd $(LOCALDOCDIR)
        -latex wxtree
        -latex wxtree
        -makeindx wxtree
        -bibtex wxtree
        -latex wxtree
        -latex wxtree
        cd $(THISDIR)

$(WXDIR)\docs\ps\wxtree.ps:	$(LOCALDOCDIR)\wxtree.dvi
	cd $(LOCALDOCDIR)
        -dvips32 -o wxtree.ps wxtree
        move wxtree.ps $(WXDIR)\docs\ps\wxtree.ps
        cd $(THISDIR)


