#
# File:		makefile.bcc
# Author:	Julian Smart
# Created:	1999
# Updated:	
#
#
# Makefile : Builds wxTree sample for 16-bit BC++

WXDIR = $(WXWIN)

TARGET=test
OBJECTS=$(TARGET).obj wxtree.obj

!include $(WXDIR)\src\makeprog.bcc

