WXDIR = $(WXWIN)
PROGRAM = anitest

OBJECTS = $(PROGRAM).obj
!if "$(FINAL)" == "0"
EXTRALIBS=$(WXDIR)\lib\animd.lib
!else
EXTRALIBS=$(WXDIR)\lib\anim.lib
!endif
EXTRAINC = -I$(WXDIR)\contrib\include

!include $(WXDIR)\src\makeprog.vc

