#
# File:		makefile.b32
# Author:	Julian Smart
# Created:	1993
# Updated:	
# Copyright:
#
# "%W% %G%"
#
# Makefile : Builds PNG library (BC++ 32-bit)

# WXWIN and BCCDIR are set by parent make

LIBTARGET =..\..\lib\winpng.lib

OBJECTS = png.obj pngread.obj pngrtran.obj pngrutil.obj \
          pngpread.obj pngtrans.obj pngwrite.obj pngwtran.obj pngwutil.obj \
          pngerror.obj pngmem.obj pngwio.obj pngrio.obj pngget.obj pngset.obj

!include $(WXWIN)\src\makelib.b32