#
# File:		makefile.vc
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:	(c) Julian Smart
#
# Makefile : Builds sample (VC++, WIN32)
# Use FINAL=1 argument to nmake to build final version with no debug info.

# Set WXDIR for your system
WXDIR = $(WXWIN)

EXTRAINC = -I..\..\src
EXTRALIBS = $(WXDIR)\lib\fl.lib
EXTRAFLAGS = /DwxDUMMY_OBJ_INCLUDED
PROGRAM=fl_test
OBJECTS = $(PROGRAM).obj

!include $(WXDIR)\src\makeprog.vc

