#
# File:		makefile.dos
# Author:	Julian Smart
# Created:	1998
# Updated:	
#
# Makefile : Builds 16-bit sample, VC++ 1.5
# Use FINAL=1 argument to nmake to build final version with no debugging
# info

WXDIR = $(WXWIN)

TARGET=bombs
OBJECTS = $(TARGET).obj bombs1.obj game.obj

!include $(WXDIR)\src\makeprog.msc

