#
# File:		makefile.unx
# Author:	Julian Smart
# Created:	1998
# Updated:	
# Copyright:	(c) 1998 Julian Smart
#
# "%W% %G%"
#
# Makefile for bombs example (UNIX).

PROGRAM=bombs

OBJECTS=$(PROGRAM).o bombs1.o game.o

include ../../src/makeprog.env

