#!/bin/sh
# makewxgtk
# Configures and makes wxGTK from either the root wxWindows directory
# or a build directory underneath it.

CONFIG=./configure

if [ ! -f ./configure ]; then
  CONFIG=../configure
fi

CONFIG="$CONFIG --disable-shared --enable-gui --with-gtk --enable-debug_flag --enable-log --enable-debug_info --enable-debug --enable-threads --enable-sockets -with-odbc -with-libjpeg --enable-debug_cntxt"

echo Invoking $CONFIG

rm -f *.cache
$CONFIG

make

