# Purpose: makefile for richedit example (Unix)
# Created: 2000-03-14
# hand hacked from template file by Ron <ron@debian.org>

CXX = $(shell wx-config --cxx)

PROGRAM = wxLayout

OBJECTS = $(PROGRAM).o kbList.o wxllist.o wxlparser.o wxlwindow.o

# implementation

.SUFFIXES:	.o .cpp

.cpp.o :
	$(CXX) -c `wx-config --cxxflags` -o $@ $<

$(PROGRAM): $(OBJECTS)
	$(CXX) -o $(PROGRAM) $(OBJECTS) `wx-config --libs`
	
clean:
	rm -f *.o $(PROGRAM)
