#
# File:         makefile.g95
# Author:       Julian Smart
# Created:      1999
# Updated:
# Copyright:    (c) Julian Smart, 1999
#
# Makefile for wxWindows sample (Cygwin/Mingw32).

WXDIR = ../..

TARGET=wxLayout
OBJECTS = $(TARGET).o kbList.o wxllist.o wxlparser.o wxlwindow.o

include $(WXDIR)/src/makeprog.g95

