# cotire.cmake 1.8.0 generated file
# D:/WxWidgets/MyOutputFolder/libs/xrc/wxxrc_CXX_cotire.cmake
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_EXTENSIONS "inc;inl;ipp")
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_PATH "")
set (COTIRE_CLEAN_ALL_TARGET_NAME "clean_cotire")
set (COTIRE_CLEAN_TARGET_SUFFIX "_clean_cotire")
set (COTIRE_CMAKE_MODULE_FILE "D:/WxWidgets/build/cmake/modules/cotire.cmake")
set (COTIRE_CMAKE_MODULE_VERSION "1.8.0")
set (COTIRE_DEBUG "OFF")
set (COTIRE_INTDIR "cotire")
set (COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES "-j")
set (COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES "2")
set (COTIRE_PCH_ALL_TARGET_NAME "all_pch")
set (COTIRE_PCH_MEMORY_SCALING_FACTOR "170")
set (COTIRE_PCH_TARGET_SUFFIX "_pch")
set (COTIRE_PREFIX_HEADER_FILENAME_SUFFIX "_prefix")
set (COTIRE_TARGETS_FOLDER "cotire")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_DEBUG "CMAKE_INTDIR=\"Debug\";wxxrc_EXPORTS;WXDLLNAME=wxuwp316ud_xrc_vc_custom;WXBUILDING;_LIB;wxUSE_GUI=1;wxUSE_BASE=0;UNICODE;_UNICODE;_CRT_SECURE_NO_DEPRECATE=1;_CRT_NON_CONFORMING_SWPRINTFS=1;_SCL_SECURE_NO_WARNINGS=1;_WINSOCK_DEPRECATED_NO_WARNINGS=1;__WXUWP__;DLL_EXPORTS;WXMAKINGDLL_XRC;WXUSINGDLL;WX_PRECOMP;WIN32;_WINDOWS")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_RELEASE "CMAKE_INTDIR=\"Release\";wxxrc_EXPORTS;WXDLLNAME=wxuwp316ud_xrc_vc_custom;WXBUILDING;_LIB;wxUSE_GUI=1;wxUSE_BASE=0;UNICODE;_UNICODE;_CRT_SECURE_NO_DEPRECATE=1;_CRT_NON_CONFORMING_SWPRINTFS=1;_SCL_SECURE_NO_WARNINGS=1;_WINSOCK_DEPRECATED_NO_WARNINGS=1;__WXUWP__;DLL_EXPORTS;WXMAKINGDLL_XRC;WXUSINGDLL;WX_PRECOMP;WIN32;_WINDOWS;NDEBUG")
set (COTIRE_TARGET_COMPILE_FLAGS_DEBUG "/GR;/EHsc;/MP;/MDd;/Zi;/Ob0;/Od;/W4")
set (COTIRE_TARGET_COMPILE_FLAGS_RELEASE "/GR;/EHsc;/MP;/MD;/O2;/Ob2;/W4")
set (COTIRE_TARGET_CONFIGURATION_TYPES "Debug;Release")
set (COTIRE_TARGET_CXX_COMPILER_LAUNCHER "COTIRE_TARGET_CXX_COMPILER_LAUNCHER-NOTFOUND")
set (COTIRE_TARGET_IGNORE_PATH "D:/WxWidgets")
set (COTIRE_TARGET_INCLUDE_DIRECTORIES_DEBUG "D:/WxWidgets/MyOutputFolder/lib/vc_x64_dll/uwpud;D:/WxWidgets/include")
set (COTIRE_TARGET_INCLUDE_DIRECTORIES_RELEASE "D:/WxWidgets/MyOutputFolder/lib/vc_x64_dll/uwpud;D:/WxWidgets/include")
set (COTIRE_TARGET_INCLUDE_PRIORITY_PATH "")
set (COTIRE_TARGET_LANGUAGE "CXX")
set (COTIRE_TARGET_MAXIMUM_NUMBER_OF_INCLUDES "-j")
set (COTIRE_TARGET_POST_UNDEFS "")
set (COTIRE_TARGET_PRE_UNDEFS "")
set (COTIRE_TARGET_SOURCES "D:/WxWidgets/src/xrc/xh_activityindicator.cpp;D:/WxWidgets/src/xrc/xh_animatctrl.cpp;D:/WxWidgets/src/xrc/xh_bannerwindow.cpp;D:/WxWidgets/src/xrc/xh_bmp.cpp;D:/WxWidgets/src/xrc/xh_bmpcbox.cpp;D:/WxWidgets/src/xrc/xh_bmpbt.cpp;D:/WxWidgets/src/xrc/xh_bttn.cpp;D:/WxWidgets/src/xrc/xh_cald.cpp;D:/WxWidgets/src/xrc/xh_chckb.cpp;D:/WxWidgets/src/xrc/xh_chckl.cpp;D:/WxWidgets/src/xrc/xh_choic.cpp;D:/WxWidgets/src/xrc/xh_choicbk.cpp;D:/WxWidgets/src/xrc/xh_clrpicker.cpp;D:/WxWidgets/src/xrc/xh_cmdlinkbn.cpp;D:/WxWidgets/src/xrc/xh_collpane.cpp;D:/WxWidgets/src/xrc/xh_combo.cpp;D:/WxWidgets/src/xrc/xh_comboctrl.cpp;D:/WxWidgets/src/xrc/xh_datectrl.cpp;D:/WxWidgets/src/xrc/xh_dirpicker.cpp;D:/WxWidgets/src/xrc/xh_dlg.cpp;D:/WxWidgets/src/xrc/xh_editlbox.cpp;D:/WxWidgets/src/xrc/xh_filectrl.cpp;D:/WxWidgets/src/xrc/xh_filepicker.cpp;D:/WxWidgets/src/xrc/xh_fontpicker.cpp;D:/WxWidgets/src/xrc/xh_frame.cpp;D:/WxWidgets/src/xrc/xh_gauge.cpp;D:/WxWidgets/src/xrc/xh_gdctl.cpp;D:/WxWidgets/src/xrc/xh_grid.cpp;D:/WxWidgets/src/xrc/xh_html.cpp;D:/WxWidgets/src/xrc/xh_hyperlink.cpp;D:/WxWidgets/src/xrc/xh_infobar.cpp;D:/WxWidgets/src/xrc/xh_listb.cpp;D:/WxWidgets/src/xrc/xh_listbk.cpp;D:/WxWidgets/src/xrc/xh_listc.cpp;D:/WxWidgets/src/xrc/xh_mdi.cpp;D:/WxWidgets/src/xrc/xh_menu.cpp;D:/WxWidgets/src/xrc/xh_notbk.cpp;D:/WxWidgets/src/xrc/xh_odcombo.cpp;D:/WxWidgets/src/xrc/xh_panel.cpp;D:/WxWidgets/src/xrc/xh_propdlg.cpp;D:/WxWidgets/src/xrc/xh_radbt.cpp;D:/WxWidgets/src/xrc/xh_radbx.cpp;D:/WxWidgets/src/xrc/xh_scrol.cpp;D:/WxWidgets/src/xrc/xh_scwin.cpp;D:/WxWidgets/src/xrc/xh_htmllbox.cpp;D:/WxWidgets/src/xrc/xh_simplebook.cpp;D:/WxWidgets/src/xrc/xh_sizer.cpp;D:/WxWidgets/src/xrc/xh_slidr.cpp;D:/WxWidgets/src/xrc/xh_spin.cpp;D:/WxWidgets/src/xrc/xh_split.cpp;D:/WxWidgets/src/xrc/xh_srchctrl.cpp;D:/WxWidgets/src/xrc/xh_statbar.cpp;D:/WxWidgets/src/xrc/xh_stbmp.cpp;D:/WxWidgets/src/xrc/xh_stbox.cpp;D:/WxWidgets/src/xrc/xh_stlin.cpp;D:/WxWidgets/src/xrc/xh_sttxt.cpp;D:/WxWidgets/src/xrc/xh_text.cpp;D:/WxWidgets/src/xrc/xh_tglbtn.cpp;D:/WxWidgets/src/xrc/xh_timectrl.cpp;D:/WxWidgets/src/xrc/xh_toolb.cpp;D:/WxWidgets/src/xrc/xh_toolbk.cpp;D:/WxWidgets/src/xrc/xh_tree.cpp;D:/WxWidgets/src/xrc/xh_treebk.cpp;D:/WxWidgets/src/xrc/xh_unkwn.cpp;D:/WxWidgets/src/xrc/xh_wizrd.cpp;D:/WxWidgets/src/xrc/xmlres.cpp;D:/WxWidgets/src/xrc/xmlrsall.cpp;D:/WxWidgets/src/xrc/xh_dataview.cpp")
set (COTIRE_UNITY_BUILD_ALL_TARGET_NAME "all_unity")
set (COTIRE_UNITY_BUILD_TARGET_SUFFIX "_unity")
set (COTIRE_UNITY_OUTPUT_DIRECTORY "")
set (COTIRE_UNITY_SOURCE_EXCLUDE_EXTENSIONS "m;mm")
set (COTIRE_UNITY_SOURCE_FILENAME_SUFFIX "_unity")
set (MSVC "1")
set (CMAKE_GENERATOR "Visual Studio 17 2022")
set (CMAKE_CONFIGURATION_TYPES "Debug;Release")
set (CMAKE_CXX_COMPILER_ID "MSVC")
set (CMAKE_CXX_COMPILER_VERSION "19.30.30706.0")
set (CMAKE_CXX_COMPILER "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe")
set (CMAKE_CXX_COMPILER_ARG1 "")
set (CMAKE_INCLUDE_FLAG_CXX "-I")
set (CMAKE_INCLUDE_SYSTEM_FLAG_CXX "-external:I ")
set (CMAKE_CXX_SOURCE_FILE_EXTENSIONS "C;M;c++;cc;cpp;cxx;mm;mpp;CPP;ixx;cppm")
