#
# File:		makefile.b32
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:
#
# Makefile : Builds Animation library for 32-bit BC++

WXDIR = $(WXWIN)

LIBTARGET=$(WXDIR)\lib\anim.lib

OBJECTS = animate.obj

!include $(WXDIR)\src\makelib.b32

