#
# File:		makefile.b32
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:
#
# Makefile : Builds Animation library for 32-bit BC++

WXDIR = $(WXWIN)

LIBTARGET=anim

!include $(WXDIR)\src\makeb32.env

OBJECTS = $(OBJ_PATH)\animate.obj

!include $(WXDIR)\src\makelib.b32

$(OBJ_PATH)\animate.obj : animate.cpp
