# Purpose: makefile for event example (BC++ 16bit)
# Created: 2001-01-31

!if "$(WXWIN)" == ""
!error You must define the WXWIN variable in autoexec.bat, e.g. WXWIN=c:\wx
!endif

WXDIR = $(WXWIN)

TARGET=event
OBJECTS=$(TARGET).obj

!include $(WXDIR)\src\makeprog.bcc

