#
# File:		makefile.b32
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:
#
# Makefile : Builds FL library for 32-bit BC++

WXDIR = $(WXWIN)

LIBTARGET=$(WXDIR)\lib\fl.lib

OBJECTS = antiflickpl.obj bardragpl.obj barhintspl.obj cbcustom.obj\
 controlarea.obj controlbar.obj dyntbar.obj dyntbarhnd.obj\
 garbagec.obj gcupdatesmgr.obj hintanimpl.obj newbmpbtn.obj\
 panedrawpl.obj rowdragpl.obj rowlayoutpl.obj\
 toolwnd.obj updatesmgr.obj 

!include $(WXDIR)\src\makelib.b32

