#
# File:		makefile.b32
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:
#
# Makefile : Builds Deprecated library for 32-bit BC++

WXDIR = $(WXWIN)

LIBTARGET=$(WXDIR)\lib\wxdeprecated.lib

OBJECTS = prop.obj propform.obj proplist.obj y_tab.obj resource.obj treelay.obj

!include $(WXDIR)\src\makelib.b32

