#
# File:         makefile.g95
# Author:       Julian Smart
# Created:      1999
# Updated:
# Copyright:    (c) Julian Smart, 1999
#
# Makefile for wxWindows Deprecated Features library (Cygwin/Mingw32).

WXDIR = ../../..

LIBTARGET=$(WXDIR)/lib/libwxdeprecated.a
OBJECTS = prop.o propform.o proplist.o y_tab.o resource.o treelay.o

include $(WXDIR)/src/makelib.g95

