#
# File:         makefile.g95
# Author:       Julian Smart
# Created:      1999
# Updated:
# Copyright:    (c) Julian Smart, 1999
#
# Makefile for wxWindows MMedia library Cygwin/Mingw32).

WXDIR = ../../..

LIBTARGET=$(WXDIR)/contrib/lib/libmmedia.a
OBJECTS = cdbase.o cdwin.o g711.o g721.o g723_24.o \
  g723_40.o g72x.o sndaiff.o sndbase.o sndcodec.o \
  sndcpcm.o sndfile.o sndg72x.o sndpcm.o sndulaw.o \
  sndwav.o sndwin.o vidbase.o vidwin.o

include $(WXDIR)/src/makelib.g95

