#!/bin/sh
set -e

TEMPDIR=temp-debian

echo "creating Debian source tree ..."

rm -rf ${TEMPDIR}
mkdir ${TEMPDIR}
cd ${TEMPDIR} && ../configure --with-flavour="$1" && make debian-dist
cd .. && rm -r ${TEMPDIR}

echo "done."
echo " "
echo "  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "  If this is a new release version"
echo "  remember to update the changelog"
echo "  before building the package."
echo " "
if [ -n "$1" ]; then
    echo "  You will need a changelog entry"
    echo "  for: wxwidgets2.5-$1"
fi
echo "  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo " "


