#!/bin/sh
# makewxmotif
# Configures and makes wxMotif from either the root wxWindows directory
# or a build directory underneath it.

CONFIG=./configure

if [ ! -f ./configure ]; then
  CONFIG=../configure
fi

CONFIG="$CONFIG --disable-shared --with-motif --without-gtk --enable-debug_flag --enable-debug_info --enable-debug --disable-sockets --disable-odbc --enable-threads --enable-newgrid"

echo Invoking $CONFIG

rm -f *.cache
$CONFIG
make
