#
# File:         makefile.g95
# Author:       Julian Smart
# Created:      1999
# Updated:
# Copyright:    (c) Julian Smart, 1999
#
# Makefile for wxWindows sample (Cygwin/Mingw32).

WXDIR = ../../..

TARGET=test_med4
OBJECTS = $(TARGET).o
EXTRALIBS= ../lib/libwxmmedia2 -lwx -lwinmm

include $(WXDIR)\src\makeprog.g95

