# cotire.cmake 1.8.0 generated file
# D:/WxWidgets/MyOutputFolder/libs/base/wxbase_CXX_cotire.cmake
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_EXTENSIONS "inc;inl;ipp")
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_PATH "")
set (COTIRE_CLEAN_ALL_TARGET_NAME "clean_cotire")
set (COTIRE_CLEAN_TARGET_SUFFIX "_clean_cotire")
set (COTIRE_CMAKE_MODULE_FILE "D:/WxWidgets/build/cmake/modules/cotire.cmake")
set (COTIRE_CMAKE_MODULE_VERSION "1.8.0")
set (COTIRE_DEBUG "OFF")
set (COTIRE_INTDIR "cotire")
set (COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES "-j")
set (COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES "2")
set (COTIRE_PCH_ALL_TARGET_NAME "all_pch")
set (COTIRE_PCH_MEMORY_SCALING_FACTOR "170")
set (COTIRE_PCH_TARGET_SUFFIX "_pch")
set (COTIRE_PREFIX_HEADER_FILENAME_SUFFIX "_prefix")
set (COTIRE_TARGETS_FOLDER "cotire")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_DEBUG "CMAKE_INTDIR=\"Debug\";wxbase_EXPORTS;WXDLLNAME=wxbase316u_vc_custom;WXBUILDING;_LIB;wxUSE_GUI=0;wxUSE_BASE=1;UNICODE;_UNICODE;_CRT_SECURE_NO_DEPRECATE=1;_CRT_NON_CONFORMING_SWPRINTFS=1;_SCL_SECURE_NO_WARNINGS=1;_WINSOCK_DEPRECATED_NO_WARNINGS=1;__WXUWP__;DLL_EXPORTS;WXMAKINGDLL_BASE;WX_PRECOMP;WIN32;_WINDOWS")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_RELEASE "CMAKE_INTDIR=\"Release\";wxbase_EXPORTS;WXDLLNAME=wxbase316u_vc_custom;WXBUILDING;_LIB;wxUSE_GUI=0;wxUSE_BASE=1;UNICODE;_UNICODE;_CRT_SECURE_NO_DEPRECATE=1;_CRT_NON_CONFORMING_SWPRINTFS=1;_SCL_SECURE_NO_WARNINGS=1;_WINSOCK_DEPRECATED_NO_WARNINGS=1;__WXUWP__;DLL_EXPORTS;WXMAKINGDLL_BASE;WX_PRECOMP;WIN32;_WINDOWS;NDEBUG")
set (COTIRE_TARGET_COMPILE_FLAGS_DEBUG "/GR;/EHsc;/MP;/MDd;/Zi;/Ob0;/Od;/W4")
set (COTIRE_TARGET_COMPILE_FLAGS_RELEASE "/GR;/EHsc;/MP;/MD;/O2;/Ob2;/W4")
set (COTIRE_TARGET_CONFIGURATION_TYPES "Debug;Release")
set (COTIRE_TARGET_CXX_COMPILER_LAUNCHER "COTIRE_TARGET_CXX_COMPILER_LAUNCHER-NOTFOUND")
set (COTIRE_TARGET_IGNORE_PATH "D:/WxWidgets")
set (COTIRE_TARGET_INCLUDE_DIRECTORIES_DEBUG "D:/WxWidgets/3rdparty/pcre/src/wx;D:/WxWidgets/src/zlib;D:/WxWidgets/MyOutputFolder/lib/vc_x64_dll/uwpu;D:/WxWidgets/include")
set (COTIRE_TARGET_INCLUDE_DIRECTORIES_RELEASE "D:/WxWidgets/3rdparty/pcre/src/wx;D:/WxWidgets/src/zlib;D:/WxWidgets/MyOutputFolder/lib/vc_x64_dll/uwpu;D:/WxWidgets/include")
set (COTIRE_TARGET_INCLUDE_PRIORITY_PATH "")
set (COTIRE_TARGET_LANGUAGE "CXX")
set (COTIRE_TARGET_MAXIMUM_NUMBER_OF_INCLUDES "-j")
set (COTIRE_TARGET_POST_UNDEFS "")
set (COTIRE_TARGET_PRE_UNDEFS "")
set (COTIRE_TARGET_SOURCES "D:/WxWidgets/src/common/any.cpp;D:/WxWidgets/src/common/appbase.cpp;D:/WxWidgets/src/common/arcall.cpp;D:/WxWidgets/src/common/arcfind.cpp;D:/WxWidgets/src/common/archive.cpp;D:/WxWidgets/src/common/arrstr.cpp;D:/WxWidgets/src/common/base64.cpp;D:/WxWidgets/src/common/clntdata.cpp;D:/WxWidgets/src/common/cmdline.cpp;D:/WxWidgets/src/common/config.cpp;D:/WxWidgets/src/common/convauto.cpp;D:/WxWidgets/src/common/datetime.cpp;D:/WxWidgets/src/common/datetimefmt.cpp;D:/WxWidgets/src/common/datstrm.cpp;D:/WxWidgets/src/common/dircmn.cpp;D:/WxWidgets/src/common/dynlib.cpp;D:/WxWidgets/src/common/dynload.cpp;D:/WxWidgets/src/common/encconv.cpp;D:/WxWidgets/src/common/evtloopcmn.cpp;D:/WxWidgets/src/common/ffile.cpp;D:/WxWidgets/src/common/file.cpp;D:/WxWidgets/src/common/fileback.cpp;D:/WxWidgets/src/common/fileconf.cpp;D:/WxWidgets/src/common/filefn.cpp;D:/WxWidgets/src/common/filename.cpp;D:/WxWidgets/src/common/filesys.cpp;D:/WxWidgets/src/common/filtall.cpp;D:/WxWidgets/src/common/filtfind.cpp;D:/WxWidgets/src/common/fmapbase.cpp;D:/WxWidgets/src/common/fs_arc.cpp;D:/WxWidgets/src/common/fs_filter.cpp;D:/WxWidgets/src/common/hash.cpp;D:/WxWidgets/src/common/hashmap.cpp;D:/WxWidgets/src/common/init.cpp;D:/WxWidgets/src/common/intl.cpp;D:/WxWidgets/src/common/ipcbase.cpp;D:/WxWidgets/src/common/languageinfo.cpp;D:/WxWidgets/src/common/list.cpp;D:/WxWidgets/src/common/log.cpp;D:/WxWidgets/src/common/longlong.cpp;D:/WxWidgets/src/common/memory.cpp;D:/WxWidgets/src/common/mimecmn.cpp;D:/WxWidgets/src/common/module.cpp;D:/WxWidgets/src/common/mstream.cpp;D:/WxWidgets/src/common/numformatter.cpp;D:/WxWidgets/src/common/object.cpp;D:/WxWidgets/src/common/platinfo.cpp;D:/WxWidgets/src/common/powercmn.cpp;D:/WxWidgets/src/common/process.cpp;D:/WxWidgets/src/common/regex.cpp;D:/WxWidgets/src/common/secretstore.cpp;D:/WxWidgets/src/common/stdpbase.cpp;D:/WxWidgets/src/common/sstream.cpp;D:/WxWidgets/src/common/stdstream.cpp;D:/WxWidgets/src/common/stopwatch.cpp;D:/WxWidgets/src/common/strconv.cpp;D:/WxWidgets/src/common/stream.cpp;D:/WxWidgets/src/common/string.cpp;D:/WxWidgets/src/common/stringimpl.cpp;D:/WxWidgets/src/common/stringops.cpp;D:/WxWidgets/src/common/strvararg.cpp;D:/WxWidgets/src/common/sysopt.cpp;D:/WxWidgets/src/common/tarstrm.cpp;D:/WxWidgets/src/common/textbuf.cpp;D:/WxWidgets/src/common/textfile.cpp;D:/WxWidgets/src/common/threadinfo.cpp;D:/WxWidgets/src/common/time.cpp;D:/WxWidgets/src/common/timercmn.cpp;D:/WxWidgets/src/common/timerimpl.cpp;D:/WxWidgets/src/common/tokenzr.cpp;D:/WxWidgets/src/common/translation.cpp;D:/WxWidgets/src/common/txtstrm.cpp;D:/WxWidgets/src/common/unichar.cpp;D:/WxWidgets/src/common/uri.cpp;D:/WxWidgets/src/common/ustring.cpp;D:/WxWidgets/src/common/variant.cpp;D:/WxWidgets/src/common/wfstream.cpp;D:/WxWidgets/src/common/wxcrt.cpp;D:/WxWidgets/src/common/wxprintf.cpp;D:/WxWidgets/src/common/xlocale.cpp;D:/WxWidgets/src/common/xti.cpp;D:/WxWidgets/src/common/xtistrm.cpp;D:/WxWidgets/src/common/zipstrm.cpp;D:/WxWidgets/src/common/zstream.cpp;D:/WxWidgets/src/common/fswatchercmn.cpp;D:/WxWidgets/src/generic/fswatcherg.cpp;D:/WxWidgets/src/common/lzmastream.cpp;D:/WxWidgets/src/common/uilocale.cpp;D:/WxWidgets/src/common/event.cpp;D:/WxWidgets/src/common/fs_mem.cpp;D:/WxWidgets/src/common/msgout.cpp;D:/WxWidgets/src/common/utilscmn.cpp;D:/WxWidgets/src/msw/basemsw.cpp;D:/WxWidgets/src/msw/crashrpt.cpp;D:/WxWidgets/src/msw/debughlp.cpp;D:/WxWidgets/src/msw/dde.cpp;D:/WxWidgets/src/msw/dir.cpp;D:/WxWidgets/src/msw/dlmsw.cpp;D:/WxWidgets/src/msw/evtloopconsole.cpp;D:/WxWidgets/src/msw/mimetype.cpp;D:/WxWidgets/src/msw/power.cpp;D:/WxWidgets/src/msw/regconf.cpp;D:/WxWidgets/src/msw/registry.cpp;D:/WxWidgets/src/msw/secretstore.cpp;D:/WxWidgets/src/msw/snglinst.cpp;D:/WxWidgets/src/msw/stackwalk.cpp;D:/WxWidgets/src/msw/stdpaths.cpp;D:/WxWidgets/src/msw/thread.cpp;D:/WxWidgets/src/msw/timer.cpp;D:/WxWidgets/src/msw/utils.cpp;D:/WxWidgets/src/msw/utilsexc.cpp;D:/WxWidgets/src/msw/fswatcher.cpp;D:/WxWidgets/src/msw/uilocale.cpp;D:/WxWidgets/src/msw/main.cpp;D:/WxWidgets/src/msw/volume.cpp")
set (COTIRE_UNITY_BUILD_ALL_TARGET_NAME "all_unity")
set (COTIRE_UNITY_BUILD_TARGET_SUFFIX "_unity")
set (COTIRE_UNITY_OUTPUT_DIRECTORY "")
set (COTIRE_UNITY_SOURCE_EXCLUDE_EXTENSIONS "m;mm")
set (COTIRE_UNITY_SOURCE_FILENAME_SUFFIX "_unity")
set (MSVC "1")
set (CMAKE_GENERATOR "Visual Studio 17 2022")
set (CMAKE_CONFIGURATION_TYPES "Debug;Release")
set (CMAKE_CXX_COMPILER_ID "MSVC")
set (CMAKE_CXX_COMPILER_VERSION "19.30.30706.0")
set (CMAKE_CXX_COMPILER "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe")
set (CMAKE_CXX_COMPILER_ARG1 "")
set (CMAKE_INCLUDE_FLAG_CXX "-I")
set (CMAKE_INCLUDE_SYSTEM_FLAG_CXX "-external:I ")
set (CMAKE_CXX_SOURCE_FILE_EXTENSIONS "C;M;c++;cc;cpp;cxx;mm;mpp;CPP;ixx;cppm")
