#
# File:		makefile.b32
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:
#
# Makefile : Builds sample for 32-bit BC++

WXDIR = $(WXWIN)

TARGET=ogledit
EXTRALIBS=$(WXDIR)\contrib\lib\ogl.lib
# EXTRACPPFLAGS=-I$(WXDIR)\utils\ogl\src
OBJECTS = $(TARGET).obj doc.obj view.obj palette.obj

!include $(WXDIR)\src\makeprog.b32

