// A bunch of %rename directives generated by ./distrib/build_renamers.py
// in order to remove the wx prefix from all global scope names.

#ifndef SWIGXML

%rename(GLContext)                          wxGLContext;
%rename(GLCanvasWithContext)                wxGLCanvasWithContext;
%rename(GLCanvas)                           wxGLCanvas;

#endif
