#
# File:         makefile.g95
# Author:       Michael Bedward
# Created:      1999
# Updated:
#
# Makefile for wxWindows sample (Cygwin/Mingw32).

WXDIR = ../..

TARGET=griddemo
OBJECTS = $(TARGET).o

include $(WXDIR)/src/makeprog.g95

