#
# File:		makefile.vc
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:	(c) Julian Smart
#
# Makefile : Builds sample (VC++, WIN32)
# Use FINAL=1 argument to nmake to build final version with no debug info.

# Set WXDIR for your system
WXDIR = $(WXWIN)
FINAL=0
PROGRAM=resource
!if "$(FINAL)" == "0"
EXTRALIBS=$(WXDIR)\lib\wxdeprecatedd.lib
!else
EXTRALIBS=$(WXDIR)\lib\wxdeprecated.lib
!endif
OBJECTS = $(PROGRAM).obj

!include $(WXDIR)\src\makeprog.vc

