#
# File:         makefile.g95
# Author:       Julian Smart
# Created:      1999
# Updated:
# Copyright:    (c) Julian Smart, 1999
#
# Makefile for wxWindows sample (Cygwin/Mingw32).

WXDIR = ../../../..

TARGET=resource
OBJECTS = $(TARGET).o
EXTRAINC = -I$(WXDIR)/contrib/include
EXTRALIBS = -lwxdeprecated

include $(WXDIR)/src/makeprog.g95

