# File:     makefile.g95 for Plot demo
# Author:	Julian Smart
# Created:	2001-06-12
# Updated:

WXDIR = ../../../..

TARGET = simple
OBJECTS = $(TARGET).o
EXTRAINC = -I$(WXDIR)/contrib/include
EXTRALIBS = -lcanvas

include $(WXDIR)/src/makeprog.g95

