#
# File:		makefile.b32
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:
#
# Makefile : Builds sample for 32-bit BC++

WXDIR = $(WXWIN)

TARGET=simple

EXTRALIBS=$(WXDIR)\lib\canvas.lib
OBJECTS = $(TARGET).obj

!include $(WXDIR)\src\makeprog.b32

