#!/bin/sh

SETUP="python$PYVER -u setup.py"
FLAGS="USE_SWIG=1 IN_CVS_TREE=1"

# "c" --> clean
if [ "$1" =  "c" ]; then
    shift
    CMD="$SETUP $FLAGS clean"
    OTHERCMD="rm -f wxPython/*.so"

# "i" --> install
elif [ "$1" = "i" ]; then
    shift
    CMD="$SETUP build install"

# "s" --> source dist
elif [ "$1" = "s" ]; then
    shift
    CMD="$SETUP sdist"

# "r" --> rpm dist
elif [ "$1" = "r" ]; then
    shift
    CMD="$SETUP bdist_rpm"

# (no command arg) --> normal build for development
else
    CMD="$SETUP $FLAGS build_ext --inplace $*"
fi


echo $CMD
$CMD


if [ "$OTHERCMD" != "" ]; then
    echo $OTHERCMD
    $OTHERCMD
fi

