#!/bin/sh
# makewxmac
# Configures and makes wxMac for MacOS X from either the root wxWindows
# directory or a build directory underneath it.

CONFIG=./configure

if [ ! -f ./configure ]; then
  CONFIG=../configure
fi

CONFIG="$CONFIG --disable-shared --enable-debug --enable-debug_cntxt --with-threads --without-sockets --without-odbc --enable-mem_tracing"

echo Invoking $CONFIG

rm -f *.cache
$CONFIG

make

