#
# File:		makefile.g95
# Author:	Julian Smart
# Created:	1993
# Updated:	
# Copyright:	(c) 1993, AIAI, University of Edinburgh
#
# "%W% %G%"
#
# Makefile for server/client example (UNIX).

all:
	make -f client.g95 all
	make -f server.g95 all

clean:
	make -f client.g95 clean
	make -f server.g95 clean

