
#----------------------------------------------------------------------

TARGET = glcanvasc

OBJECTS = glcanvas.obj

PYMODULES = $(TARGETDIR)\html.py $(TARGETDIR)\htmlhelper.py 

SOURCES = $(GENCODEDIR)\html.cpp 


#----------------------------------------------------------------------

!include ..\makeinc.vc

# override this
EXTRAINC = $(EXTRAINC) -I$(WXDIR)\utils\glcanvas\win
GLLIBS=$(WXDIR)\lib\glcanvas.lib glu32.lib opengl32.lib

#----------------------------------------------------------------------

default: $(TARGETDIR)\$(TARGET).pyd pycfiles

all:    $(TARGET)

#----------------------------------------------------------------------

$(TARGETDIR)\$(TARGET).pyd : $(DUMMYOBJ) $(WXLIB) $(OBJECTS) # $(TARGET).res
	$(link) @<<
/out:$@ /dll
$(LFLAGS) /def:$(TARGET).def /implib:./$(TARGET).lib
$(DUMMYOBJ) $(OBJECTS) 
$(LIBS) $(GLLIBS)
<<

#----------------------------------------------------------------------

