#!/bin/sh

# you need to change this if you run from outside this dir.
if [ "$WXROOT" = "" ]; then
  WXROOT=../../..
fi

. $WXROOT/distrib/scripts/includes/configure_build.inc

. $WXROOT/distrib/scripts/mac/mac_options.inc

# most of this script is shared with other Mac-based and other
# configure-based build scripts, which is why this looks a little empty.

if [ "$UNIVERSAL" = "1" ]; then
  OTHER_OPTS="--enable-universal_binary "
fi

do_build

make prefix=$INSTALLDIR install

cd $OLDDIR
