#
# File:		makefile.dos
# Author:	Julian Smart
# Created:	1998
# Updated:	
#
# Makefile : Builds 16-bit sample, VC++ 1.5
# Use FINAL=1 argument to nmake to build final version with no debugging
# info

WXDIR = $(WXWIN)

TARGET=forty
OBJECTS = $(TARGET).obj canvas.obj card.obj game.obj pile.obj playerdg.obj scoredg.obj scorefil.obj

!include $(WXDIR)\src\makeprog.msc

