#!/bin/bash
#----------------------------------------------------------------------

if [ ! -d wxPython ]; then
    echo "Please run this script from the root wxPython directory."
    exit 1
fi

VERSION=`python -c "import setup;print setup.VERSION"`

mkdir _distrib_tgz
mkdir _distrib_tgz/wxPython-$VERSION

cp -R demo _distrib_tgz/wxPython-$VERSION
cp -R samples _distrib_tgz/wxPython-$VERSION

# do some cleanup
rm -rf `find _distrib_tgz/wxPython-$VERSION -name CVS`
rm -f `find  _distrib_tgz/wxPython-$VERSION -name "*.pyc"`
rm -f `find  _distrib_tgz/wxPython-$VERSION -name .cvsignore`
rm -f `find  _distrib_tgz/wxPython-$VERSION -name "core.[0-9]*"`
rm -f `find  _distrib_tgz/wxPython-$VERSION -name "core"`
rm -f `find  _distrib_tgz/wxPython-$VERSION -name wxPython`
rm -f `find  _distrib_tgz/wxPython-$VERSION -name "*.o"`
rm -f `find  _distrib_tgz/wxPython-$VERSION -name "*.so"`
rm -f `find  _distrib_tgz/wxPython-$VERSION -name "*~"`
rm -f `find  _distrib_tgz/wxPython-$VERSION -name ".#*"`

cd _distrib_tgz

tar cvf ../dist/wxPython-demo-$VERSION.tar wxPython-$VERSION
gzip -9 ../dist/wxPython-demo-$VERSION.tar

cd ..
rm -r _distrib_tgz




