#!/bin/bash
#----------------------------------------------------------------------

if [ -z $1 ]; then
    echo "Please specify a version number on the command line."
    exit 1
fi

if [ ! -d wxPython ]; then
    echo "Please run this script from the root wxPython directory."
    exit 1
fi

mkdir _distrib_tgz
mkdir _distrib_tgz/wxPython-$1

cp -R demo _distrib_tgz/wxPython-$1
cp -R samples _distrib_tgz/wxPython-$1

# do some cleanup
rm -rf `find _distrib_tgz/wxPython-$1 -name CVS`
rm -f `find  _distrib_tgz/wxPython-$1 -name "*.pyc"`
rm -f `find  _distrib_tgz/wxPython-$1 -name .cvsignore`
rm -f `find  _distrib_tgz/wxPython-$1 -name "core*"`
rm -f `find  _distrib_tgz/wxPython-$1 -name wxPython`
rm -f `find  _distrib_tgz/wxPython-$1 -name "*.o"`
rm -f `find  _distrib_tgz/wxPython-$1 -name "*.so"`
rm -f `find  _distrib_tgz/wxPython-$1 -name "*~"`
rm -f `find  _distrib_tgz/wxPython-$1 -name ".#*"`

cd _distrib_tgz

tar cvf ../dist/wxPythonDemo-$1.tar wxPython-$1
gzip -9 ../dist/wxPythonDemo-$1.tar

cd ..
rm -r _distrib_tgz




