#!/bin/bash
#----------------------------------------------------------------------

if [ ! -d wxPython -o ! -e distrib/makerpm ]; then
    echo "Please run this script from the root wxPython directory."
    exit 1
fi




distrib/makerpm    2.2   skipclean                  srpm
distrib/makerpm    2.3   skipclean skipcopy skiptar srpm
distrib/makerpm    2.2   skipclean skipcopy skiptar srpm gtk2
distrib/makerpm    2.3   skipclean skipcopy skiptar srpm gtk2