#
# File:		makefile.b32
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:
#
# Makefile : Builds sample for 32-bit BC++

WXDIR = $(WXWIN)

TARGET=isosurf
# EXTRALIBS=$(WXDIR)\lib\glcanvas.lib
# EXTRACPPFLAGS=-I$(WXDIR)\utils\glcanvas\win
OBJECTS = $(TARGET).obj
EXTRATARGETS=isosurf.dat

!include $(WXDIR)\src\makeprog.b32

isosurf.dat:    isosurf.dat.gz
    gzip -c -d isosurf.dat.gz > isosurf.dat

