#
# File:         makefile.g95
# Author:       Julian Smart
# Created:      1999
# Updated:
# Copyright:    (c) Julian Smart, 1999
#
# Makefile for wxWindows dcsvg library Cygwin/Mingw32).

WXDIR = ../../..

LIBTARGET=$(WXDIR)/lib/libdcsvg.a
OBJECTS = dcsvg.o

include $(WXDIR)/src/makelib.g95

