
#----------------------------------------------------------------------

TARGET = lseditorc

OBJECTS = lseditor.obj finddlg.obj lseditorpl.obj markup.obj \
	plugin.obj sourcepainter.obj tdefs.objhtml.obj

PYMODULES = $(TARGETDIR)\lseditor.py 

SOURCES = $(GENCODEDIR)/lseditor.cpp finddlg.cpp lseditorpl.cpp markup.cpp \
	plugin.cpp sourcepainter.cpp tdefs.cpp


#----------------------------------------------------------------------

!include ..\makeinc.vc
# undo overrideflags /GX- ...
OVERRIDEFLAGS=$(OTHERCFLAGS)

#----------------------------------------------------------------------

default: $(TARGETDIR)\$(TARGET).pyd pycfiles

all:    $(TARGET)

# for generating the html.cpp file
$(GENCODEDIR)/lseditor.cpp : lseditor.i

#----------------------------------------------------------------------

$(TARGETDIR)\$(TARGET).pyd : $(DUMMYOBJ) $(WXLIB) $(OBJECTS) # $(TARGET).res
	$(link) @<<
/out:$@ /dll
$(LFLAGS) /def:$(TARGET).def /implib:./$(TARGET).lib
$(DUMMYOBJ) $(OBJECTS) 
$(LIBS)
<<


#----------------------------------------------------------------------

