#
# File:		makefile.unx
# Author:	Julian Smart
# Created:	1998
# Updated:	
# Copyright:	(c) 1998 Julian Smart
#
# "%W% %G%"
#
# Makefile for dbtest example (UNIX).

PROGRAM=dbtest

OBJECTS=$(PROGRAM).o listdb.o

include ../../src/makeprog.env

