#
# File:         makefile.g95
# Author:       Julian Smart
# Created:      1999
# Updated:
# Copyright:    (c) Julian Smart, 1999
#
# Makefile for wxWindows sample (Cygwin/Mingw32).

WXDIR = ../..

TARGET=dbtest
OBJECTS = $(TARGET).o listdb.o

include $(WXDIR)/src/makeprog.g95

