#
# File:		makefile.nt
# Author:	George Tasker
# Created:	1998
# Updated:	
#
# "%W% %G%"
#
# Makefile : Builds database example (MS VC++).

!if "$(FINAL)" == ""
FINAL=0
!endif


!if "$(MSVCDIR)" == ""
MSVCDIR=c:\devstudio\vc
!endif

# Set WXDIR for your system
WXDIR     = $(WXWIN)
THISDIR   = $(WXDIR)\samples\database
WXODBCDIR = $(WXDIR)\utils\wxodbc

!if "$(MSVCDIR)" == ""
DBLIBS=$(MSDEVDIR)\lib\odbc32.lib
!else
DBLIBS=$(MSVCDIR)\lib\odbc32.lib
!endif

EXTRAINC = -I$(WXODBCDIR)\src
EXTRALIBS = $(DBLIBS) $(WXODBCDIR)\lib\wxodbc.lib

!include $(WXDIR)\src\ntwxwin.mak

PROGRAM=database

OBJECTS = $(PROGRAM).$(OBJSUFF) listdb.$(OBJSUFF)

all:    wxodbc $(PROGRAM).exe

$(PROGRAM):    $(PROGRAM).exe

gt:
		cd $(CPPFLAGS)

wxodbc:
        cd $(WXODBCDIR)\src
        nmake -f makefile.nt FINAL=$(FINAL)
        cd $(THISDIR)

wx:
        cd $(WXDIR)\src\msw
        nmake -f makefile.nt FINAL=$(FINAL)
        cd $(THISDIR)

wxclean:
        cd $(WXDIR)\src\msw
        nmake -f makefile.nt clean
        cd $(THISDIR)
        cd $(WXODBCDIR)\src
        nmake -f makefile.nt clean
        cd $(THISDIR)


$(PROGRAM).exe: $(DUMMYOBJ) $(OBJECTS) $(PROGRAM).res
	$(link) @<<
-out:$(PROGRAM).exe
$(LINKFLAGS)
$(DUMMYOBJ) $(OBJECTS) $(PROGRAM).res
$(LIBS)
<<


listdb.$(OBJSUFF): $(*B).$(SRCSUFF) $(*B).h 
	$(cc) @<<
$(CPPFLAGS) /c /Fo$(*B).$(OBJSUFF) /Tp $(*B).$(SRCSUFF)
<<


$(PROGRAM).$(OBJSUFF): $(PROGRAM).$(SRCSUFF) $(PROGRAM).h listdb.h
	$(cc) @<<
$(CPPFLAGS) /c /Fo$(*B).$(OBJSUFF) /Tp $(*B).$(SRCSUFF)
<<


$(PROGRAM).res: $(PROGRAM).rc $(WXDIR)\include\wx\msw\wx.rc
    $(rc) -r /i$(WXDIR)\include -fo$@ $(PROGRAM).rc


clean:
        -erase *.obj
        -erase *.exe
        -erase *.res
        -erase *.map
        -erase *.sbr
        -erase *.pdb
