#
# File:		makefile.dos
# Author:	Julian Smart
# Created:	1998
# Updated:	
#
# Makefile : Builds 16-bit sample, VC++ 1.5
# Use FINAL=1 argument to nmake to build final version with no debugging
# info

# This sample will not build any longer (most likely)
# without heavy mods to the db/dbtable classes

WXDIR = $(WXWIN)

TARGET=dbtest
OBJECTS=$(TARGET).obj listdb.obj

!include $(WXDIR)\src\makeprog.msc

