#!/bin/sh
# Build application and make a tarball.

cd ~/wxconfigtool-build

echo Building wxWindows...
makeapp release wx

rm -f wxconfigtool-build-release/wxconfigtool

if [ "$1" = "clean" ]; then
  rm -f wxconfigtool-build-release/*
fi

echo Building Application...
makeapp release all

if [ ! -f wxconfigtool-build-release/wxconfigtool ]; then
  echo *** Sorry, wxconfigtool was not built correctly.
  exit
fi

echo Making tarball...
makeapp release release

# appver will have been written by the 'release' target.
APPVER=`/tmp/appver`

cd /tmp/wxconfigtool-deliver
APPARCHIVE=wxconfigtool-$APPVER-i386.tar.gz

# echo Copying tarball $APPARCHIVE to ftp site...
# You can use a script to copy this to an ftp site,
# using for example, the 'curl' utility.
# curl ftp://www.mysite.com/$APPARCHIVE --user "myname:mypassword" --upload-file $APPARCHIVE

echo Done building and archiving wxconfigtool.
