#!/bin/sh
# Build application

# The first argument is debug or release
LEVEL=$1

# Then you can supply one or more makefile targets
TARGET="$2 $3 $4 $5 $6 $6 $7 $8 $9"

if [ "$1" = "" ] || [ "$2" = "" ]; then
  echo Usage: makeapp debug/release full/wx/genericapp/cleanall
  exit
fi

export APPDIR=$WXWIN/utils/configtool
export WXDIR=$WXWIN
export WXBUILDDIR=wxwin-build-$LEVEL

# If there's no wxwin-build-... directory yet, the makefile
# must include a dummy makeprog.env
export USEDUMMYMAKEPROG="0"
if [ ! -f $WXBUILDDIR/src/makeprog.env ]; then
  USEDUMMYMAKEPROG="1"
fi
 
make -f ${APPDIR}/src/Makefile WXDIR=$WXDIR USEDUMMYMAKEPROG=$USEDUMMYMAKEPROG APPDIR=$APPDIR WXBUILDDIR=$WXBUILDDIR LEVEL=$LEVEL $TARGET
