#!/bin/sh -e
# 
# build binary package and put it on a disk image
# 
# usage: build [-s dir] [-d dir] [--cvs-update] [--force] [--debug]
# 
# (C)opyright 2002 Frank Vercruesse


prog="`dirname \"$0\"`/_`basename \"$0\"`"
sudo "$prog" "${USER?'USER not set.'}" "$@"
