#
# File:		makefile.bcc
# Author:	Julian Smart
# Created:	1998
# Updated:	
#
# Builds a BC++ 16-bit sample

!if "$(WXWIN)" == ""
!error You must define the WXWIN variable in autoexec.bat, e.g. WXWIN=c:\wx
!endif

WXDIR = $(WXWIN)

TARGET=bombs
OBJECTS=$(TARGET).obj bombs1.obj game.obj

!include $(WXDIR)\src\makeprog.bcc

