# File:     makefile.g95 for stectrl
# Author:	Robin Dunn
# Created:	1-Feb-2000
# Updated:

WXDIR = ../../..

TARGET = xrcdemo
OBJECTS = $(TARGET).o \
	myframe.o \
        derivdlg.o \
	custclas.o
EXTRAINC = -I$(WXDIR)/contrib/include
EXTRALIBS = -lwxxrc

include $(WXDIR)/src/makeprog.g95


