# Purpose: makefile for proplist example (BC++ 16bit)
# Created: 2000-03-15

!if "$(WXWIN)" == ""
!error You must define the WXWIN variable in autoexec.bat, e.g. WXWIN=c:\wx
!endif

WXDIR = $(WXWIN)

TARGET=proplist
OBJECTS=$(TARGET).obj

!include $(WXDIR)\src\makeprog.bcc

