# Purpose: makefile for multicell example (BC++ 32bit)
# Created 2000-07-28

WXDIR = $(WXWIN)

TARGET=mtest
OBJECTS = $(TARGET).obj
EXTRALIBS=$(WXDIR)\lib\gizmos.lib

!include $(WXDIR)\src\makeprog.b32

