# Purpose: makefile for multicell example (Unix)
# Created 2000-07-28

CC = gcc

PROGRAM = mtest

OBJECTS = $(PROGRAM).o ../src/multicell.o
EXTRAINC=-I../include

# implementation

.SUFFIXES:	.o .cpp

.cpp.o :
	$(CC) -c `wx-config --cflags` -o $@ $<

all:    $(PROGRAM)

$(PROGRAM):	$(OBJECTS)
	$(CC) -o $(PROGRAM) $(OBJECTS) `wx-config --libs`

clean:
	rm -f *.o $(PROGRAM)
