# Purpose: makefile for multicell example (Cygwin/Mingw32)
# Created 2000-07-28

WXDIR = ../../../..

TARGET=mtest
OBJECTS = $(TARGET).o
EXTRALIBS=$(WXDIR)/lib/libgizmos.lib

include $(WXDIR)/src/makeprog.g95

