# Purpose: makefile for multicell example (VC++ 1.5x)
# Created 2000-07-28

WXDIR = $(WXWIN)

TARGET=mtest
OBJECTS = $(TARGET).obj ..\src\multicell.obj
EXTRAINC=-I..\include

!include $(WXDIR)\src\makeprog.msc

