# File:		makefile.vc for svgtest sample
# Author:	Julian Smart
# Created:	2001-06-12
# Updated:

WXDIR = $(WXWIN)
PROGRAM = svgtest

OBJECTS = $(PROGRAM).obj
EXTRALIBS = $(WXDIR)\lib\dcsvg$(LIBEXT).lib
EXTRAINC = -I$(WXDIR)\contrib\include

!include $(WXDIR)\src\makeprog.vc

