# File:     makefile.g95 for svgtest demo
# Author:	Julian Smart
# Created:	2001-06-12
# Updated:

WXDIR = ../../..

TARGET = svgtest
OBJECTS = $(TARGET).o
EXTRAINC = -I$(WXDIR)/contrib/include
RCEXTRAINC = --include-dir $(WXDIR)/contrib/include
EXTRALIBS = -ldcsvg

include $(WXDIR)/src/makeprog.g95

