#
# File:		makefile.b32
# Author:	Julian Smart Chris Elliott
# Created:	1999/2002
# Updated:	
# Copyright:
#
# Makefile : Builds sample for 32-bit BC++

EXTRALIBS=$(WXDIR)\lib\dcsvg.lib

WXDIR = $(WXWIN)

TARGET=svgtest
OBJECTS = $(TARGET).obj 

!include $(WXDIR)\src\makeprog.b32

