# File:		makefile.vc  For stectrl
# Author:	Robin Dunn
# Created:	1-Feb-2000
# Updated:

WXDIR = $(WXWIN)
PROGRAM = stctest

OBJECTS = $(PROGRAM).obj edit.obj prefs.obj
EXTRALIBS = $(WXDIR)\lib\stc$(LIBEXT).lib
EXTRAINC = -I$(WXDIR)\contrib\include

!include $(WXDIR)\src\makeprog.vc

