# File:		makefile.vc  For stectrl
# Author:	Robin Dunn
# Created:	1-Feb-2000
# Updated:

WXDIR = $(WXWIN)
PROGRAM = xrcdemo

OBJECTS = $(PROGRAM).obj myframe.obj derivdlg.obj custclas.obj

EXTRALIBS = $(WXDIR)\lib\wxxrc$(LIBEXT).lib
EXTRAINC = -I$(WXDIR)\contrib\include

!include $(WXDIR)\src\makeprog.vc


