#
# File:		makefile.b32
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:
#
# Makefile : Builds sample for 32-bit BC++

WXDIR = $(WXWIN)

TARGET=xrcdemo

EXTRALIBS=$(WXDIR)\lib\wxxrc.lib
OBJECTS = $(TARGET).obj \
	myframe.obj \
        derivdlg.obj \
	custclas.obj

!include $(WXDIR)\src\makeprog.b32


