#!/bin/sh
# makewxx11
# Configures and makes wxX11 from either the root wxWindows directory
# or a build directory underneath it.

CONFIG=./configure

if [ ! -f ./configure ]; then
  CONFIG=../configure
fi

CONFIG="$CONFIG --disable-shared --enable-gui --with-x11 --enable-debug_flag --enable-log --enable-debug_info --enable-debug --enable-threads --enable-mdi --enable-sockets --without-odbc --with-libjpeg --with-opengl --enable-debug_cntxt"

echo Invoking $CONFIG

rm -f *.cache
$CONFIG

make

