#
# File:		makefile.nt
# Author:	Julian Smart
# Created:	1993
# Updated:	
# Copyright:	(c) 1993, AIAI, University of Edinburgh
#
# "%W% %G%"
#
# Makefile : Builds docview example (MS VC++).
# Use FINAL=1 argument to nmake to build final version with no debugging
# info

# Set WXDIR for your system
WXDIR = $(WXWIN)

WXUSINGDLL=0

!include $(WXDIR)\src\ntwxwin.mak

THISDIR = $(WXDIR)\samples\docvwmdi
PROGRAM=docview
 
OBJECTS = $(PROGRAM).obj doc.obj view.obj

$(PROGRAM):    $(PROGRAM).exe

all:    wx $(PROGRAM).exe

wx:
        cd $(WXDIR)\src\msw
        nmake -f makefile.nt FINAL=$(FINAL)
        cd $(THISDIR)

wxclean:
        cd $(WXDIR)\src\msw
        nmake -f makefile.nt clean
        cd $(THISDIR)

$(PROGRAM).exe:      $(DUMMYOBJ) $(WXLIB) $(OBJECTS) $(PROGRAM).res
	$(link) @<<
-out:$(PROGRAM).exe
$(LINKFLAGS)
$(DUMMYOBJ) $(OBJECTS) $(PROGRAM).res
$(LIBS)
<<

$(PROGRAM).obj:      $(PROGRAM).h doc.h view.h $(PROGRAM).$(SRCSUFF) $(DUMMYOBJ)
        $(cc) @<<
$(CPPFLAGS) /c /Tp $*.$(SRCSUFF)
<<

doc.obj:      doc.h doc.$(SRCSUFF) $(DUMMYOBJ)
        $(cc) @<<
$(CPPFLAGS) /c /Tp $*.$(SRCSUFF)
<<

view.obj:      view.h view.$(SRCSUFF) $(DUMMYOBJ)
        $(cc) @<<
$(CPPFLAGS) /c /Tp $*.$(SRCSUFF)
<<

$(PROGRAM).res :      $(PROGRAM).rc $(WXDIR)\include\wx\msw\wx.rc
    $(rc) -r /i$(WXDIR)\include -fo$@ $(PROGRAM).rc


clean:
        -erase *.obj
        -erase *.exe
        -erase *.res
        -erase *.map
        -erase *.pdb
        -erase *.sbr


