
#----------------------------------------------------------------------

TARGET = samplec

OBJECTS = sample.obj mywidget.obj

PYMODULES = $(TARGETDIR)\sample.py 

SOURCES = $(GENCODEDIR)\sample.cpp mywidget.cpp


#----------------------------------------------------------------------

!include ..\makeinc.vc

#----------------------------------------------------------------------

default: $(TARGETDIR)\$(TARGET).pyd pycfiles

all:    $(TARGET)

# dependency to automatically generate swig files
$(GENCODEDIR)/sample.cpp : sample.i

#----------------------------------------------------------------------

$(TARGETDIR)\$(TARGET).pyd : $(DUMMYOBJ) $(WXLIB) $(OBJECTS) # $(TARGET).res
	$(link) @<<
/out:$@ /dll
$(LFLAGS) /def:$(TARGET).def /implib:./$(TARGET).lib
$(DUMMYOBJ) $(OBJECTS) 
$(LIBS)
<<


#----------------------------------------------------------------------

