# Purpose: makefile for statbar example (BC++ 16bit)
# Created: 2000-02-04

!if "$(WXWIN)" == ""
!error You must define the WXWIN variable in autoexec.bat, e.g. WXWIN=c:\wx
!endif

WXDIR = $(WXWIN)

TARGET=statbar
OBJECTS=$(TARGET).obj

!include $(WXDIR)\src\makeprog.bcc

