#!/bin/bash

if [ -z $1 ]; then
    echo "Please specify a version number on the command line."
    exit 1
fi

if [ ! -f wxPython.spec.in ]; then
    echo "Please run this script from the directory containing the wxPython.spec.in file."
    exit 1
fi



strip /usr/lib/python1.5/site-packages/wxPython/*.so
strip /usr/lib/libwxPyHelpers.so

cat wxPython.spec.in | sed s/__VERSION__/$1/g > wxPython.spec

mkdir /usr/doc/wxPython-$1
cp ../README.txt /usr/doc/wxPython-$1
cp ../../../docs/preamble.txt /usr/doc/wxPython-$1
cp ../../../docs/licence.txt /usr/doc/wxPython-$1
cp ../../../docs/licendoc.txt /usr/doc/wxPython-$1
cp ../../../docs/lgpl.txt /usr/doc/wxPython-$1
cp ../../../docs/gpl.txt /usr/doc/wxPython-$1

rpm -bb wxPython.spec

mv /usr/src/redhat/RPMS/*/wxPython*.rpm .
chown rd:users wxPython*.rpm

rm -r /usr/doc/wxPython-$1