#!/bin/bash

if [ -z $1 ]; then
    echo "Please specify a version number on the command line."
    exit 1
fi

if [ ! -f wxPython.spec.in ]; then
    echo "Please run this script from the directory containing the wxPython.spec.in file."
    exit 1
fi



mkdir i386
strip /usr/lib/python1.5/site-packages/wxPython/wxcmodule.so

cat wxPython.spec.in | sed s/__VERSION__/$1/g > wxPython.spec
rpm --rcfile .rpmrc -bb --clean wxPython.spec

mv i386/*.rpm .
rm -rf i386
