#
# File:		makefile.unx
# Author:	Julian Smart
# Created:	1998
# Updated:	
# Copyright:	(c) 1998 Julian Smart
#
# Makefile for penguin example (UNIX).

PROGRAM=penguin

OPENGLHOME=/home/jacs/mesa/Mesa-2.3

EXTRACPPFLAGS=-I$(OPENGLHOME)/include # -I../../motif
EXTRALDFLAGS=-L$(OPENGLHOME)/lib
EXTRALDLIBS=-lMesaGL -lMesaGLU

OBJECTS=$(PROGRAM).o trackball.o lw.o

include ../../../src/makeprog.env

