#
# File:         makefile.g95
# Author:       Julian Smart
# Created:      1999
# Updated:
# Copyright:    (c) Julian Smart, 1999
#
# Makefile for wxWindows sample (Cygwin/Mingw32).

WXDIR = ../../..

TARGET=penguin
#EXTRACPPFLAGS=-I../../win
EXTRALIBS=-lopengl32 -lglu32
OBJECTS = $(TARGET).o lw.o trackball.o

include $(WXDIR)/src/makeprog.g95

