/////////////////////////////////////////////////////////////////////////////
// Name:        class_mobile.h
// Purpose:     Basic wxMobile UI classes
// Author:      Julian Smart
// RCS-ID:      $Id$
// Licence:     wxWindows Licence
/////////////////////////////////////////////////////////////////////////////

/**

@defgroup group_class_wxMobile wxMobile UI classes
@ingroup group_class

Please note when reading the class documentation, that when including a file you use the form wx/mobile/window.h
rather than wx/mobile/generic/window.h as generated by Doxygen.

These classes provide the basic wxMobile user interface functionality.

*/

