#
# File:		makefile.b32
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:
#
# Makefile : Builds application for 32-bit BC++

WXDIR = $(WXWIN)

TARGET=wxconfigtool
OBJECTS = $(TARGET).obj wxconfigtool.obj appsettings.obj configitem.obj \
 configitemselector.obj configtooldoc.obj configtoolview.obj configtree.obj \
 custompropertydialog.obj htmlparser.obj mainframe.obj propeditor.obj \
 property.obj settingsdialog.obj utils.obj

!include $(WXDIR)\src\makeprog.b32

