#!################################################################################
#! File:    univ.t
#! Purpose: tmake template file from which src/univ/files.lst containing the
#!          list of files for wxUniversal library is generated by tmake
#! Author:  Vadim Zeitlin
#! Created: 26.06.01
#! Version: $Id$
#!################################################################################
#${
    #! include the code which parses filelist.txt file and initializes
    #! %wxCommon, %wxGeneric, %wxHtml, %wxUNIX, %wxGTK, %wxMOTIF and
    #! %wxOS2PM hashes.
    IncludeTemplate("filelist.t");

    #! find all our sources
    foreach $file (sort keys %wxUNIV) {
        ($fileobj = $file) =~ s/cp?p?$/\o/;
        ($filedep = $file) =~ s/cp?p?$/\d/;

        $project{"UNIV_SOURCES"} .= "univ/" . $file . " ";
        $project{"UNIVOBJS"} .= $fileobj . " ";
        $project{"UNIVDEPS"} .= $filedep . " ";
    }

#$}
# This file was automatically generated by tmake at #$ Now()
# DO NOT CHANGE THIS FILE, YOUR CHANGES WILL BE LOST! CHANGE GTK.T!
UNIVOBJS = \
		#$ ExpandList("UNIVOBJS");

UNIVDEPS = \
		#$ ExpandList("UNIVDEPS");

