#
# File:		makefile.dos
# Author:	Michael Bedward
# Created:	1999
# Updated:	
#
# Makefile : Builds 16-bit sample, VC++ 1.5
# Use FINAL=1 argument to nmake to build final version with no debugging
# info

WXDIR = $(WXWIN)

TARGET=griddemo
OBJECTS=$(TARGET).obj

!include $(WXDIR)\src\makeprog.msc

