#
# File:		makefile.vc
# Author:	Michael Bedward
# Created:	1999
# Updated:	
#
# Makefile : Builds sample (VC++, WIN32)
# Use FINAL=1 argument to nmake to build final version with no debug info.

# Set WXDIR for your system
WXDIR = $(WXWIN)

PROGRAM=griddemo
OBJECTS = $(PROGRAM).obj

!include $(WXDIR)\src\makeprog.vc

