#
# File:		makefile.bcc
# Author:	Michael Bedward
# Created:	1999
# Updated:	
#
# Builds a BC++ 16-bit sample

!if "$(WXWIN)" == ""
!error You must define the WXWIN variable in autoexec.bat, e.g. WXWIN=c:\wx
!endif

WXDIR = $(WXWIN)

TARGET=griddemo
OBJECTS=$(TARGET).obj

!include $(WXDIR)\src\makeprog.bcc

