#
# File:		makefile.unx
# Author:	Julian Smart
# Created:	1998
# Updated:	
# Copyright:	(c) 1998 Julia`n Smart
#
# "%W% %G%"
#
# Makefile for wxGLCanvas (Unix)

LIBTARGET=$(WXWIN)/lib/libglcanvas
OPENGLHOME=/home/jacs/mesa/Mesa-2.3

EXTRACPPFLAGS=-I$(OPENGLHOME)/include

OBJECTS=glcanvas.o

include ../../../src/makelib.env

