#
# File:		makefile.bcc
# Author:	Julian Smart
# Created:	1998
# Updated:	
#
# Builds a BC++ 16-bit Dialog Editor

!if "$(WXWIN)" == ""
!error You must define the WXWIN variable in autoexec.bat, e.g. WXWIN=c:\wx
!endif

WXDIR = $(WXWIN)

TARGET=dialoged
OBJECTS=dialoged.obj reseditr.obj dlghndlr.obj reswrite.obj\
  winprop.obj edtree.obj edlist.obj symbtabl.obj winstyle.obj

!include $(WXDIR)\src\makeprog.bcc

