#
# File:         makefile.g95
# Author:       Julian Smart
# Created:      1999
# Updated:
# Copyright:    (c) Julian Smart, 1999
#
# Makefile for wxWindows Dialog Editor (Cygwin/Mingw32).

WXDIR = ../../..

TARGET=dialoged
OBJECTS = $(TARGET).o reseditr.o dlghndlr.o reswrite.o\
  winprop.o edtree.o edlist.o symbtabl.o winstyle.o

include $(WXDIR)/src/makeprog.g95

