#
# File:		makefile.unx
# Author:	Julian Smart
# Created:	1998
# Updated:	
# Copyright:	(c) 1998 Julian Smart
#
# "%W% %G%"
#
# Makefile for Dialog Editor (Unix)

PROGRAM=dialoged

OBJECTS = dialoged.o reseditr.o dlghndlr.o reswrite.o\
  winprop.o edtree.o edlist.o symbtabl.o winstyle.o

include ../../../src/makeprog.env

