# Generated automatically from Makefile.in by configure.
#
# File:		makefile.unx
# Author:	Julian Smart
# Created:	1998
# Updated:	
# Copyright:	(c) 1998 Julian Smart
#
# "%W% %G%"
#
# Makefile for Tex2RTF (Unix)

top_srcdir = ../../..
top_builddir = ../../..
program_dir = utils/dialoged/src

PROGRAM=DialogEd

OBJECTS = dialoged.o dlghndlr.o edlist.o edtree.o reseditr.o reswrite.o symbtabl.o winprop.o winstyle.o

include ../../../src/makeprog.env

