#
# File:		makefile.b32
# Author:	Patrick Halke
# Created:	1995
# Updated:	
# Copyright:	(c) 1993, AIAI, University of Edinburgh
#
# "%W% %G%"
#
# Makefile : Builds Dialog Editor (32-bit Borland)

# WXWIN and BCCDIR are set by parent make

WXDIR = $(WXWIN)

TARGET=dialoged
OBJECTS = dialoged.obj reseditr.obj dlghndlr.obj reswrite.obj winprop.obj\
 edtree.obj edlist.obj symbtabl.obj winstyle.obj

!include $(WXDIR)\src\makeprog.b32

