#
# Makefile for Windows and MS VIsual C++
#

WXDIR = $(WXWIN)
PYTHONDIR = d:\tools\Python22

PROGRAM = embedded
OBJECTS = $(PROGRAM).obj
EXTRAINC  = /I$(PYTHONDIR)\include /I$(WXDIR)/wxPython/src
EXTRALIBS = /LIBPATH:$(PYTHONDIR)\libs

!include $(WXDIR)\src\makeprog.vc
