#
# File:		makefile.b32
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:
#
# Makefile : Builds sample for 32-bit BC++

WXDIR = $(WXWIN)

TARGET=mmboard
EXTRALIBS=$(WXDIR)\contrib\lib\mmedia.lib
OBJECTS = $(TARGET).obj mmbman.obj

!include $(WXDIR)\src\makeprog.b32

