#
# File:		makefile.vc
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:	(c) Julian Smart
#
# Makefile : Builds sample (VC++, WIN32)
# Use FINAL=1 argument to nmake to build final version with no debug info.

# Set WXDIR for your system
WXDIR = $(WXWIN)

PROGRAM=mmboard

!if "$(FINAL)" == "0"
EXTRALIBS=$(WXDIR)\contrib\lib\mmediad.lib
!else
EXTRALIBS=$(WXDIR)\contrib\lib\mmedia.lib
!endif

OBJECTS = $(PROGRAM).obj mmbman.obj

!include $(WXDIR)\src\makeprog.vc

