#
# File:		makefile.b32
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:
#
# Makefile : Builds wxGLCanvas library for 32-bit BC++

WXDIR = $(WXWIN)

LIBTARGET=$(WXDIR)\lib\glcanvas.lib

OBJECTS = glcanvas.obj

!include $(WXDIR)\src\makelib.b32

