#
# File:         makefile.g95
# Author:       Julian Smart
# Created:      1999
# Updated:
# Copyright:    (c) Julian Smart, 1999
#
# Makefile for wxWindows wxGLCanvas library Cygwin/Mingw32).

WXDIR = ../../..

LIBTARGET=$(WXDIR)/lib/libglcanvas.a
OBJECTS = glcanvas.o

include $(WXDIR)/src/makelib.g95

