all:
        cd html
        nmake -f makefile.vc
        cd ..\lseditor
        nmake -f makefile.vc
        cd ..\glcanvas
        nmake -f makefile.vc
        cd ..


clean:
        cd html
        nmake -f makefile.vc clean
        cd ..\lseditor
        nmake -f makefile.vc clean
        cd ..\glcanvas
        nmake -f makefile.vc clean
        cd ..
