#
# File:		makefile.vc
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:	(c) Julian Smart
#
# Makefile : Builds sample (VC++, WIN32)
# Use FINAL=1 argument to nmake to build final version with no debug info.

!include $(WXWIN)/src/makevc.env

all:
    nmake -f server.vc FINAL=$(FINAL)
    nmake -f client.vc FINAL=$(FINAL)

clean:
    nmake -f server.vc clean
    nmake -f client.vc clean

