#
# File:		makefile.vc
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:	(c) Julian Smart
#
# Makefile : Builds sample for 32-bit BC++

all:
    make -f server.b32 all
    make -f client.b32 all

clean:
    make -f server.b32 clean
    make -f client.b32 clean

