#
# File:		makefile.vc
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:	(c) Julian Smart
#
# Makefile : Builds sample for 32-bit BC++

!if "$(WXUSINGDLL)" == ""
WXUSINGDLL=0
!endif

!if "$(FINAL)" == ""
FINAL=0
!endif

all:
    make -f server.b32 FINAL=$(FINAL) WXUSINGDLL=$(WXUSINGDLL)
    make -f client.b32 FINAL=$(FINAL) WXUSINGDLL=$(WXUSINGDLL)

clean:
    make -f server.b32 clean
    make -f client.b32 clean

