# Purpose: makefile for sockets example (Unix)
# Created: 2000-03-14
# hand hacked from template file by Ron <ron@debian.org>

CXX = $(shell wx-config --cxx)

PROGRAMS = client server

# implementation

.SUFFIXES:	.o .cpp

.cpp.o :
	$(CXX) -c `wx-config --cxxflags` -o $@ $<

all: $(PROGRAMS)

client: client.o
	$(CXX) -o $@ $< `wx-config --libs`

server: server.o
	$(CXX) -o $@ $< `wx-config --libs`

clean:
	rm -f *.o $(PROGRAMS)
