#!/bin/sh
##############################################################################
# Name:       misc/scripts/inc_year
# Purpose:    increments the year in various copyright notices
# Created:    2019-04-21
# Copyright:  (c) 2019 Vadim Zeitlin <vadim@wxwidgets.org>
# Licence:    wxWindows licence
##############################################################################

. `dirname $0`/run_sed_common.sh

new_year=`date +%Y`
old_year=`expr $new_year - 1`

echo "Updating dates to use $new_year instead of $old_year:"

# Update copyright to extend to the new year.
for f in docs/doxygen/mainpages/copyright.h docs/doxygen/regen.sh \
         interface/wx/aboutdlg.h interface/wx/generic/aboutdlgg.h \
         src/common/utilscmn.cpp src/msw/version.rc \
         ; do
    run_sed $f "s/1992-$old_year/1992-$new_year/"
done

# And Mac files are much newer than that.
run_sed CMakeLists.txt "s/2002-$old_year/2002-$new_year/"
run_sed build/bakefiles/mac_bundles.bkl "s/2002-$old_year/2002-$new_year/"
run_sed samples/minimal/Info_cocoa.plist "s/2005-$old_year/2005-$new_year/"
