#!/bin/sh
##############################################################################
# Name:       misc/scripts/inc_year
# Purpose:    increments the year in various copyright notices
# Created:    2019-04-21
# Copyright:  (c) 2019 Vadim Zeitlin <vadim@wxwidgets.org>
# Licence:    wxWindows licence
##############################################################################

. `dirname $0`/run_sed_common.sh

new_year=`date +%Y`
old_year=`expr $new_year - 1`

echo "Updating dates to use $new_year instead of $old_year:"

# Update copyright to extend to the new year.
for f in CMakeLists.txt \
         docs/doxygen/mainpages/copyright.h docs/doxygen/regen.sh \
         interface/wx/aboutdlg.h interface/wx/generic/aboutdlgg.h \
         ; do
    run_sed $f "s/1992-$old_year/1992-$new_year/"
done

# Some files use later initial copyright year, for some reason...
run_sed src/msw/version.rc "s/1993-$old_year/1993-$new_year/"
run_sed src/common/utilscmn.cpp "s/1995-$old_year/1995-$new_year/"

# And Mac files are much newer than that.
for f in samples/docview/Info.plist samples/minimal/Info_cocoa.plist; do
    run_sed $f "s/2005-$old_year/2005-$new_year/"
done
