#!/bin/sh
ctags --totals --language-force=c++ -I WXDLLEXPORT \
	include/wx/*.h \
	include/wx/aui/*.h \
	include/wx/generic/*.h \
	include/wx/gtk/*.h \
	include/wx/html/*.h \
	include/wx/protocol/*.h \
	include/wx/richtext/*.h \
	include/wx/xml/*.h \
	include/wx/xrc/*.h \
	include/wx/unix/*.h \
	src/aui/*.cpp \
	src/common/*.cpp \
	src/generic/*.cpp \
	src/gtk/*.cpp \
	src/html/*.cpp \
	src/richtext/*.cpp \
	src/unix/*.cpp \
	src/xml/*.cpp \
	src/xrc/*.cpp

