#!/bin/sh
ctags --c-types=+x --totals --language-force=c++ -I WXDLLEXPORT \
	include/wx/*.h \
	include/wx/gtk/*.h \
	include/wx/generic/*.h \
	include/wx/protocol/*.h \
	include/wx/unix/*.h \
	src/common/*.cpp \
	src/generic/*.cpp \
	src/gtk/*.cpp \
	src/html/*.cpp \
	src/unix/*.cpp

