# Purpose: makefile for validate example (TWIN)
# Created: 2000-03-14

WXDIR = ../..

# All common UNIX compiler flags and options are now in
# this central makefile.
include $(WXDIR)/src/maketwin.env

OBJECTS = $(OBJDIR)/validate.$(OBJSUFF) $(OBJDIR)/validate.$(OBJSUFF)

all:    $(OBJDIR) validate$(GUISUFFIX)$(EXESUFF)

wx:

$(OBJDIR):
	mkdir $(OBJDIR)

validate$(GUISUFFIX)$(EXESUFF):	$(OBJECTS) $(WXLIB)
	$(CC) $(LDFLAGS) -o validate$(GUISUFFIX)$(EXESUFF) $(OBJECTS) $(LDLIBS)

$(OBJDIR)/validate.$(OBJSUFF):	validate.$(SRCSUFF)
	$(CC) -c $(CPPFLAGS) -o $@ validate.$(SRCSUFF)

validate.c:  validate.rc
	$(RESCOMP) $(RCINPUTSWITCH) validate.rc $(RCOUTPUTSWITCH) validate.c $(RESFLAGS)

$(OBJDIR)/validate.$(OBJSUFF):	validate.c
	$(CC) -c $(CPPFLAGS) -o $@ validate.c

#$(OBJDIR)/validate.o:  validate.rc
#	$(RESCOMP) $(RCINPUTSWITCH) validate.rc $(RCOUTPUTSWITCH) $(OBJDIR)/validate.o $(RESFLAGS)

clean:
	rm -f $(OBJECTS) validate$(GUISUFFIX).exe core *.rsc *.res
