# Purpose: makefile for validate example (VC++ 32bit)
# Created: 2000-03-14

# Set WXDIR for your system
WXDIR = $(WXWIN)

PROGRAM=validate
OBJECTS = $(PROGRAM).obj

!include $(WXDIR)\src\makeprog.vc

