%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Name:        htprint.inc
%% Purpose:     Macros which can be used with wxHtmlPrintout: this file is
%%              included from several locations where we list these macros
%% Author:      Vadim Zeitlin
%% Created:     2006-07-29
%% RCS-ID:      $Id$
%% Copyright:   (c) 2006 Vadim Zeitlin
%% License:     wxWindows license
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{itemize}\itemsep=0pt
\item @DATE@ is replaced by the current date in default format
\item @PAGENUM@ is replaced by page number
\item @PAGESCNT@ is replaced by total number of pages
\item @TIME@ is replaced by the current time in default format
\item @TITLE@ is replaced with the title of the document
\end{itemize}

