.TH wx\-config 1 "15 Feb 2000" "Debian GNU/Linux" "wxWidgets"
.SH NAME
wx-config \- generate compile time requirements for wxWidgets applications
.SH SYNOPSIS
.nh
.B wxbase\-config
.br
.B wxgtk\-config
.HP
.B wx\-config
[\-\-version]
[\-\-libs\fI[=LIBS]\fP] [\-\-gl\-libs]
[\-\-cppflags] [\-\-cflags] [\-\-cxxflags]
[\-\-cc] [\-\-cxx] [\-\-ld]
[\-\-prefix\fI[=DIR]\fP] [\-\-exec\-prefix\fI[=DIR]\fP]
[\-\-release] [\-\-basename]
.SH DESCRIPTION
\fIwx\-config\fP is a tool to determine the compiler and linker
flags required for applications using the \fIwxWidgets\fP toolkit(s).
.PP
\fIwx\-config\fP is normally a symlink to one of the port\-specific
versions like \fIwxbase\-config\fP or \fIwxgtk\-config\fP which
designates the default port to compile applications with.
You can override this default either by using one of the specific
versions directly, or by changing which version the symlink points to.
On Debian systems this can be done using the
.BR update\-alternatives (8)
mechanism.
.hy
.SH OPTIONS
.l
\fIwx\-config\fP accepts the following options:
.TP 15
.B  \-\-version
What to
.B ALWAYS
include in a bug report.
.TP 15
.B  \-\-libs[=LIBS]
Generate linker flags for a \fIwxWidgets\fP application.
The optional argument is a comma separated list of the wxWidgets libraries
to link with.  You may include contrib libs here too.  If no argument is
given it will assume you wish to link all 'core' libraries.
.TP 15
.B  \-\-gl-libs
Output linker parameters for a \fIwxWindows\fP application that uses the glcanvas.
.TP 15
.B  \-\-cppflags
Output parameters required by the C preprocessor for wxWindows applications.
.TP 15
.B  \-\-cflags
Output parameters required by the C compiler for wxWindows applications.
.TP 15
.B  \-\-cxxflags
Output parameters required by the C++ compiler for wxWindows applications.
.TP 15
.B  \-\-cc
Output the name of the C compiler \fB$(CC)\fP.
.TP 15
.B  \-\-cxx
Output the name of the C++ compiler \fB$(CXX)\fP.
.TP 15
.B  \-\-ld
Output the linker command \fB$(LD)\fP.
.TP 15
.B  \-\-prefix=PREFIX
If specified, use PREFIX instead of the installation prefix that \fIwxWidgets\fP
was built with when computing the output for the \-\-cflags and
\-\-libs options. This option is also used for the exec prefix
if \-\-exec\-prefix was not specified. This option must be specified
before any \-\-libs or \-\-cflags options.
.br
.nh
.HP
(Translation:  this is the root path to the \fIwxWidgets\fP headers \-\- [Ron])
.hy
.TP 15
.B  \-\-exec\-prefix=PREFIX
If specified, use PREFIX instead of the installation exec prefix that
\fIwxWidgets\fP was built with when computing the output for the \-\-cflags
and \-\-libs options.  This option must be specified before any
\-\-libs or \-\-cflags options.
.br
.nh
.HP
(Translation:  this is the root path to the \fIwxWidgets\fP library \-\- [Ron])
.hy
.TP 15
.B  \-\-release
Output the wxWidgets release number.
.TP 15
.B  \-\-basename
Output the base name of the wxWidgets libraries.
.SH SEE ALSO
.BR gtk\-config (1),
.BR update\-alternatives (8)
.SH COPYRIGHT
This manpage was copied whole\-heartedly from the \fBgtk\-config\fP(1) manpage
by Brian Bassett <brianb@debian.org> for the Debian GNU/Linux distribution of
wxGTK.  It was subsequently updated to include new options and otherwise
bastardised generally by Ron Lee <ron@debian.org>

The original gtk\-config manpage copyright:

Copyright \(co  1995 Spencer Kimball and Peter Mattis

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted,
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in
supporting documentation.
