.TH wx\-xy\-config 1 "15 Feb 2000" "Debian GNU/Linux" "wxWindows"
.SH NAME
wx-XY-config \- generate compile time requirements for specific wxWindows versions
.SH DESCRIPTION
You should not call the versioned \fIwx\-XY\-config\fP scripts directly,
instead call \fIwx\-config\fP with the options you require.
These files are deprecated and have (already) been removed from
later releases.
.SH SEE ALSO
.BR wx\-config (1),
.SH COPYRIGHT
This manpage was created by Ron Lee <ron@debian.org> for the Debian
distribution.  It may be used freely by anyone who cares to find it
useful.
