.TH wxrc\-tools 1 "30 Jul 2004" "Debian GNU/Linux" "wxWidgets"
.SH NAME
wxrc \- command line compiler for wx xml resources.

.SH DESCRIPTION
The real documentation for this tool (what of it that exists) is available
in the wxWidgets manual, which is packaged in html format in the wx2.8-doc
package and installed in
/usr/share/doc/wx2.8-doc/wx-manual.html/wx_xrcoverview.html on Debian systems.

.SH COPYRIGHT
This manpage was written by Ron Lee <ron@debian.org> for the Debian GNU/Linux
distribution of wxWidgets.  It may be freely distributed by anyone insane
enough to find it useful.
