.TH wxrc\-tools 1 "30 Jul 2004" "Debian GNU/Linux" "wxWindows"
.SH NAME
wxrc \- command line compiler for wx xml resources.
.br
wxrced \- graphical editing tool for wx xml resource files.

.SH DESCRIPTION
The real documentation for these tools (what of it that exists) is available
in the wxWindows manual, which is packaged in html format in the wxwin2.4-doc
package and installed in /usr/share/doc/wxwin2.4-doc/wxWindows-manual.html on
Debian systems.

.SH COPYRIGHT
This manpage was written by Ron Lee <ron@debian.org> for the Debian GNU/Linux
distribution of wxWindows.  It may be freely distributed by anyone insane enough
to find it useful.

