## This file reverse renames symbols in the wx package to give
## them their wx prefix again, for backwards compatibility.
##
## Generated by BuildRenamers in config.py

# This silly stuff here is so the wxPython.wx module doesn't conflict
# with the wx package.  We need to import modules from the wx package
# here, then we'll put the wxPython.wx entry back in sys.modules.
import sys
_wx = None
if sys.modules.has_key('wxPython.wx'):
    _wx = sys.modules['wxPython.wx']
    del sys.modules['wxPython.wx']

import wx.grid

sys.modules['wxPython.wx'] = _wx
del sys, _wx


# Now assign all the reverse-renamed names:
wxGRID_VALUE_STRING = wx.grid.GRID_VALUE_STRING
wxGRID_VALUE_BOOL = wx.grid.GRID_VALUE_BOOL
wxGRID_VALUE_NUMBER = wx.grid.GRID_VALUE_NUMBER
wxGRID_VALUE_FLOAT = wx.grid.GRID_VALUE_FLOAT
wxGRID_VALUE_CHOICE = wx.grid.GRID_VALUE_CHOICE
wxGRID_VALUE_TEXT = wx.grid.GRID_VALUE_TEXT
wxGRID_VALUE_LONG = wx.grid.GRID_VALUE_LONG
wxGRID_VALUE_CHOICEINT = wx.grid.GRID_VALUE_CHOICEINT
wxGRID_VALUE_DATETIME = wx.grid.GRID_VALUE_DATETIME
wxGridNoCellCoords = wx.grid.GridNoCellCoords
wxGridNoCellRect = wx.grid.GridNoCellRect
wxGRID_DEFAULT_NUMBER_ROWS = wx.grid.GRID_DEFAULT_NUMBER_ROWS
wxGRID_DEFAULT_NUMBER_COLS = wx.grid.GRID_DEFAULT_NUMBER_COLS
wxGRID_DEFAULT_ROW_HEIGHT = wx.grid.GRID_DEFAULT_ROW_HEIGHT
wxGRID_DEFAULT_COL_WIDTH = wx.grid.GRID_DEFAULT_COL_WIDTH
wxGRID_DEFAULT_COL_LABEL_HEIGHT = wx.grid.GRID_DEFAULT_COL_LABEL_HEIGHT
wxGRID_DEFAULT_ROW_LABEL_WIDTH = wx.grid.GRID_DEFAULT_ROW_LABEL_WIDTH
wxGRID_LABEL_EDGE_ZONE = wx.grid.GRID_LABEL_EDGE_ZONE
wxGRID_MIN_ROW_HEIGHT = wx.grid.GRID_MIN_ROW_HEIGHT
wxGRID_MIN_COL_WIDTH = wx.grid.GRID_MIN_COL_WIDTH
wxGRID_DEFAULT_SCROLLBAR_WIDTH = wx.grid.GRID_DEFAULT_SCROLLBAR_WIDTH
wxGridCellWorker = wx.grid.GridCellWorker
wxGridCellRenderer = wx.grid.GridCellRenderer
wxPyGridCellRenderer = wx.grid.PyGridCellRenderer
wxGridCellStringRenderer = wx.grid.GridCellStringRenderer
wxGridCellNumberRenderer = wx.grid.GridCellNumberRenderer
wxGridCellFloatRenderer = wx.grid.GridCellFloatRenderer
wxGridCellBoolRenderer = wx.grid.GridCellBoolRenderer
wxGridCellDateTimeRenderer = wx.grid.GridCellDateTimeRenderer
wxGridCellEnumRenderer = wx.grid.GridCellEnumRenderer
wxGridCellAutoWrapStringRenderer = wx.grid.GridCellAutoWrapStringRenderer
wxGridCellEditor = wx.grid.GridCellEditor
wxPyGridCellEditor = wx.grid.PyGridCellEditor
wxGridCellTextEditor = wx.grid.GridCellTextEditor
wxGridCellNumberEditor = wx.grid.GridCellNumberEditor
wxGridCellFloatEditor = wx.grid.GridCellFloatEditor
wxGridCellBoolEditor = wx.grid.GridCellBoolEditor
wxGridCellChoiceEditor = wx.grid.GridCellChoiceEditor
wxGridCellEnumEditor = wx.grid.GridCellEnumEditor
wxGridCellAutoWrapStringEditor = wx.grid.GridCellAutoWrapStringEditor
wxGridCellAttr = wx.grid.GridCellAttr
wxGridCellAttrProvider = wx.grid.GridCellAttrProvider
wxPyGridCellAttrProvider = wx.grid.PyGridCellAttrProvider
wxGridTableBase = wx.grid.GridTableBase
wxPyGridTableBase = wx.grid.PyGridTableBase
wxGridStringTable = wx.grid.GridStringTable
wxGRIDTABLE_REQUEST_VIEW_GET_VALUES = wx.grid.GRIDTABLE_REQUEST_VIEW_GET_VALUES
wxGRIDTABLE_REQUEST_VIEW_SEND_VALUES = wx.grid.GRIDTABLE_REQUEST_VIEW_SEND_VALUES
wxGRIDTABLE_NOTIFY_ROWS_INSERTED = wx.grid.GRIDTABLE_NOTIFY_ROWS_INSERTED
wxGRIDTABLE_NOTIFY_ROWS_APPENDED = wx.grid.GRIDTABLE_NOTIFY_ROWS_APPENDED
wxGRIDTABLE_NOTIFY_ROWS_DELETED = wx.grid.GRIDTABLE_NOTIFY_ROWS_DELETED
wxGRIDTABLE_NOTIFY_COLS_INSERTED = wx.grid.GRIDTABLE_NOTIFY_COLS_INSERTED
wxGRIDTABLE_NOTIFY_COLS_APPENDED = wx.grid.GRIDTABLE_NOTIFY_COLS_APPENDED
wxGRIDTABLE_NOTIFY_COLS_DELETED = wx.grid.GRIDTABLE_NOTIFY_COLS_DELETED
wxGridTableMessage = wx.grid.GridTableMessage
wxGridCellCoords = wx.grid.GridCellCoords
wxGrid = wx.grid.Grid
wxPreGrid = wx.grid.PreGrid
wxGrid_GetClassDefaultAttributes = wx.grid.Grid_GetClassDefaultAttributes
wxGridEvent = wx.grid.GridEvent
wxGridSizeEvent = wx.grid.GridSizeEvent
wxGridRangeSelectEvent = wx.grid.GridRangeSelectEvent
wxGridEditorCreatedEvent = wx.grid.GridEditorCreatedEvent
wxEVT_GRID_CELL_LEFT_CLICK = wx.grid.wxEVT_GRID_CELL_LEFT_CLICK
wxEVT_GRID_CELL_RIGHT_CLICK = wx.grid.wxEVT_GRID_CELL_RIGHT_CLICK
wxEVT_GRID_CELL_LEFT_DCLICK = wx.grid.wxEVT_GRID_CELL_LEFT_DCLICK
wxEVT_GRID_CELL_RIGHT_DCLICK = wx.grid.wxEVT_GRID_CELL_RIGHT_DCLICK
wxEVT_GRID_LABEL_LEFT_CLICK = wx.grid.wxEVT_GRID_LABEL_LEFT_CLICK
wxEVT_GRID_LABEL_RIGHT_CLICK = wx.grid.wxEVT_GRID_LABEL_RIGHT_CLICK
wxEVT_GRID_LABEL_LEFT_DCLICK = wx.grid.wxEVT_GRID_LABEL_LEFT_DCLICK
wxEVT_GRID_LABEL_RIGHT_DCLICK = wx.grid.wxEVT_GRID_LABEL_RIGHT_DCLICK
wxEVT_GRID_ROW_SIZE = wx.grid.wxEVT_GRID_ROW_SIZE
wxEVT_GRID_COL_SIZE = wx.grid.wxEVT_GRID_COL_SIZE
wxEVT_GRID_RANGE_SELECT = wx.grid.wxEVT_GRID_RANGE_SELECT
wxEVT_GRID_CELL_CHANGE = wx.grid.wxEVT_GRID_CELL_CHANGE
wxEVT_GRID_SELECT_CELL = wx.grid.wxEVT_GRID_SELECT_CELL
wxEVT_GRID_EDITOR_SHOWN = wx.grid.wxEVT_GRID_EDITOR_SHOWN
wxEVT_GRID_EDITOR_HIDDEN = wx.grid.wxEVT_GRID_EDITOR_HIDDEN
wxEVT_GRID_EDITOR_CREATED = wx.grid.wxEVT_GRID_EDITOR_CREATED
wxEVT_GRID_CELL_BEGIN_DRAG = wx.grid.wxEVT_GRID_CELL_BEGIN_DRAG


d = globals()
for k, v in wx.grid.__dict__.iteritems():
    if k.startswith('EVT'):
        d[k] = v
del d, k, v



