PATH="/c/Program Files/Bakefile/src":$PATH
cd $WXWIN
mkdir -p build/wince
echo "<?xml version=\"1.0\"?><bakefile-gen><enable-formats>msevc4prj</enable-formats></bakefile-gen>" > build/bakefiles/Bakefiles.local.bkgen
cd build/bakefiles
echo $PATH
bakefile_gen -b wx.bkl -f msevc4prj

bakefile_gen -b ../../demos/bombs/bombs.bkl -f msevc4prj
bakefile_gen -b ../../demos/dbbrowse/dbbrowse.bkl -f msevc4prj
bakefile_gen -b ../../demos/forty/forty.bkl -f msevc4prj
bakefile_gen -b ../../demos/fractal/fractal.bkl -f msevc4prj
bakefile_gen -b ../../demos/life/life.bkl -f msevc4prj
bakefile_gen -b ../../demos/poem/poem.bkl -f msevc4prj

bakefile_gen -b ../../samples/access/access.bkl -f msevc4prj
bakefile_gen -b ../../samples/artprov/artprov.bkl -f msevc4prj
bakefile_gen -b ../../samples/calendar/calendar.bkl -f msevc4prj
bakefile_gen -b ../../samples/caret/caret.bkl -f msevc4prj
bakefile_gen -b ../../samples/checklst/checklst.bkl -f msevc4prj
bakefile_gen -b ../../samples/config/config.bkl -f msevc4prj
bakefile_gen -b ../../samples/console/console.bkl -f msevc4prj
bakefile_gen -b ../../samples/controls/controls.bkl -f msevc4prj
bakefile_gen -b ../../samples/db/db.bkl -f msevc4prj
bakefile_gen -b ../../samples/dialogs/dialogs.bkl -f msevc4prj
bakefile_gen -b ../../samples/dialup/dialup.bkl -f msevc4prj
bakefile_gen -b ../../samples/display/display.bkl -f msevc4prj
bakefile_gen -b ../../samples/dnd/dnd.bkl -f msevc4prj
bakefile_gen -b ../../samples/docview/docview.bkl -f msevc4prj
bakefile_gen -b ../../samples/docvwmdi/docvwmdi.bkl -f msevc4prj
bakefile_gen -b ../../samples/dragimag/dragimag.bkl -f msevc4prj
bakefile_gen -b ../../samples/drawing/drawing.bkl -f msevc4prj
bakefile_gen -b ../../samples/dynamic/dynamic.bkl -f msevc4prj
bakefile_gen -b ../../samples/erase/erase.bkl -f msevc4prj
bakefile_gen -b ../../samples/event/event.bkl -f msevc4prj
bakefile_gen -b ../../samples/except/except.bkl -f msevc4prj
bakefile_gen -b ../../samples/exec/exec.bkl -f msevc4prj
bakefile_gen -b ../../samples/font/font.bkl -f msevc4prj
bakefile_gen -b ../../samples/grid/grid.bkl -f msevc4prj
bakefile_gen -b ../../samples/help/help.bkl -f msevc4prj
bakefile_gen -b ../../samples/htlbox/htlbox.bkl -f msevc4prj
bakefile_gen -b ../../samples/html/about/about.bkl -f msevc4prj
bakefile_gen -b ../../samples/html/help/help.bkl -f msevc4prj
bakefile_gen -b ../../samples/html/helpview/helpview.bkl -f msevc4prj
bakefile_gen -b ../../samples/html/html_samples.bkl -f msevc4prj
bakefile_gen -b ../../samples/html/htmlctrl/htmlctrl.bkl -f msevc4prj
bakefile_gen -b ../../samples/html/printing/printing.bkl -f msevc4prj
bakefile_gen -b ../../samples/html/test/test.bkl -f msevc4prj
bakefile_gen -b ../../samples/html/virtual/virtual.bkl -f msevc4prj
bakefile_gen -b ../../samples/html/widget/widget.bkl -f msevc4prj
bakefile_gen -b ../../samples/html/zip/zip.bkl -f msevc4prj
bakefile_gen -b ../../samples/image/image.bkl -f msevc4prj
bakefile_gen -b ../../samples/internat/internat.bkl -f msevc4prj
bakefile_gen -b ../../samples/ipc/ipc.bkl -f msevc4prj
bakefile_gen -b ../../samples/joytest/joytest.bkl -f msevc4prj
bakefile_gen -b ../../samples/keyboard/keyboard.bkl -f msevc4prj
bakefile_gen -b ../../samples/layout/layout.bkl -f msevc4prj
bakefile_gen -b ../../samples/listbox/listbox.bkl -f msevc4prj
bakefile_gen -b ../../samples/listctrl/listctrl.bkl -f msevc4prj
bakefile_gen -b ../../samples/mdi/mdi.bkl -f msevc4prj
bakefile_gen -b ../../samples/memcheck/memcheck.bkl -f msevc4prj
bakefile_gen -b ../../samples/menu/menu.bkl -f msevc4prj
bakefile_gen -b ../../samples/mfc/mfc.bkl -f msevc4prj
bakefile_gen -b ../../samples/minifram/minifram.bkl -f msevc4prj
bakefile_gen -b ../../samples/minimal/minimal.bkl -f msevc4prj
bakefile_gen -b ../../samples/mobile/mobile_samples.bkl -f msevc4prj
bakefile_gen -b ../../samples/mobile/styles/styles.bkl -f msevc4prj
bakefile_gen -b ../../samples/mobile/wxedit/wxedit.bkl -f msevc4prj
bakefile_gen -b ../../samples/multimon/multimon.bkl -f msevc4prj
bakefile_gen -b ../../samples/nativdlg/nativdlg.bkl -f msevc4prj
bakefile_gen -b ../../samples/notebook/notebook.bkl -f msevc4prj
bakefile_gen -b ../../samples/oleauto/oleauto.bkl -f msevc4prj
bakefile_gen -b ../../samples/opengl/cube/cube.bkl -f msevc4prj
bakefile_gen -b ../../samples/opengl/isosurf/isosurf.bkl -f msevc4prj
bakefile_gen -b ../../samples/opengl/opengl_samples.bkl -f msevc4prj
bakefile_gen -b ../../samples/opengl/penguin/penguin.bkl -f msevc4prj
bakefile_gen -b ../../samples/ownerdrw/ownerdrw.bkl -f msevc4prj
bakefile_gen -b ../../samples/png/png.bkl -f msevc4prj
bakefile_gen -b ../../samples/printing/printing.bkl -f msevc4prj
bakefile_gen -b ../../samples/propsize/propsize.bkl -f msevc4prj
bakefile_gen -b ../../samples/regtest/regtest.bkl -f msevc4prj
bakefile_gen -b ../../samples/render/render.bkl -f msevc4prj
bakefile_gen -b ../../samples/richedit/richedit.bkl -f msevc4prj
bakefile_gen -b ../../samples/rotate/rotate.bkl -f msevc4prj
bakefile_gen -b ../../samples/rttitest/minimal.bkl -f msevc4prj
bakefile_gen -b ../../samples/sashtest/sashtest.bkl -f msevc4prj
bakefile_gen -b ../../samples/scroll/scroll.bkl -f msevc4prj
bakefile_gen -b ../../samples/scrollsub/scrollsub.bkl -f msevc4prj
bakefile_gen -b ../../samples/shaped/shaped.bkl -f msevc4prj
bakefile_gen -b ../../samples/sockets/sockets.bkl -f msevc4prj
bakefile_gen -b ../../samples/sound/sound.bkl -f msevc4prj
bakefile_gen -b ../../samples/splitter/splitter.bkl -f msevc4prj
bakefile_gen -b ../../samples/statbar/statbar.bkl -f msevc4prj
bakefile_gen -b ../../samples/tab/tab.bkl -f msevc4prj
bakefile_gen -b ../../samples/taskbar/taskbar.bkl -f msevc4prj
bakefile_gen -b ../../samples/text/text.bkl -f msevc4prj
bakefile_gen -b ../../samples/thread/thread.bkl -f msevc4prj
bakefile_gen -b ../../samples/toolbar/toolbar.bkl -f msevc4prj
bakefile_gen -b ../../samples/treectrl/treectrl.bkl -f msevc4prj
bakefile_gen -b ../../samples/typetest/typetest.bkl -f msevc4prj
bakefile_gen -b ../../samples/validate/validate.bkl -f msevc4prj
bakefile_gen -b ../../samples/vscroll/vscroll.bkl -f msevc4prj
bakefile_gen -b ../../samples/widgets/widgets.bkl -f msevc4prj
bakefile_gen -b ../../samples/wizard/wizard.bkl -f msevc4prj

bakefile_gen -b ../../contrib/build/animate/animate.bkl -f msevc4prj
bakefile_gen -b ../../contrib/build/deprecated/deprecated.bkl -f msevc4prj
bakefile_gen -b ../../contrib/build/fl/fl.bkl -f msevc4prj
bakefile_gen -b ../../contrib/build/gizmos/gizmos.bkl -f msevc4prj
bakefile_gen -b ../../contrib/build/mmedia/mmedia.bkl -f msevc4prj
bakefile_gen -b ../../contrib/build/net/net.bkl -f msevc4prj
bakefile_gen -b ../../contrib/build/ogl/ogl.bkl -f msevc4prj
bakefile_gen -b ../../contrib/build/plot/plot.bkl -f msevc4prj
bakefile_gen -b ../../contrib/build/stc/stc.bkl -f msevc4prj
bakefile_gen -b ../../contrib/build/svg/svg.bkl -f msevc4prj
bakefile_gen -b ../../contrib/build/xrc/xrc.bkl -f msevc4prj
bakefile_gen -b ../../contrib/samples/animate/anitest.bkl -f msevc4prj
bakefile_gen -b ../../contrib/samples/deprecated/proplist/proplist.bkl -f msevc4prj
bakefile_gen -b ../../contrib/samples/deprecated/resource/resource.bkl -f msevc4prj
bakefile_gen -b ../../contrib/samples/deprecated/treelay/treelay.bkl -f msevc4prj
bakefile_gen -b ../../contrib/samples/fl/fl.bkl -f msevc4prj
bakefile_gen -b ../../contrib/samples/gizmos/dynsash/dynsash.bkl -f msevc4prj
bakefile_gen -b ../../contrib/samples/gizmos/dynsash_switch/dynsash_switch.bkl -f msevc4prj
bakefile_gen -b ../../contrib/samples/gizmos/editlbox/editlbox.bkl -f msevc4prj
bakefile_gen -b ../../contrib/samples/gizmos/led/led.bkl -f msevc4prj
bakefile_gen -b ../../contrib/samples/gizmos/multicell/multicell.bkl -f msevc4prj
bakefile_gen -b ../../contrib/samples/gizmos/splittree/splittree.bkl -f msevc4prj
bakefile_gen -b ../../contrib/samples/mmedia/mmboard.bkl -f msevc4prj
bakefile_gen -b ../../contrib/samples/ogl/ogledit/ogledit.bkl -f msevc4prj
bakefile_gen -b ../../contrib/samples/ogl/studio/studio.bkl -f msevc4prj
bakefile_gen -b ../../contrib/samples/plot/plot.bkl -f msevc4prj
bakefile_gen -b ../../contrib/samples/stc/stctest.bkl -f msevc4prj
bakefile_gen -b ../../contrib/samples/svg/svgtest.bkl -f msevc4prj
bakefile_gen -b ../../contrib/samples/xrc/xrcdemo.bkl -f msevc4prj

