#!/bin/sh
# tardist: make up a tar.gz distribution of wxWindows 2
# Supply a source (e.g. ~/wx2) and destination (e.g. ~/wx2/deliver)

# We can't use e.g. this:
# ls `cat $SRC/distrib/msw/makefile.rsp` zip -@ -u $DEST/wxWindows-$VERSION-gen.zip
# because there's not enough space on the command line, plus we need to ignore the
# blank lines.

expandlines()
{
    toexpand=$1
    outputfile=$2

    rm -f $outputfile
    touch $outputfile
    for line in `cat $toexpand` ; do
      if [ "$line" != "" ]; then
        ls $line >> $outputfile
      fi
    done
}


init=""
if [ "$1" = "" ]
then
  echo Usage: tardist wx-dir output-dir version
  exit
fi

if [ "$2" = "" ]
then
  echo Usage: tardist wx-dir output-dir version
  exit
fi

if [ "$3" = "" ]
then
  echo Usage: tardist wx-dir output-dir version
  exit
fi

WXVER=$3

echo About to archive wxWindows:
echo   From   $1
echo   To     $2
echo CTRL-C if this is not correct.
read dummy

cd $1

echo Removing backup files...
rm *~ */*~ */*/*~ */*/*/*~ */*/*/*/*~

rm -f $2/wx*-${WXVER}*.tar.gz
rm -f $2/tex2rtf2-*.tar.gz
rm -f $2/dialoged-*.tar.gz
rm -f $2/ogl3-*.tar.gz
rm -f $2/jpeg-*.tar.gz
rm -f $2/tiff-*.tar.gz
rm -f $2/stc-*.tar.gz
rm -f $2/canvas-*.tar.gz
rm -f $2/contrib-*.tar.gz
rm -f $2/applet-*.tar.gz
rm -f $2/wxxrc-*.tar.gz

echo Tarring...

### Generic
ls `cat $1/distrib/msw/generic.rsp $1/distrib/msw/contrib.rsp $1/distrib/msw/xml.rsp $1/distrib/msw/makefile.rsp` > /tmp/wxgen.txt
tar cvf $2/wxWindows-${WXVER}-gen.tar -T /tmp/wxgen.txt
gzip $2/wxWindows-${WXVER}-gen.tar
mv $2/wxWindows-${WXVER}-gen.tar.gz $2/wxWindows-${WXVER}-gen.tgz

### wxGTK
ls `cat $1/distrib/msw/generic.rsp $1/distrib/msw/contrib.rsp $1/distrib/msw/xml.rsp $1/distrib/msw/gtk.rsp $1/distrib/msw/makefile.rsp $1/distrib/msw/tiff.rsp $1/distrib/msw/jpeg.rsp` > /tmp/wxgtk.txt
tar cvf $2/wxGTK-${WXVER}.tar -T /tmp/wxgtk.txt
gzip $2/wxGTK-${WXVER}.tar

### wxMotif
ls `cat $1/distrib/msw/generic.rsp $1/distrib/msw/motif.rsp $1/distrib/msw/contrib.rsp $1/distrib/msw/xml.rsp $1/distrib/msw/ogl.rsp $1/distrib/msw/makefile.rsp $1/distrib/msw/tiff.rsp $1/distrib/msw/jpeg.rsp` > /tmp/wxmotif.txt
tar cvf $2/wxMotif-${WXVER}.tar -T /tmp/wxmotif.txt
gzip $2/wxMotif-${WXVER}.tar

### wxX: combined wxMotif and wxX11 distributions
ls `cat $1/distrib/msw/generic.rsp $1/distrib/msw/motif.rsp $1/distrib/msw/x11.rsp $1/distrib/msw/univ.rsp $1/distrib/msw/contrib.rsp $1/distrib/msw/xml.rsp $1/distrib/msw/ogl.rsp $1/distrib/msw/makefile.rsp $1/distrib/msw/tiff.rsp $1/distrib/msw/jpeg.rsp` | uniq > /tmp/wxx.txt
tar cvf $2/wxX11-${WXVER}.tar -T /tmp/wxx.txt
gzip $2/wxX11-${WXVER}.tar

### wxMSW
ls `cat $1/distrib/msw/msw.rsp $1/distrib/msw/vc.rsp $1/distrib/msw/bc.rsp $1/distrib/msw/contrib.rsp $1/distrib/msw/xml.rsp $1/distrib/msw/makefile.rsp $1/distrib/msw/tiff.rsp $1/distrib/msw/jpeg.rsp` > /tmp/wxmsw.txt
tar cvf $2/wxMSW-${WXVER}.tar -T /tmp/wxmsw.txt
gzip $2/wxMSW-${WXVER}.tar

### Doc sources
ls `cat $1/distrib/msw/docsrc.rsp` > /tmp/docsrc.txt
tar cvf $2/wxWindows-${WXVER}-doc.tar -T /tmp/docsrc.txt
gzip $2/wxWindows-${WXVER}-doc.tar

### HTML docs
ls `cat $1/distrib/msw/wx_html.rsp` > /tmp/html.txt
tar cvf $2/wxWindows-${WXVER}-htm.tar -T /tmp/html.txt
gzip $2/wxWindows-${WXVER}-htm.tar

### PDF docs
ls `cat $1/distrib/msw/wx_pdf.rsp` > /tmp/pdf.txt
tar cvf $2/wxWindows-${WXVER}-pdf.tar -T /tmp/pdf.txt
gzip $2/wxWindows-${WXVER}-pdf.tar

### Stubs files
#ls `cat $1/distrib/msw/stubs.rsp` > /tmp/stubs.txt
#tar cvf $2/wxWindows-${WXVER}-stubs.tar -T /tmp/stubs.txt
#gzip $2/wxWindows-${WXVER}-stubs.tar

### Tex2RTF
ls `cat $1/distrib/msw/tex2rtf.rsp` > /tmp/tex2rtf.txt
tar cvf $2/tex2rtf2-${WXVER}.tar -T /tmp/tex2rtf.txt
gzip $2/tex2rtf2-${WXVER}.tar

### OGL
ls `cat $1/distrib/msw/ogl.rsp` > /tmp/ogl.txt
tar cvf $2/ogl3-${WXVER}.tar -T /tmp/ogl.txt
gzip $2/ogl3-${WXVER}.tar

### JPEG
ls `cat $1/distrib/msw/jpeg.rsp` > /tmp/jpeg.txt
tar cvf $2/jpeg-${WXVER}.tar -T /tmp/jpeg.txt
gzip $2/jpeg-${WXVER}.tar

### TIFF
ls `cat $1/distrib/msw/tiff.rsp` > /tmp/tiff.txt
tar cvf $2/tiff-${WXVER}.tar -T /tmp/tiff.txt
gzip $2/tiff-${WXVER}.tar

# Copy readme and other files
copy $1/docs/readme.txt $2/readme-${WXVER}.txt
copy $1/docs/changes.txt $2/changes-${WXVER}.txt
copy $1/docs/mgl/readme.txt $2/readme_mgl-${WXVER}.txt
copy $1/docs/mgl/install.txt $2/install_mgl-${WXVER}.txt
copy $1/docs/x11/readme.txt $2/readme_x11-${WXVER}.txt
copy $1/docs/x11/readme-nanox.txt $2/readme_nanox-${WXVER}.txt
copy $1/docs/x11/install.txt $2/install_x11-${WXVER}.txt
copy $1/docs/motif/readme.txt $2/readme_motif-${WXVER}.txt
copy $1/docs/motif/install.txt $2/install_motif-${WXVER}.txt
copy $1/docs/msw/readme.txt $2/readme_msw-${WXVER}.txt
copy $1/docs/msw/install.txt $2/install_msw-${WXVER}.txt
copy $1/docs/gtk/readme.txt $2/readme_gtk-${WXVER}.txt
copy $1/docs/gtk/install.txt $2/install_gtk-${WXVER}.txt
copy $1/docs/mac/readme.txt $2/readme_mac-${WXVER}.txt
copy $1/docs/mac/install.txt $2/install_mac-${WXVER}.txt

echo Done!
