#!/bin/sh
# tardist: make up a tar.gz distribution of wxWindows 2
# Supply a source (e.g. ~/wx2) and destination (e.g. ~/wx2/deliver)

# We can't use e.g. this:
# ls `cat $SRC/distrib/msw/makefile.rsp` zip -@ -u $DEST/wxWindows-$VERSION-gen.zip
# because there's not enough space on the command line, plus we need to ignore the
# blank lines.

expandlines()
{
    toexpand=$1
    outputfile=$2

    rm -f $outputfile
    touch $outputfile
    for line in `cat $toexpand` ; do
      if [ "$line" != "" ]; then
        ls $line >> $outputfile
      fi
    done
}


init=""
if [ "$1" = "" ]
then
  echo Usage: tardist wx-dir output-dir version
  exit
fi

if [ "$2" = "" ]
then
  echo Usage: tardist wx-dir output-dir version
  exit
fi

if [ "$3" = "" ]
then
  echo Usage: tardist wx-dir output-dir version
  exit
fi

WXVER=$3

echo About to archive wxWindows:
echo   From   $1
echo   To     $2
echo CTRL-C if this is not correct.
read dummy

cd $1

echo Removing backup files...
rm *~ */*~ */*/*~ */*/*/*~ */*/*/*/*~

rm -f $2/wxWindows-${WXVER}*.tgz
rm -f $2/tex2rtf2.tgz
rm -f $2/ogl3.tgz
rm -f $2/jpeg.tgz
rm -f $2/tiff.tgz

echo Tarring...

### Generic
ls `cat $1/distrib/msw/generic.rsp $1/distrib/msw/contrib.rsp $1/distrib/msw/makefile.rsp` > /tmp/wxgen.txt
tar cvf $2/wxWindows-${WXVER}-gen.tar -T /tmp/wxgen.txt
gzip $2/wxWindows-${WXVER}-gen.tar
mv $2/wxWindows-${WXVER}-gen.tar.gz $2/wxWindows-${WXVER}-gen.tgz

### wxGTK
ls `cat $1/distrib/msw/generic.rsp $1/distrib/msw/contrib.rsp $1/distrib/msw/xml.rsp $1/distrib/msw/gtk.rsp $1/distrib/msw/makefile.rsp` > /tmp/wxgtk.txt
tar cvf $2/wxWindows-${WXVER}-gtk.tar -T /tmp/wxgtk.txt
gzip $2/wxWindows-${WXVER}-gtk.tar
mv $2/wxWindows-${WXVER}-gtk.tar.gz $2/wxWindows-${WXVER}-gtk.tgz

### wxMotif
ls `cat $1/distrib/msw/generic.rsp $1/distrib/msw/motif.rsp $1/distrib/msw/contrib.rsp $1/distrib/msw/xml.rsp $1/distrib/msw/makefile.rsp` > /tmp/wxmotif.txt
tar cvf $2/wxWindows-${WXVER}-mot.tar -T /tmp/wxmotif.txt
gzip $2/wxWindows-${WXVER}-mot.tar
mv $2/wxWindows-${WXVER}-mot.tar.gz $2/wxWindows-${WXVER}-mot.tgz

### Doc sources
ls `cat $1/distrib/msw/docsrc.rsp` > /tmp/docsrc.txt
tar cvf $2/wxWindows-${WXVER}-doc.tar -T /tmp/docsrc.txt
gzip $2/wxWindows-${WXVER}-doc.tar
mv $2/wxWindows-${WXVER}-doc.tar.gz $2/wxWindows-${WXVER}-doc.tgz

### HTML docs
ls `cat $1/distrib/msw/wx_html.rsp` > /tmp/html.txt
tar cvf $2/wxWindows-${WXVER}-htm.tar -T /tmp/html.txt
gzip $2/wxWindows-${WXVER}-htm.tar
mv $2/wxWindows-${WXVER}-htm.tar.gz $2/wxWindows-${WXVER}-htm.tgz

### PDF docs
ls `cat $1/distrib/msw/wx_pdf.rsp` > /tmp/pdf.txt
tar cvf $2/wxWindows-${WXVER}-pdf.tar -T /tmp/pdf.txt
gzip $2/wxWindows-${WXVER}-pdf.tar
mv $2/wxWindows-${WXVER}-pdf.tar.gz $2/wxWindows-${WXVER}-pdf.tgz

### Stubs files
ls `cat $1/distrib/msw/stubs.rsp` > /tmp/stubs.txt
tar cvf $2/wxWindows-${WXVER}-stubs.tar -T /tmp/stubs.txt
gzip $2/wxWindows-${WXVER}-stubs.tar
mv $2/wxWindows-${WXVER}-stubs.tar.gz $2/wxWindows-${WXVER}-stubs.tgz

### Tex2RTF
ls `cat $1/distrib/msw/tex2rtf.rsp` > /tmp/tex2rtf.txt
tar cvf $2/tex2rtf2.tar -T /tmp/tex2rtf.txt
gzip $2/tex2rtf2.tar
mv $2/tex2rtf2.tar.gz $2/tex2rtf2.tgz

### OGL
ls `cat $1/distrib/msw/ogl.rsp` > /tmp/ogl.txt
tar cvf $2/ogl3.tar -T /tmp/ogl.txt
gzip $2/ogl3.tar
mv $2/ogl3.tar.gz $2/ogl3.tgz

### JPEG
ls `cat $1/distrib/msw/jpeg.rsp` > /tmp/jpeg.txt
tar cvf $2/jpeg.tar -T /tmp/jpeg.txt
gzip $2/jpeg.tar
mv $2/jpeg.tar.gz $2/jpeg.tgz

### TIFF
ls `cat $1/distrib/msw/tiff.rsp` > /tmp/tiff.txt
tar cvf $2/tiff.tar -T /tmp/tiff.txt
gzip $2/tiff.tar
mv $2/tiff.tar.gz $2/tiff.tgz

echo Done!
