#
# File:         makefile.g95
# Author:       Julian Smart
# Created:      1999
# Updated:
# Copyright:    (c) Julian Smart, 1999
#
# Makefile for wxWindows sample (Cygwin/Mingw32).

WXDIR = ../..

TARGET=life
EXTRALDFLAGS=-Wl,--subsystem,console
OBJECTS = $(TARGET).o dialogs.o game.o reader.o

include $(WXDIR)/src/makeprog.g95

