#
# File:		makefile.vc
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:	(c) Julian Smart
#
# Makefile : Builds sample (VC++, WIN32)
# Use FINAL=1 argument to nmake to build final version with no debug info.

# Set WXDIR for your system

WXDIR = $(WXWIN)

TARGET=test
OBJECTS = $(TARGET).obj test_wdr.obj

!include $(WXDIR)\src\makeprog.b32

