# Purpose: makefile for proplist example (BC++ 32bit)
# Created: 2000-03-15

WXDIR = $(WXWIN)

TARGET=proplist
EXTRALIBS=$(WXDIR)\lib\wxdeprecated.lib
OBJECTS = $(TARGET).obj

!include $(WXDIR)\src\makeprog.b32

