#
# File:		makefile.nt
# Author:	Julian Smart
# Created:	1997
# Updated:	
# Copyright:	(c) 1997, Julian Smart
#
# "%W% %G%"
#
# Makefile : Builds gui plugin example (MS VC++).
# Use FINAL=1 argument to nmake to build final version with no debugging
# info

# Set WXDIR for your system
WXDIR = $(WXWIN)

# Application is a DLL
DLL=1

EXTRAINC=/I$(WXDIR)\utils\nplugin\src

!include $(WXDIR)\src\ntwxwin.mak

THISDIR = $(WXDIR)\utils\nplugin\examples\gui
PROGRAM=npgui32
PLUGINLIB=$(WXDIR)\utils\nplugin\lib\nplugin.lib

OBJECTS = gui.obj

all:    $(PROGRAM).dll

$(PROGRAM):    $(PROGRAM).exe

wx:
        cd $(WXDIR)\src\msw
        nmake -f makefile.nt dllnp FINAL=$(FINAL)
        cd $(THISDIR)

# Update the dynamic link library

$(PROGRAM).dll: $(DUMMYOBJ) $(OBJECTS) $(WXDIR)\lib\wx.lib $(PLUGINLIB) $(PROGRAM).res $(PROGRAM).def
    $(link) $(LINKFLAGS) \
    -out:$(PROGRAM).dll   \
    -def:$(PROGRAM).def \
    $(DUMMYOBJ) $(OBJECTS) $(PROGRAM).res $(WXDIR)\lib\wx.lib $(PLUGINLIB) \
    $(guilibsdll) shell32.lib comctl32.lib ctl3d32.lib

gui.obj:      gui.$(SRCSUFF) gui.h $(DUMMYOBJ)
        $(cc) @<<
$(CPPFLAGS) /c /Tp $*.$(SRCSUFF)
<<

$(PROGRAM).res :      $(PROGRAM).rc $(WXDIR)\include\wx\msw\wx.rc
    $(rc) -r /i$(WXDIR)\include -fo$@ $(PROGRAM).rc

copy:
	copy npgui32.dll "c:\program files\Netscape\Navigator\program\plugins"
	copy npgui32.dll "c:\program files\Internet Explorer\plugins"

clean:
        -erase *.obj
        -erase *.exe
        -erase *.res
        -erase *.map
        -erase *.sbr
        -erase *.pdb
        -erase *.dll
        -erase *.exp
        -erase *.lib
        -erase *.ilk
