#
# File:         Makefile
# Author:       Hans Van Leemputten
# Created:      2001
# Updated:
# Copyright:    (c) wxWorkshop team, 2001
#
# Makefile for wxWorkshop for mingw & cygwin.

WXDIR = ../../../..
TARGET = fl_demo2

EXTRACPPFLAGS = -DBMP_DIR=\"../bitmaps/\"
EXTRALIBS     = $(WXDIR)/lib/libfl.a

OBJECTS = $(TARGET).o

include $(WXDIR)/src/makeprog.g95
