# Purpose: makefile for treelay example (VC++ 32bit)
# Created: 2000-03-15

# Set WXDIR for your system
WXDIR = $(WXWIN)

PROGRAM=treelay
FINAL=0
!if "$(FINAL)" == "0"
EXTRALIBS=$(WXDIR)\lib\wxdeprecatedd.lib
!else
EXTRALIBS=$(WXDIR)\lib\wxdeprecated.lib
!endif
OBJECTS = $(PROGRAM).obj

!include $(WXDIR)\src\makeprog.vc

