# Purpose: makefile for treelay example (Cygwin/Mingw32)
# Created: #03.01.00

WXDIR = ../../../..

TARGET=treelay
OBJECTS = $(TARGET).o
EXTRAINC = -I$(WXDIR)/contrib/include
EXTRALIBS = -lwxdeprecated

include $(WXDIR)/src/makeprog.g95

