<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<!-- ****************************************************** -->
<!--            Standard wxWidgets header                   -->

<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>$title</title>
    <meta name="author" content="wxWidgets team">
    <meta name="created" content="$datetime">
    <meta name="keywords" content="wxWidgets">
    <link href="wxwidgets.css" rel="stylesheet" type="text/css">
    <link href="tabs.css" rel="stylesheet" type="text/css">
</head>
<body>


<!--          End of wxWidgets standard header           -->
<!-- *************************************************** -->

