<!-- ******************************************************* -->
<!--             Standard wxWidgets footer                   -->

<br><hr>
<table width="100%" border="0">
<tr>
    <td align="left">
        <a href="http://www.wxwidgets.org" style="margin-left: 0px">
            <img src="powered-by-wxwidgets.png">
        </a>
    </td>
    <td valign="middle" align="center"><p class="footer">Page generated <tt>$datetime</tt> by <a href="http://www.doxygen.org">Doxygen</a> $doxygenversion</p></td>
    <td valign="middle" align="right"><p>[ <a href="#top" class="top">top</a> ]</p></td>
</tr>
</table>

</body>
</html>

<!-- ***************************************************** -->
<!--         End of wxWidgets standard footer              -->
