#
# File:		makefile.b32
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:
#
# Makefile : Builds sample for 32-bit BC++

WXDIR = $(WXWIN)

TARGET=studio
EXTRALIBS=$(WXDIR)\lib\ogl.lib
EXTRACPPFLAGS=-I$(WXDIR)\utils\ogl\src
OBJECTS = $(TARGET).obj doc.obj shapes.obj symbols.obj view.obj cspalette.obj\
  mainfrm.obj project.obj dialogs.obj csprint.obj

!include $(WXDIR)\src\makeprog.b32

