# Purpose: makefile for multicell example (Unix)
# Created 2000-07-28

CXX = $(shell wx-config --cxx)

PROGRAM = mtest

OBJECTS = $(PROGRAM).o ../src/multicell.o
EXTRAINC=-I../include

# implementation

.SUFFIXES:	.o .cpp

.cpp.o :
	$(CXX) -c `wx-config --cxxflags` -o $@ $<

all:    $(PROGRAM)

$(PROGRAM):	$(OBJECTS)
	$(CXX) -o $(PROGRAM) $(OBJECTS) `wx-config --libs`

clean:
	rm -f *.o $(PROGRAM)
