#
# File:         makefile.g95
# Author:       Julian Smart
# Created:      1999
# Updated:
# Copyright:    (c) Julian Smart, 1999
#
# Makefile for wxWindows Net library Cygwin/Mingw32).

WXDIR = ../../..

LIBTARGET=$(WXDIR)/lib/libnet.a
OBJECTS = smapi.o email.o web.o

include $(WXDIR)/src/makelib.g95

