#
# File:     makefile.va
# Author:   David Webster
# Created:  1999
# Updated:
# Copyright:    (c) David Webster
#
# Makefile : Builds sample (VisualAgeC++ V3.0, OS/2 PM)
# Use FINAL=1 argument to nmake to build final version with no debug info.

# Set WXDIR for your system
WXDIR = $(WXWIN)

WXUSINGDLL=0

!include $(WXDIR)\src\makeva.env

PROGRAM=$D\dragimag
OBJECTS = $(PROGRAM).obj

!if [md $D]
!endif

!include $(WXDIR)\src\makeprog.va

