/* XPM */
static char *iphonebattery_png[] = {
/* columns rows colors chars-per-pixel */
"24 12 3 1 ",
"  c black",
". c #24279F971112",
"X c None",
/* pixels */
"XXXXXXXXXXXXXXXXXXXXXXXX",
"X                   XXXX",
"X XXXXXXXXXXXXXXXXX XXXX",
"X X.............XXX XXXX",
"X X.............XXX    X",
"X X.............XXX XX X",
"X X.............XXX XX X",
"X X.............XXX    X",
"X X.............XXX XXXX",
"X XXXXXXXXXXXXXXXXX XXXX",
"X                   XXXX",
"XXXXXXXXXXXXXXXXXXXXXXXX"
};
