#!/bin/bash
#----------------------------------------------------------------------

set -o errexit

if [ $skipsource != yes -o $onlysource = yes ]; then

    # make the source tarball and srpm
    distrib/make_src_tarball

    # Copy everything to the staging dir
    echo "Moving stuff to $STAGING_DIR..."
    mv dist/* $STAGING_DIR

fi 
