#!/bin/bash
#----------------------------------------------------------------------

set -o errexit

# read the config variables from the file given on the command line
. $1

if [ $skipsource != yes -o $onlysource = yes ]; then

    # make the source tarball and srpm
    distrib/makerpm 2.3 srpm

    # Copy everything to the staging dir
    echo "Moving stuff to $STAGING_DIR..."
    mv dist/* $STAGING_DIR

fi 
