#!/bin/bash
# ---------------------------------------------------------------------------
# Build wxWidgets and wxPython on a OSX box.  This is normally 
# called from build-all but it should be able to be used standalone too...
# 
# The command line must have the following parameters:
#
#    1. the path to the base of the wx source tree
#    2. the path of where to put the resulting installers
#    3. skipclean flag (yes|no)
#    4. the VERSION
#    5. the FLAVOR (panther or jaguar)
#    *. the remaining args are the versions of Python to build for
#
# ---------------------------------------------------------------------------

set -o errexit
#set -o xtrace

echo "-=-=-=-  Hello from $HOSTNAME  -=-=-=-"

if [ $# -lt 6 ]; then
    echo "Usage: $0 WXDIR DESTDIR SKIPCLEAN VERSION FLAVOR PYVER..."
    exit 1
fi

WXDIR=$1
DESTDIR=$2
SKIPCLEAN=$3
VERSION=$4
FLAVOR=$5
shift;shift;shift;shift;shift
PYVER=$@


export PATH=/sw/bin:/usr/local/bin:$PATH


# untar the source 
echo "Unarchiving wxPythonSrc-$VERSION.tar.gz"
cd $DESTDIR
tar xzf wxPythonSrc-$VERSION.tar.gz 
rm wxPythonSrc-$VERSION.tar.gz


echo "Invoking wxPythonOSX build script..."
cd $WXDIR/wxPython
export TARBALLDIR=$DESTDIR
mkdir -p dist
distrib/mac/wxPythonOSX/build $FLAVOR inplace skipclean


echo "Copying installers to $DESTDIR..."
cp dist/*.dmg $DESTDIR
cd $DESTDIR


if [ $SKIPCLEAN != yes ]; then 
    echo "Cleaning up..."
    rm -r $WXDIR || true
    rm wxPythonDocs-$VERSION.tar.gz
    rm wxPythonDemo-$VERSION.tar.gz
fi

echo "-=-=-=-  Goodbye!  -=-=-=-"
