#!/bin/bash
#----------------------------------------------------------------------

set -o errexit

# read the config variables from the file given on the command line
. $1


# clean out the local dist dir
rm -f dist/*

