#!/bin/bash
#----------------------------------------------------------------------

set -o errexit


PYVER=$1

if [ $buildansi = yes ]; then
    CHARTYPE=both
else
    CHARTYPE=unicode
fi


if [ $skipwin != yes ]; then
    # test if the target machine is online
    if ping -q -c1 -w1 $WIN_HOST > /dev/null; then
	echo " The $WIN_HOST machine is online, Windows build continuing..."
    else
	echo "The $WIN_HOST machine is **OFFLINE**, skipping the Windows build."
	return 0
    fi

    echo "Copying source, docs and build script..."
    scp $STAGING_DIR/wxPython-src-$VERSION.tar.bz2 \
	$STAGING_DIR/wxPython-docs-$VERSION.tar.bz2 \
	distrib/all/do-build-windows \
	$WIN_HOST:$WIN_BUILD
    
     echo "Running build script on $WIN_HOST..."
     wxdir=$WIN_BUILD/wxPython-src-$VERSION
     cmd=./do-build-windows
     ssh $WIN_HOST "cd $WIN_BUILD && $cmd $wxdir $WIN_BUILD $skipclean $VERSION $PYVER $CHARTYPE && rm $cmd"

     echo "Fetching the results..."
     scp "$WIN_HOST:$WIN_BUILD/wxPython*-win32*"  $STAGING_DIR
     ssh $WIN_HOST "rm $WIN_BUILD/wxPython*-win32*"
     ssh $WIN_HOST "rm -rf $WIN_BUILD/*"

     echo "Done!"
fi