#!/bin/bash
#----------------------------------------------------------------------

set -o errexit



chmod a+r $STAGING_DIR/*

if [ $KIND = dryrun ]; then
    # we're done leave the files in the staging dir and quit
    echo "Not uploading dryrun."
    exit 0
fi


if [ $KIND = daily ]; then 

    echo "Copying to the local file server..."
    destdir=/stuff/temp/$VERSION
    mkdir -p $destdir
    cp $STAGING_DIR/* $destdir

    if [ $skipupload != yes ]; then 
	destdir=$UPLOAD_PREVIEW_ROOT/$DAILY
	echo "Copying to $UPLOAD_HOST at $destdir..."
	if [ $UPLOAD_METHOD = ssh ]; then
	    ssh $UPLOAD_HOST "mkdir -p $destdir"
	    scp -p $STAGING_DIR/* $UPLOAD_HOST:/$destdir
	fi
	if [ $UPLOAD_METHOD = ftp ]; then
	    lftp -c "open $UPLOAD_HOST; mkdir $destdir"
	    lftp -c "open $UPLOAD_HOST; cd $destdir; mput $STAGING_DIR/*"
	fi

        # TODO: something to remove old builds from starship, keeping 
        # only N days worth

        # Send email to wxPython-dev
	DATE=`date`
	TO=wxPython-dev@lists.wxwidgets.org

	cat <<EOF  | /usr/sbin/sendmail  $TO
From: R'bot <rbot@wxpython.org>
To: $TO
Subject: $DAILY test build uploaded
Date: $DATE

Hi,

A new test build of wxPython has been uploaded.  

   Version: $VERSION
   URL:     $UPLOAD_URL_ROOT/preview/$DAILY
   Changes: $UPLOAD_URL_ROOT/preview/$DAILY/CHANGES.html

Have fun!
R'bot

EOF
    fi

    echo "Cleaning up staging dir..."
    rm $STAGING_DIR/*
    rmdir $STAGING_DIR

    exit 0
fi


if [ $KIND = release ]; then 

    echo "Copying to the local file server..."
    destdir=/stuff/Development/wxPython/dist/$VERSION
    mkdir -p $destdir
    cp $STAGING_DIR/* $destdir

    if [ $skipupload != yes ]; then 
	echo "Copying to $UPLOAD_HOST..."
	destdir=$UPLOAD_RELEASE_ROOT/$VERSION
	if [ $UPLOAD_METHOD = ssh ]; then
	    ssh $UPLOAD_HOST "mkdir -p $destdir"
	    scp -p $STAGING_DIR/* $UPLOAD_HOST:/$destdir
	fi
	if [ $UPLOAD_METHOD = ftp ]; then
	    lftp -c "open $UPLOAD_HOST; mkdir $destdir"
	    lftp -c "open $UPLOAD_HOST; cd $destdir; mput $STAGING_DIR/*"
	fi

        # Send email to wxPython-dev
	DATE=`date`
	TO=wxPython-dev@lists.wxwidgets.org

	cat <<EOF  | /usr/sbin/sendmail  $TO
From: R'bot <rbot@wxpython.org>
To: $TO
Subject: $VERSION release candidate build uploaded
Date: $DATE

Hi,

A new RC build of wxPython has been uploaded to starship.  

   Version: $VERSION
   URL:     $UPLOAD_URL_ROOT/release/$VERSION
   Changes: $UPLOAD_URL_ROOT/release/$VERSION/CHANGES.html

Have fun!
R'bot

EOF

    fi

    echo "Cleaning up staging dir..."
    rm $STAGING_DIR/*
    rmdir $STAGING_DIR

    exit 0
fi

