#!/bin/bash
#----------------------------------------------------------------------

set -o errexit

# read the config variables from the file given on the command line
. $1


if [ $skipdocs != yes ]; then 
    # Regenerate the reST docs
    echo "Regenerating the reST docs..."
    cd docs
    for x in *.txt; do
	docutils-html $x `basename $x .txt`.html
    done
    cd -
    for doc in CHANGES BUILD INSTALL MigrationGuide default; do
	cp docs/$doc.* $STAGING_DIR
    done
	
    # build the doc and demo tarballs
    distrib/makedemo
    distrib/makedocs
    mv dist/wxPython-docs-$VERSION.tar.gz $STAGING_DIR
    mv dist/wxPython-demo-$VERSION.tar.gz $STAGING_DIR


    # build the new docs too
    if [ $skipnewdocs != yes ]; then
	docs/bin/everything
	mv dist/wxPython-newdocs-$VERSION.tar.gz $STAGING_DIR
    fi
fi

#----------------------------------------------------------------------
