#!/bin/bash
#----------------------------------------------------------------------

set -o errexit

# read the config variables from the file given on the command line
. $1


if [ $skipwin != yes ]; then
    # test if the target machine is online
    if ping -q -c1 -w1 $WIN_HOST > /dev/null; then
	echo " The $WIN_HOST machine is online, Windows build continuing..."
    else
	echo "The $WIN_HOST machine is **OFFLINE**, skipping the Windows build."
	return 0
    fi

    echo "Copying source file and build script..."
    scp $STAGING_DIR/wxPython-src-$VERSION.tar.gz \
	distrib/all/do-build-windows \
	$WIN_HOST:$WIN_BUILD
    
     echo "Running build script on $WIN_HOST..."
     wxdir=$WIN_BUILD/wxPython-src-$VERSION
     cmd=./do-build-windows
     ssh $WIN_HOST "cd $WIN_BUILD && $cmd $wxdir $WIN_BUILD $skipclean $VERSION $PYVER && rm $cmd"

     echo "Fetching the results..."
     scp "$WIN_HOST:$WIN_BUILD/wxPython*-win32*"  $STAGING_DIR
     ssh $WIN_HOST "rm $WIN_BUILD/wxPython*-win32*"
fi