#!/bin/bash
#----------------------------------------------------------------------

set -o errexit

# read the config variables from the file given on the command line
. $1


host=$2
flavor=$3

if [ $skiposx != yes ]; then
    # test if the target machine is online
    if ping -q -c1 -w1 $host > /dev/null; then
	echo " The $host machine is online, OSX-$flavor build continuing..."
    else
	echo "The $host machine is **OFFLINE**, skipping the OSX-$flavor build."
	exit 0
    fi

    echo "Copying source files and build script..."
    ssh root@$host "mkdir -p $OSX_BUILD && rm -rf $OSX_BUILD/* || true"
    
    scp $STAGING_DIR/wxPython-src-$VERSION.tar.gz \
	$STAGING_DIR/wxPython-docs-$VERSION.tar.gz \
	$STAGING_DIR/wxPython-demo-$VERSION.tar.gz \
	distrib/all/do-build-osx \
	root@$host:$OSX_BUILD

    echo "Running build script on $host..."
    wxdir=$OSX_BUILD/wxPython-src-$VERSION
    cmd=./do-build-osx
    ssh root@$host "cd $OSX_BUILD && $cmd $wxdir $OSX_BUILD $skipclean $VERSION $flavor $PYVER && rm $cmd"
    
    echo "Fetching the results..."
    scp "root@$host:$OSX_BUILD/wxPython*-osx*"  $STAGING_DIR
    ssh root@$host "rm $OSX_BUILD/wxPython*-osx*"
fi

