#
# File:		makefile.unx
# Author:	Julian Smart
# Created:	1998
# Updated:	
# Copyright:	(c) 1998 Julian Smart
#
# "%W% %G%"
#
# Makefile for docview example (UNIX).

PROGRAM=docview

OBJECTS=$(PROGRAM).o doc.o view.o

include ../../src/makeprog.env


