#
# File:		makefile.b32
# Author:       Andre Beltman
# Created:	1995
# Updated:	
# Copyright:    (c) 1995, AIAI, University of Edinburgh
#
# "%W% %G%"
#
# Makefile : Imports 32bit ctl3d library for Windows 95
# and Borland C++ 4.x

WXDIR = $(WXWIN)
WXLIB = $(WXDIR)\lib

LIBTARGET= $(WXLIB)\ctl3d32.lib

all:    $(LIBTARGET)

$(LIBTARGET):
	erase $(LIBTARGET)
        implib $(LIBTARGET) ..\ctl3d32.dll

clean:
        -erase $(LIBTARGET)
