#
# File:		makefile.bcc
# Author:	Julian Smart
# Created:	1998
# Updated:	
#
# Builds OGL library for BC++, 16-bit

!if "$(WXWIN)" == ""
!error You must define the WXWIN variable in autoexec.bat, e.g. WXWIN=c:\wx
!endif

WXDIR = $(WXWIN)

LIBTARGET=$(WXDIR)\lib\ogl.lib

OBJECTS = basic.obj basic2.obj canvas.obj ogldiag.obj lines.obj misc.obj divided.obj constrnt.obj\
 composit.obj drawn.obj bmpshape.obj mfutils.obj

!include $(WXDIR)\src\makelib.bcc

