#
# File:		makefile.b32
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:
#
# Makefile : Builds OGL library for 32-bit BC++

WXDIR = $(WXWIN)

LIBTARGET=$(WXDIR)\lib\ogl.lib

OBJECTS = basic.obj basic2.obj canvas.obj ogldiag.obj lines.obj misc.obj divided.obj constrnt.obj\
 composit.obj drawn.obj bmpshape.obj mfutils.obj

!include $(WXDIR)\src\makelib.b32

