#----------------------------------------------------------------------
# Convenience makefile to drive the build script in a more user
# friendly manner.
#----------------------------------------------------------------------


all:
	./buildall -b


install: all
	./buildall -i

clean:
	./buildall -c

uninstall:
	./buildall -u
