
#----------------------------------------------------------------------

TARGET = htmlc

OBJECTS = html.obj

PYMODULES = $(TARGETDIR)\html.py $(TARGETDIR)\htmlhelper.py 

SOURCES = $(GENCODEDIR)\html.cpp 


#----------------------------------------------------------------------

!include ..\makeinc.vc

#----------------------------------------------------------------------

default: $(TARGETDIR)\$(TARGET).pyd pycfiles

all:    $(TARGET)

# for generating the html.cpp file
$(GENCODEDIR)/html.cpp : html.i

#----------------------------------------------------------------------

$(TARGETDIR)\$(TARGET).pyd : $(DUMMYOBJ) $(WXLIB) $(OBJECTS) # $(TARGET).res
	$(link) @<<
/out:$@ /dll
$(LFLAGS) /def:$(TARGET).def /implib:./$(TARGET).lib
$(DUMMYOBJ) $(OBJECTS) 
$(LIBS)
<<


#----------------------------------------------------------------------

