#
# File:		makefile.bcc
# Author:	Julian Smart
# Created:	1998
# Updated:	
#
# Builds a BC++ 16-bit sample

!if "$(WXWIN)" == ""
!error You must define the WXWIN variable in autoexec.bat, e.g. WXWIN=c:\wx
!endif

WXDIR = $(WXWIN)

TARGET=widgets button.obj combobox.obj gauge.obj listbox.obj\
 notebook.obj radiobox.obj slider.obj spinbtn.obj static.obj textctrl.obj
OBJECTS=$(TARGET).obj

!include $(WXDIR)\src\makeprog.bcc

