#
# File:		makefile.b32
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:
#
# Makefile : Builds sample for 32-bit BC++

WXDIR = $(WXWIN)

TARGET=widgets
OBJECTS = $(TARGET).obj button.obj combobox.obj gauge.obj listbox.obj\
 notebook.obj radiobox.obj slider.obj spinbtn.obj static.obj textctrl.obj

!include $(WXDIR)\src\makeprog.b32

