#
# File:		makefile.vc
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:	(c) Julian Smart
#
# Makefile : Builds sample (VC++, WIN32)
# Use FINAL=1 argument to nmake to build final version with no debug info.

# Set WXDIR for your system
WXDIR = $(WXWIN)

PROGRAM=widgets
OBJECTS = $(PROGRAM).obj button.obj combobox.obj gauge.obj listbox.obj\
 notebook.obj radiobox.obj slider.obj spinbtn.obj static.obj textctrl.obj

!include $(WXDIR)\src\makeprog.vc

