#
# File:         makefile.g95
# Author:       Julian Smart
# Created:      1999
# Updated:
# Copyright:    (c) Julian Smart, 1999
#
# Makefile for wxrc (Cygwin/Mingw32).

WXDIR = ../../..

TARGET=wxrcedit
EXTRALIBS=-lwxxml
OBJECTS=edapp.o editor.o nodehnd.o xmlhelpr.o preview.o nodesdb.o \
        pe_basic.o pe_adv.o propedit.o propframe.o splittree.o
include $(WXDIR)/src/makeprog.g95

