#
# File:         makefile.g95
# Author:       Julian Smart
# Created:      1999
# Updated:
# Copyright:    (c) Julian Smart, 1999
#
# Makefile for wxrc (Cygwin/Mingw32).

WXDIR = ../../..

TARGET=wxrcedit
EXTRALIBS=-lwxxml
OBJECTS = edapp.o editor.o nodehnd.o prophnd.o xmlhelpr.o
include $(WXDIR)/src/makeprog.g95

