#
# File:		makefile.bcc
# Author:	Julian Smart
# Created:	1998
# Updated:	
#
# Builds a BC++ 16-bit sample

!if "$(WXWIN)" == ""
!error You must define the WXWIN variable in autoexec.bat, e.g. WXWIN=c:\wx
!endif

WXDIR = $(WXWIN)

TARGET=studio
EXTRALIBS=$(WXDIR)\contrib\lib\ogl.lib
OBJECTS = $(TARGET).obj doc.obj shapes.obj symbols.obj view.obj cspalette.obj\
  mainfrm.obj project.obj dialogs.obj csprint.obj

!include $(WXDIR)\src\makeprog.bcc

