#
# File:		makefile.bcc
# Author:	Julian Smart
# Created:	1998
# Updated:
#
# Builds Gizmos library for BC++, 16-bit

!if "$(WXWIN)" == ""
!error You must define the WXWIN variable in autoexec.bat, e.g. WXWIN=c:\wx
!endif

WXDIR = $(WXWIN)

LIBTARGET=$(WXDIR)\lib\gizmos.lib

OBJECTS = multicell.obj splittree.obj editlbox.obj dynamicsash.obj ledctrl.obj

!include $(WXDIR)\src\makelib.bcc

