#
# File:		makefile.b32
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:
#
# Makefile : Builds Gizmos library for 32-bit BC++

WXDIR = $(WXWIN)

LIBTARGET=$(WXDIR)\lib\gizmos.lib

OBJECTS = multicell.obj splittree.obj

!include $(WXDIR)\src\makelib.b32

