#
# File:         makefile.g95
# Author:       Julian Smart
# Created:      1999
# Updated:
# Copyright:    (c) Julian Smart, 1999
#
# Makefile for wxWindows Gizmos library Cygwin/Mingw32).

WXDIR = ../../..

LIBTARGET=$(WXDIR)/lib/libgizmos.a
OBJECTS = multicell.o splittree.o

include $(WXDIR)/src/makelib.g95

