#! /bin/sh
#
# This script is creates a dir tree in ~/wxmotif_dist which
# can then be packed into an archive

echo                               --------
echo    This script will copy the wxMotif release files into ~/wxmotif_dist
echo                               --------
echo

mkdir ~/wxmotif_dist
mkdir ~/wxmotif_dist/wxMotif

echo Base dir..

cd ../..
cp wxMotif.spec ~/wxmotif_dist/wxMotif
cp Makefile.am ~/wxmotif_dist/wxMotif
cp acconfig.h ~/wxmotif_dist/wxMotif
cp acinclude.m4 ~/wxmotif_dist/wxMotif
cp aclocal.m4 ~/wxmotif_dist/wxMotif
cp configure.in ~/wxmotif_dist/wxMotif
cp configure ~/wxmotif_dist/wxMotif
cp config.sub ~/wxmotif_dist/wxMotif
cp config.guess ~/wxmotif_dist/wxMotif
cp install-sh ~/wxmotif_dist/wxMotif
cp ltconfig ~/wxmotif_dist/wxMotif
cp ltmain.sh ~/wxmotif_dist/wxMotif
cp missing ~/wxmotif_dist/wxMotif
cp mkinstalldirs ~/wxmotif_dist/wxMotif
cp wx-config.in ~/wxmotif_dist/wxMotif
cp makefile.unx.in ~/wxmotif_dist/wxMotif
cp setup.h.in ~/wxmotif_dist/wxMotif
cp stamp-h.in ~/wxmotif_dist/wxMotif
cp Makefile.in ~/wxmotif_dist/wxMotif

echo Docs..

cd docs/motif2
cp COPYING.LIB ~/wxmotif_dist/wxMotif
cp install.txt ~/wxmotif_dist/wxMotif/INSTALL.txt
cp changes.txt ~/wxmotif_dist/wxMotif/CHANGES.txt
cp licence.txt ~/wxmotif_dist/wxMotif/LICENCE.txt
cp readme.txt ~/wxmotif_dist/wxMotif/README.txt
cp todo.txt ~/wxmotif_dist/wxMotif/TODO.txt
cd ..
cp symbols.txt ~/wxmotif_dist/wxMotif/SYMBOLS.txt
cd ..

echo Include dir..

mkdir ~/wxmotif_dist/wxMotif/include
cd include
cp Makefile.am ~/wxmotif_dist/wxMotif/include
cp Makefile.in ~/wxmotif_dist/wxMotif/include

mkdir ~/wxmotif_dist/wxMotif/include/wx
cd wx
cp *.h ~/wxmotif_dist/wxMotif/include/wx
cp *.cpp ~/wxmotif_dist/wxMotif/include/wx
cp Makefile.am ~/wxmotif_dist/wxMotif/include/wx
cp Makefile.in ~/wxmotif_dist/wxMotif/include/wx

mkdir ~/wxmotif_dist/wxMotif/include/wx/generic
cd generic
cp *.h ~/wxmotif_dist/wxMotif/include/wx/generic
cp *.xpm ~/wxmotif_dist/wxMotif/include/wx/generic
cp Makefile.am ~/wxmotif_dist/wxMotif/include/wx/generic
cp Makefile.in ~/wxmotif_dist/wxMotif/include/wx/generic
cd ..

mkdir ~/wxmotif_dist/wxMotif/include/wx/html
cd html
cp *.h ~/wxmotif_dist/wxMotif/include/wx/html
cp Makefile.am ~/wxmotif_dist/wxMotif/include/wx/html
cp Makefile.in ~/wxmotif_dist/wxMotif/include/wx/html
cd ..

mkdir ~/wxmotif_dist/wxMotif/include/wx/unix
cd unix
cp *.h ~/wxmotif_dist/wxMotif/include/wx/unix
cp Makefile.am ~/wxmotif_dist/wxMotif/include/wx/unix
cp Makefile.in ~/wxmotif_dist/wxMotif/include/wx/unix
cd ..

mkdir ~/wxmotif_dist/wxMotif/include/wx/msw
cd msw
cp Makefile.am ~/wxmotif_dist/wxMotif/include/wx/msw
cp Makefile.in ~/wxmotif_dist/wxMotif/include/wx/msw
cd ..

mkdir ~/wxmotif_dist/wxMotif/include/wx/motif
cd motif
cp *.h ~/wxmotif_dist/wxMotif/include/wx/motif
rm ~/wxmotif_dist/wxMotif/include/wx/motif/setup.h
cp Makefile.am ~/wxmotif_dist/wxMotif/include/wx/motif
cp Makefile.in ~/wxmotif_dist/wxMotif/include/wx/motif
cd ..

mkdir ~/wxmotif_dist/wxMotif/include/wx/gtk
cd gtk
cp Makefile.am ~/wxmotif_dist/wxMotif/include/wx/gtk
cp Makefile.in ~/wxmotif_dist/wxMotif/include/wx/gtk
cd ..

mkdir ~/wxmotif_dist/wxMotif/include/wx/protocol
cd protocol
cp *.h ~/wxmotif_dist/wxMotif/include/wx/protocol
cp Makefile.am ~/wxmotif_dist/wxMotif/include/wx/protocol
cp Makefile.in ~/wxmotif_dist/wxMotif/include/wx/protocol
cd ..

cd ../..

echo Misc dir..

mkdir ~/wxmotif_dist/wxMotif/misc
cd misc
cp Makefile.am ~/wxmotif_dist/wxMotif/misc
cp Makefile.in ~/wxmotif_dist/wxMotif/misc
mkdir ~/wxmotif_dist/wxMotif/misc/afm
cd afm
cp *.afm ~/wxmotif_dist/wxMotif/misc/afm
cp Makefile.am ~/wxmotif_dist/wxMotif/misc/afm
cp Makefile.in ~/wxmotif_dist/wxMotif/misc/afm
cd ..
mkdir ~/wxmotif_dist/wxMotif/misc/gs_afm
cd gs_afm
cp *.afm ~/wxmotif_dist/wxMotif/misc/gs_afm
cp Makefile.am ~/wxmotif_dist/wxMotif/misc/gs_afm
cp Makefile.in ~/wxmotif_dist/wxMotif/misc/gs_afm
cd ../..

echo Src dir..

cd src
mkdir ~/wxmotif_dist/wxMotif/src
cp Makefile.am ~/wxmotif_dist/wxMotif/src
cp Makefile.in ~/wxmotif_dist/wxMotif/src

cd motif
mkdir ~/wxmotif_dist/wxMotif/src/motif
cp Makefile.am ~/wxmotif_dist/wxMotif/src/motif
cp Makefile.in ~/wxmotif_dist/wxMotif/src/motif
cp *.xbm ~/wxmotif_dist/wxMotif/src/motif
cp *.c ~/wxmotif_dist/wxMotif/src/motif
cp *.cpp ~/wxmotif_dist/wxMotif/src/motif
cd ..

cd common
mkdir ~/wxmotif_dist/wxMotif/src/common
cp glob.inc ~/wxmotif_dist/wxMotif/src/common
cp lexer.l ~/wxmotif_dist/wxMotif/src/common
cp parser.y ~/wxmotif_dist/wxMotif/src/common
cp extended.c ~/wxmotif_dist/wxMotif/src/common
cp unzip.* ~/wxmotif_dist/wxMotif/src/common
cp *.cpp ~/wxmotif_dist/wxMotif/src/common
cd ..

cd html
mkdir ~/wxmotif_dist/wxMotif/src/html
cp *.cpp ~/wxmotif_dist/wxMotif/src/html
cp *.h ~/wxmotif_dist/wxMotif/src/html
cd bitmaps
mkdir ~/wxmotif_dist/wxMotif/src/html/bitmaps
cp *.xpm ~/wxmotif_dist/wxMotif/src/html/bitmaps
cd ../..

cd unix
mkdir ~/wxmotif_dist/wxMotif/src/unix
cp *.cpp ~/wxmotif_dist/wxMotif/src/unix
cp *.h ~/wxmotif_dist/wxMotif/src/unix
cp *.c ~/wxmotif_dist/wxMotif/src/unix
cd ..

cd generic
mkdir ~/wxmotif_dist/wxMotif/src/generic
cp *.cpp ~/wxmotif_dist/wxMotif/src/generic
cd ..

cd iodbc
mkdir ~/wxmotif_dist/wxMotif/src/iodbc
cp * ~/wxmotif_dist/wxMotif/src/iodbc
cd ..

cd zlib
mkdir ~/wxmotif_dist/wxMotif/src/zlib
cp * ~/wxmotif_dist/wxMotif/src/zlib
cd ..

cd png
mkdir ~/wxmotif_dist/wxMotif/src/png
cp * ~/wxmotif_dist/wxMotif/src/png
cd ..

cd jpeg
mkdir ~/wxmotif_dist/wxMotif/src/jpeg
cp * ~/wxmotif_dist/wxMotif/src/jpeg
cd ..

cd ..

echo Utils dir..

cd utils
mkdir ~/wxmotif_dist/wxMotif/utils
cp Makefile.am ~/wxmotif_dist/wxMotif/utils
cp Makefile.in ~/wxmotif_dist/wxMotif/utils
cd ..

echo Samples dir..

cd samples
mkdir ~/wxmotif_dist/wxMotif/samples
cp Makefile.am ~/wxmotif_dist/wxMotif/samples
cp Makefile.in ~/wxmotif_dist/wxMotif/samples

echo Minimal sample..

cd minimal
mkdir ~/wxmotif_dist/wxMotif/samples/minimal
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/minimal
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/minimal
cp minimal.cpp ~/wxmotif_dist/wxMotif/samples/minimal
cp mondrian.xpm ~/wxmotif_dist/wxMotif/samples/minimal
cd ..

echo Bombs sample..

cd bombs
mkdir ~/wxmotif_dist/wxMotif/samples/bombs
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/bombs
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/bombs
cp *.cpp ~/wxmotif_dist/wxMotif/samples/bombs
cp *.h ~/wxmotif_dist/wxMotif/samples/bombs
cp *.xpm ~/wxmotif_dist/wxMotif/samples/bombs
cd ..

echo Caret sample..

cd caret
mkdir ~/wxmotif_dist/wxMotif/samples/caret
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/caret
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/caret
cp *.cpp ~/wxmotif_dist/wxMotif/samples/caret
cp *.xpm ~/wxmotif_dist/wxMotif/samples/caret
cd ..

echo Checklst sample..

cd checklst
mkdir ~/wxmotif_dist/wxMotif/samples/checklst
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/checklst
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/checklst
cp *.cpp ~/wxmotif_dist/wxMotif/samples/checklst
cp *.xpm ~/wxmotif_dist/wxMotif/samples/checklst
cd ..

echo Config sample..

cd config
mkdir ~/wxmotif_dist/wxMotif/samples/config
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/config
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/config
cp *.cpp ~/wxmotif_dist/wxMotif/samples/config
cd ..

echo Controls sample..

cd controls
mkdir ~/wxmotif_dist/wxMotif/samples/controls
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/controls
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/controls
cp *.cpp ~/wxmotif_dist/wxMotif/samples/controls
cp *.xpm ~/wxmotif_dist/wxMotif/samples/controls
cd icons
mkdir ~/wxmotif_dist/wxMotif/samples/controls/icons
cp *.xpm ~/wxmotif_dist/wxMotif/samples/controls/icons
cd ../..

echo Db sample..

cd db
mkdir ~/wxmotif_dist/wxMotif/samples/db
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/db
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/db
cp *.cpp ~/wxmotif_dist/wxMotif/samples/db
cp *.h ~/wxmotif_dist/wxMotif/samples/db
cp *.xpm ~/wxmotif_dist/wxMotif/samples/db
cd ..

echo DDE sample..

cd dde
mkdir ~/wxmotif_dist/wxMotif/samples/dde
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/dde
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/dde
cp *.cpp ~/wxmotif_dist/wxMotif/samples/dde
cp *.h ~/wxmotif_dist/wxMotif/samples/dde
cp *.xpm ~/wxmotif_dist/wxMotif/samples/dde
cd ..

echo Dialogs sample..

cd dialogs
mkdir ~/wxmotif_dist/wxMotif/samples/dialogs
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/dialogs
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/dialogs
cp *.cpp ~/wxmotif_dist/wxMotif/samples/dialogs
cp *.h ~/wxmotif_dist/wxMotif/samples/dialogs
cd ..

echo DnD sample..

cd dnd
mkdir ~/wxmotif_dist/wxMotif/samples/dnd
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/dnd
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/dnd
cp *.cpp ~/wxmotif_dist/wxMotif/samples/dnd
cp *.xpm ~/wxmotif_dist/wxMotif/samples/dnd
cd ..

echo Docview sample..

cd docview
mkdir ~/wxmotif_dist/wxMotif/samples/docview
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/docview
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/docview
cp *.cpp ~/wxmotif_dist/wxMotif/samples/docview
cp *.h ~/wxmotif_dist/wxMotif/samples/docview
cp *.xpm ~/wxmotif_dist/wxMotif/samples/docview
cd ..

echo DocvwMDI sample..

cd docvwmdi
mkdir ~/wxmotif_dist/wxMotif/samples/docvwmdi
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/docvwmdi
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/docvwmdi
cp *.cpp ~/wxmotif_dist/wxMotif/samples/docvwmdi
cp *.h ~/wxmotif_dist/wxMotif/samples/docvwmdi
cd ..

echo Dynamic sample..

cd dynamic
mkdir ~/wxmotif_dist/wxMotif/samples/dynamic
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/dynamic
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/dynamic
cp *.cpp ~/wxmotif_dist/wxMotif/samples/dynamic
cp *.xpm ~/wxmotif_dist/wxMotif/samples/dynamic
cd ..

echo Drawing sample..

cd drawing
mkdir ~/wxmotif_dist/wxMotif/samples/drawing
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/drawing
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/drawing
cp *.cpp ~/wxmotif_dist/wxMotif/samples/drawing
cp *.xpm ~/wxmotif_dist/wxMotif/samples/drawing
cd ..

echo Forty sample..

cd forty
mkdir ~/wxmotif_dist/wxMotif/samples/forty
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/forty
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/forty
cp *.cpp ~/wxmotif_dist/wxMotif/samples/forty
cp *.h ~/wxmotif_dist/wxMotif/samples/forty
cp *.xpm ~/wxmotif_dist/wxMotif/samples/forty
cp *.xbm ~/wxmotif_dist/wxMotif/samples/forty
cd ..

echo Fractal sample..

cd fractal
mkdir ~/wxmotif_dist/wxMotif/samples/fractal
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/fractal
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/fractal
cp *.cpp ~/wxmotif_dist/wxMotif/samples/fractal
cd ..

echo Grid sample..

cd grid
mkdir ~/wxmotif_dist/wxMotif/samples/grid
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/grid
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/grid
cp *.cpp ~/wxmotif_dist/wxMotif/samples/grid
cd ..

echo Help sample..

cd help
mkdir ~/wxmotif_dist/wxMotif/samples/help
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/help
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/help
cp *.cpp ~/wxmotif_dist/wxMotif/samples/help
cp *.xpm ~/wxmotif_dist/wxMotif/samples/help
cd doc
mkdir ~/wxmotif_dist/wxMotif/samples/help/doc
cp * ~/wxmotif_dist/wxMotif/samples/help/doc
cd ../..

echo HTML samples..

cd html
mkdir ~/wxmotif_dist/wxMotif/samples/html
cp Makefile.* ~/wxmotif_dist/wxMotif/samples/html

mkdir ~/wxmotif_dist/wxMotif/samples/html/about
cp about/Makefile.* ~/wxmotif_dist/wxMotif/samples/html/about
cp about/about.* ~/wxmotif_dist/wxMotif/samples/html/about

mkdir ~/wxmotif_dist/wxMotif/samples/html/about/data
cp about/data/*.* ~/wxmotif_dist/wxMotif/samples/html/about/data

mkdir ~/wxmotif_dist/wxMotif/samples/html/help
cp help/Makefile.* ~/wxmotif_dist/wxMotif/samples/html/help
cp help/help.* ~/wxmotif_dist/wxMotif/samples/html/help

mkdir ~/wxmotif_dist/wxMotif/samples/html/help/helpfiles
cp help/helpfiles/*.* ~/wxmotif_dist/wxMotif/samples/html/help/helpfiles

mkdir ~/wxmotif_dist/wxMotif/samples/html/printing
cp printing/*.* ~/wxmotif_dist/wxMotif/samples/html/printing

mkdir ~/wxmotif_dist/wxMotif/samples/html/test
cp test/*.* ~/wxmotif_dist/wxMotif/samples/html/test

mkdir ~/wxmotif_dist/wxMotif/samples/html/virtual
cp virtual/*.* ~/wxgtk_dist/wxGTK/samples/html/virtual

mkdir ~/wxmotif_dist/wxMotif/samples/html/widget
cp widget/*.* ~/wxmotif_dist/wxMotif/samples/html/widget

mkdir ~/wxmotif_dist/wxMotif/samples/html/zip
cp zip/*.* ~/wxmotif_dist/wxMotif/samples/html/zip
cd ..

echo Image sample..

cd image
mkdir ~/wxmotif_dist/wxMotif/samples/image
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/image
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/image
cp *.cpp ~/wxmotif_dist/wxMotif/samples/image
cp horse.png ~/wxmotif_dist/wxMotif/samples/image
cp horse.gif ~/wxmotif_dist/wxMotif/samples/image
cp horse.jpg ~/wxmotif_dist/wxMotif/samples/image
cd ..

echo Internat sample..

cd internat
mkdir ~/wxmotif_dist/wxMotif/samples/internat
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/internat
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/internat
cp *.cpp ~/wxmotif_dist/wxMotif/samples/internat
cp *.xpm ~/wxmotif_dist/wxMotif/samples/internat
cp readme.txt ~/wxmotif_dist/wxMotif/samples/internat
cp wxstd.po ~/wxmotif_dist/wxMotif/samples/internat
cd fr
mkdir ~/wxmotif_dist/wxMotif/samples/internat/fr
cp *.?o ~/wxmotif_dist/wxMotif/samples/internat/fr
cd ../..

echo Layout sample..

cd layout
mkdir ~/wxmotif_dist/wxMotif/samples/layout
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/layout
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/layout
cp *.cpp ~/wxmotif_dist/wxMotif/samples/layout
cp *.h ~/wxmotif_dist/wxMotif/samples/layout
cd ..

echo Listctrl sample..

cd listctrl
mkdir ~/wxmotif_dist/wxMotif/samples/listctrl
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/listctrl
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/listctrl
cp *.cpp ~/wxmotif_dist/wxMotif/samples/listctrl
cp *.h ~/wxmotif_dist/wxMotif/samples/listctrl
cp *.xpm ~/wxmotif_dist/wxMotif/samples/listctrl
cd bitmaps
mkdir ~/wxmotif_dist/wxMotif/samples/listctrl/bitmaps
cp *.xpm ~/wxmotif_dist/wxMotif/samples/listctrl/bitmaps
cd ../..

echo MDI sample..

cd mdi
mkdir ~/wxmotif_dist/wxMotif/samples/mdi
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/mdi
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/mdi
cp *.cpp ~/wxmotif_dist/wxMotif/samples/mdi
cp *.h ~/wxmotif_dist/wxMotif/samples/mdi
cp *.xpm ~/wxmotif_dist/wxMotif/samples/mdi
cd bitmaps
mkdir ~/wxmotif_dist/wxMotif/samples/mdi/bitmaps
cp *.xpm ~/wxmotif_dist/wxMotif/samples/mdi/bitmaps
cd ../..

echo Memcheck sample..

cd memcheck
mkdir ~/wxmotif_dist/wxMotif/samples/memcheck
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/memcheck
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/memcheck
cp *.cpp ~/wxmotif_dist/wxMotif/samples/memcheck
cp *.xpm ~/wxmotif_dist/wxMotif/samples/memcheck
cd ..

echo Minifram sample..

cd minifram
mkdir ~/wxmotif_dist/wxMotif/samples/minifram
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/minifram
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/minifram
cp *.cpp ~/wxmotif_dist/wxMotif/samples/minifram
cp *.h ~/wxmotif_dist/wxMotif/samples/minifram
cp *.xpm ~/wxmotif_dist/wxMotif/samples/minifram
cd bitmaps
mkdir ~/wxmotif_dist/wxMotif/samples/minifram/bitmaps
cp *.xpm ~/wxmotif_dist/wxMotif/samples/minifram/bitmaps
cd ../..

echo Notebook sample..

cd notebook
mkdir ~/wxmotif_dist/wxMotif/samples/notebook
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/notebook
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/notebook
cp *.cpp ~/wxmotif_dist/wxMotif/samples/notebook
cp *.h ~/wxmotif_dist/wxMotif/samples/notebook
cd ..

echo PNG sample..

cd png
mkdir ~/wxmotif_dist/wxMotif/samples/png
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/png
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/png
cp *.cpp ~/wxmotif_dist/wxMotif/samples/png
cp *.h ~/wxmotif_dist/wxMotif/samples/png
cp *.png ~/wxmotif_dist/wxMotif/samples/png
cd ..

echo Printing sample..

cd printing
mkdir ~/wxmotif_dist/wxMotif/samples/printing
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/printing
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/printing
cp *.cpp ~/wxmotif_dist/wxMotif/samples/printing
cp *.h ~/wxmotif_dist/wxMotif/samples/printing
cp *.xpm ~/wxmotif_dist/wxMotif/samples/printing
cd ..

echo Proplist sample..

cd proplist
mkdir ~/wxmotif_dist/wxMotif/samples/proplist
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/proplist
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/proplist
cp *.cpp ~/wxmotif_dist/wxMotif/samples/proplist
cp *.h ~/wxmotif_dist/wxMotif/samples/proplist
cd ..

echo Resource sample..

cd resource
mkdir ~/wxmotif_dist/wxMotif/samples/resource
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/resource
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/resource
cp *.cpp ~/wxmotif_dist/wxMotif/samples/resource
cp *.h ~/wxmotif_dist/wxMotif/samples/resource
cp *.wxr ~/wxmotif_dist/wxMotif/samples/resource
cd ..

echo Sashtest sample..

cd sashtest
mkdir ~/wxmotif_dist/wxMotif/samples/sashtest
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/sashtest
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/sashtest
cp *.cpp ~/wxmotif_dist/wxMotif/samples/sashtest
cp *.h ~/wxmotif_dist/wxMotif/samples/sashtest
cd ..

echo Scroll sample..

cd sashtest
mkdir ~/wxmotif_dist/wxMotif/samples/scroll
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/scroll
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/scroll
cp *.cpp ~/wxmotif_dist/wxMotif/samples/scroll
cp *.h ~/wxmotif_dist/wxMotif/samples/scroll
cd ..

echo Splitter sample..

cd splitter
mkdir ~/wxmotif_dist/wxMotif/samples/splitter
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/splitter
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/splitter
cp *.cpp ~/wxmotif_dist/wxMotif/samples/splitter
cd ..

echo Tab sample..

cd tab
mkdir ~/wxmotif_dist/wxMotif/samples/tab
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/tab
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/tab
cp *.cpp ~/wxmotif_dist/wxMotif/samples/tab
cp *.h ~/wxmotif_dist/wxMotif/samples/tab
cd ..

echo Text sample..

cd text
mkdir ~/wxmotif_dist/wxMotif/samples/text
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/text
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/text
cp *.cpp ~/wxmotif_dist/wxMotif/samples/text
cd ..

echo Thread sample..

cd thread
mkdir ~/wxmotif_dist/wxMotif/samples/thread
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/thread
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/thread
cp *.cpp ~/wxmotif_dist/wxMotif/samples/thread
cd ..

echo Toolbar sample..

cd toolbar
mkdir ~/wxmotif_dist/wxMotif/samples/toolbar
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/toolbar
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/toolbar
cp *.cpp ~/wxmotif_dist/wxMotif/samples/toolbar
cp *.h ~/wxmotif_dist/wxMotif/samples/toolbar
cp *.xpm ~/wxmotif_dist/wxMotif/samples/toolbar
cd bitmaps
mkdir ~/wxmotif_dist/wxMotif/samples/toolbar/bitmaps
cp *.xpm ~/wxmotif_dist/wxMotif/samples/toolbar/bitmaps
cd ../..

echo TreeCtrl sample..

cd treectrl
mkdir ~/wxmotif_dist/wxMotif/samples/treectrl
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/treectrl
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/treectrl
cp *.cpp ~/wxmotif_dist/wxMotif/samples/treectrl
cp *.h ~/wxmotif_dist/wxMotif/samples/treectrl
cp *.xpm ~/wxmotif_dist/wxMotif/samples/treectrl
cd ..

echo typetest sample..

cd typetest
mkdir ~/wxmotif_dist/wxMotif/samples/typetest
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/typetest
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/typetest
cp *.cpp ~/wxmotif_dist/wxMotif/samples/typetest
cp *.h ~/wxmotif_dist/wxMotif/samples/typetest
cp *.xpm ~/wxmotif_dist/wxMotif/samples/typetest
cd ..

echo Validate sample..

cd validate
mkdir ~/wxmotif_dist/wxMotif/samples/validate
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/validate
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/validate
cp *.cpp ~/wxmotif_dist/wxMotif/samples/validate
cp *.h ~/wxmotif_dist/wxMotif/samples/validate
cp *.xpm ~/wxmotif_dist/wxMotif/samples/validate
cd ..

echo wxPoem sample..

cd wxpoem
mkdir ~/wxmotif_dist/wxMotif/samples/wxpoem
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/wxpoem
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/wxpoem
cp *.cpp ~/wxmotif_dist/wxMotif/samples/wxpoem
cp *.h ~/wxmotif_dist/wxMotif/samples/wxpoem
cp *.xpm ~/wxmotif_dist/wxMotif/samples/wxpoem
cp wxpoem.dat ~/wxmotif_dist/wxMotif/samples/wxpoem
cp wxpoem.txt ~/wxmotif_dist/wxMotif/samples/wxpoem
cp wxpoem.idx ~/wxmotif_dist/wxMotif/samples/wxpoem
cd ..

echo wxSocket sample..

cd wxsocket
mkdir ~/wxmotif_dist/wxMotif/samples/wxsocket
cp Makefile.am ~/wxmotif_dist/wxMotif/samples/wxsocket
cp Makefile.in ~/wxmotif_dist/wxMotif/samples/wxsocket
cp *.cpp ~/wxmotif_dist/wxMotif/samples/wxsocket
cp *.xpm ~/wxmotif_dist/wxMotif/samples/wxsocket
cd ../..

cd ~/wxmotif_dist
tar ch wxMotif | gzip -f9 > wxMotif-2.1.0-b7.tgz
