# makefile

CXXFLAGS = `wx-config --cxxflags`
LDFLAGS = `wx-config --libs`

PROGRAM = tex2rtf

OBJECTS = tex2rtf.o tex2any.o texutils.o rtfutils.o xlputils.o htmlutil.o readshg.o table.o

# implementation

.SUFFIXES:	.o .cpp

.cpp.o :
	$(CXX) -c $(CXXFLAGS)  -o $@ $<

all:    $(PROGRAM)

$(PROGRAM):	$(OBJECTS)
	$(CXX) -o $(PROGRAM) $(OBJECTS) $(LDFLAGS) 

clean:
	rm -f *.o $(PROGRAM)

