#
# File:		makefile.dos
# Author:	Julian Smart
# Created:	1998
# Updated:	
#
# Makefile : Builds 16-bit sample, VC++ 1.5
# Use FINAL=1 argument to nmake to build final version with no debugging
# info

WXDIR = $(WXWIN)

TARGET=tex2rtf
OBJECTS = tex2rtf.obj tex2any.obj texutils.obj rtfutils.obj xlputils.obj htmlutil.obj readshg.obj table.obj

!include $(WXDIR)\src\makeprog.msc

