#
# File:		makefile.b32
# Author:	Julian Smart
# Created:	1993
# Updated:	
# Copyright:
#
# "%W% %G%"
#
# Makefile : Builds tex2rtf

# WXWIN and BCCDIR are set by parent make

WXDIR = $(WXWIN)

TARGET=tex2rtf
OBJECTS = tex2rtf.obj tex2any.obj texutils.obj rtfutils.obj xlputils.obj htmlutil.obj readshg.obj table.obj

!include $(WXDIR)\src\makeprog.b32

