#
# File:         makefile.g95
# Author:       Julian Smart
# Created:      1999
# Updated:
# Copyright:    (c) Julian Smart, 1999
#
# Makefile for wxWindows sample (Cygwin/Mingw32).

WXDIR = ../../..

TARGET=tex2rtf
OBJECTS = $(TARGET).o texutils.o tex2any.o htmlutil.o rtfutils.o xlputils.o table.o readshg.o

include $(WXDIR)/src/makeprog.g95

