#
# File:		makefile.unx
# Author:	Julian Smart
# Created:	1998
# Updated:	
# Copyright:	(c) 1998 Julian Smart
#
# "%W% %G%"
#
# Makefile for nativdlg example (UNIX).
# Actually, this is a Windows-specific example...

PROGRAM=nativdlg

OBJECTS=$(PROGRAM).o

include ../../src/makeprog.env
