# Purpose: makefile for calendar example (BC++ 16bit)
# Created: 2000-01-03

!if "$(WXWIN)" == ""
!error You must define the WXWIN variable in autoexec.bat, e.g. WXWIN=c:\wx
!endif

WXDIR = $(WXWIN)

TARGET=calendar
OBJECTS=$(TARGET).obj

!include $(WXDIR)\src\makeprog.bcc

