# Makefile for xpm
# Borland C++   


LIBTARGET=$(WXDIR)\lib\xpm.lib

OBJECTS = crbuffri.obj crdatfri.obj create.obj crifrbuf.obj crifrdat.obj\
          data.obj hashtab.obj misc.obj parse.obj rdftodat.obj rdftoi.obj\
          rgb.obj scan.obj simx.obj wrffrdat.obj wrffrp.obj wrffri.obj

!include $(WXWIN)\src\makelib.b32
