# Makefile for xpm
# Borland C++   


LIBTARGET=$(WXDIR)\lib\xpm.lib

OBJECTS = attrib.obj crbuffri.obj crdatfri.obj create.obj crifrbuf.obj crifrdat.obj\
          data.obj image.obj info.obj hashtab.obj misc.obj parse.obj\
          rdftodat.obj rdftoi.obj rgb.obj scan.obj simx.obj wrffrdat.obj wrffri.obj

!include $(WXWIN)\src\makelib.bcc
