#
# File:		makefile.vc
# Author:	Julian Smart
# Created:	1999
# Updated:	
# Copyright:	(c) Julian Smart
#
# Makefile : Builds sample (VC++, WIN32)
# Use FINAL=1 argument to nmake to build final version with no debug info.

# Set WXDIR for your system
WXDIR = $(WXWIN)

PROGRAM=minimal
OBJECTS = $(PROGRAM).obj

!include $(WXDIR)\src\makeprog.vc

# For broken VC++ 4
noopt:
	cl @<<
$(CPPFLAGS2) /Od /c /Tp $(PROGRAM).cpp
<<

