#
# File:     makefile.va
# Author:   David Webster
# Created:  1999
# Updated:
# Copyright:    (c) David Webster
#
# Makefile : Builds sample (VisualAgeC++ V3.0, OS/2 PM)
# Use FINAL=1 argument to nmake to build final version with no debug info.

# Set WXDIR for your system
WXDIR = $(WXWIN)

PROGRAM=minimal
OBJECTS = $(PROGRAM).obj

!include $(WXDIR)\src\makeprog.va

