#! /bin/sh
#
# This script is creates a dir tree in ~/wxwine_dist which
# can then be packed into an archive

echo                               --------
echo    This script will copy the wxWINE release files into ~/wxwine_dist
echo                               --------
echo

mkdir ~/wxwine_dist
mkdir ~/wxwine_dist/wxWINE

echo Base dir..

cd ../..
cp wxWINE.spec ~/wxwine_dist/wxWINE
cp Makefile.am ~/wxwine_dist/wxWINE
cp acconfig.h ~/wxwine_dist/wxWINE
cp acinclude.m4 ~/wxwine_dist/wxWINE
cp aclocal.m4 ~/wxwine_dist/wxWINE
cp configure.in ~/wxwine_dist/wxWINE
cp configure ~/wxwine_dist/wxWINE
cp config.sub ~/wxwine_dist/wxWINE
cp config.guess ~/wxwine_dist/wxWINE
cp install-sh ~/wxwine_dist/wxWINE
cp ltconfig ~/wxwine_dist/wxWINE
cp ltmain.sh ~/wxwine_dist/wxWINE
cp missing ~/wxwine_dist/wxWINE
cp mkinstalldirs ~/wxwine_dist/wxWINE
cp wx-config.in ~/wxwine_dist/wxWINE
cp setup.h.in ~/wxwine_dist/wxWINE
cp stamp-h.in ~/wxwine_dist/wxWINE
cp Makefile.in ~/wxwine_dist/wxWINE

echo Docs..

cd docs/wine
cp COPYING.LIB ~/wxwine_dist/wxWINE
cp install.txt ~/wxwine_dist/wxWINE/INSTALL.txt
cp changes.txt ~/wxwine_dist/wxWINE/CHANGES.txt
cp licence.txt ~/wxwine_dist/wxWINE/LICENCE.txt
cp readme.txt ~/wxwine_dist/wxWINE/README.txt
cp todo.txt ~/wxwine_dist/wxWINE/TODO.txt
cd ..
cp symbols.txt ~/wxwine_dist/wxWINE/SYMBOLS.txt
cd ..

echo Include dir..

mkdir ~/wxwine_dist/wxWINE/include
cd include
cp Makefile.am ~/wxwine_dist/wxWINE/include
cp Makefile.in ~/wxwine_dist/wxWINE/include

mkdir ~/wxwine_dist/wxWINE/include/wx
cd wx
cp *.h ~/wxwine_dist/wxWINE/include/wx
cp *.cpp ~/wxwine_dist/wxWINE/include/wx
cp Makefile.am ~/wxwine_dist/wxWINE/include/wx
cp Makefile.in ~/wxwine_dist/wxWINE/include/wx

mkdir ~/wxwine_dist/wxWINE/include/wx/generic
cd generic
cp *.h ~/wxwine_dist/wxWINE/include/wx/generic
cp *.xpm ~/wxwine_dist/wxWINE/include/wx/generic
cp Makefile.am ~/wxwine_dist/wxWINE/include/wx/generic
cp Makefile.in ~/wxwine_dist/wxWINE/include/wx/generic
cd ..

mkdir ~/wxwine_dist/wxWINE/include/wx/unix
cd unix
cp *.h ~/wxwine_dist/wxWINE/include/wx/unix
cp Makefile.am ~/wxwine_dist/wxWINE/include/wx/unix
cp Makefile.in ~/wxwine_dist/wxWINE/include/wx/unix
cd ..

mkdir ~/wxwine_dist/wxWINE/include/wx/msw
cd msw
cp *.h ~/wxwine_dist/wxWINE/include/wx/msw
rm ~/wxwine_dist/wxWINE/include/wx/msw/setup.h
cp Makefile.am ~/wxwine_dist/wxWINE/include/wx/msw
cp Makefile.in ~/wxwine_dist/wxWINE/include/wx/msw
cd ..

mkdir ~/wxwine_dist/wxWINE/include/wx/motif
cd motif
cp Makefile.am ~/wxwine_dist/wxWINE/include/wx/motif
cp Makefile.in ~/wxwine_dist/wxWINE/include/wx/motif
cd ..

mkdir ~/wxwine_dist/wxWINE/include/wx/gtk
cd gtk
cp Makefile.am ~/wxwine_dist/wxWINE/include/wx/gtk
cp Makefile.in ~/wxwine_dist/wxWINE/include/wx/gtk
cd ..

mkdir ~/wxwine_dist/wxWINE/include/wx/protocol
cd protocol
cp *.h ~/wxwine_dist/wxWINE/include/wx/protocol
cp Makefile.am ~/wxwine_dist/wxWINE/include/wx/protocol
cp Makefile.in ~/wxwine_dist/wxWINE/include/wx/protocol
cd ..

cd ../..

echo Misc dir..

mkdir ~/wxwine_dist/wxWINE/misc
cd misc
cp Makefile.am ~/wxwine_dist/wxWINE/misc
cp Makefile.in ~/wxwine_dist/wxWINE/misc
mkdir ~/wxwine_dist/wxWINE/misc/afm
cd afm
cp *.afm ~/wxwine_dist/wxWINE/misc/afm
cp Makefile.am ~/wxwine_dist/wxWINE/misc/afm
cp Makefile.in ~/wxwine_dist/wxWINE/misc/afm
cd ..
mkdir ~/wxwine_dist/wxWINE/misc/gs_afm
cd gs_afm
cp *.afm ~/wxwine_dist/wxWINE/misc/gs_afm
cp Makefile.am ~/wxwine_dist/wxWINE/misc/gs_afm
cp Makefile.in ~/wxwine_dist/wxWINE/misc/gs_afm
cd ../..

echo Src dir..

cd src
mkdir ~/wxwine_dist/wxWINE/src
cp Makefile.am ~/wxwine_dist/wxWINE/src
cp Makefile.in ~/wxwine_dist/wxWINE/src

cd msw
mkdir ~/wxwine_dist/wxWINE/src/msw
cp Makefile.am ~/wxwine_dist/wxWINE/src/msw
cp Makefile.in ~/wxwine_dist/wxWINE/src/msw
cp *.xbm ~/wxwine_dist/wxWINE/src/msw
cp *.c ~/wxwine_dist/wxWINE/src/msw
cp *.inc ~/wxwine_dist/wxWINE/src/msw
cp *.cpp ~/wxwine_dist/wxWINE/src/msw
cd ..

cd common
mkdir ~/wxwine_dist/wxWINE/src/common
cp glob.inc ~/wxwine_dist/wxWINE/src/common
cp lexer.l ~/wxwine_dist/wxWINE/src/common
cp parser.y ~/wxwine_dist/wxWINE/src/common
cp extended.c ~/wxwine_dist/wxWINE/src/common
cp *.cpp ~/wxwine_dist/wxWINE/src/common
cd ..

cd unix
mkdir ~/wxwine_dist/wxWINE/src/unix
cp *.cpp ~/wxwine_dist/wxWINE/src/unix
cd ..

cd generic
mkdir ~/wxwine_dist/wxWINE/src/generic
cp *.cpp ~/wxwine_dist/wxWINE/src/generic
cd ..

cd iodbc
mkdir ~/wxwine_dist/wxWINE/src/iodbc
cp * ~/wxwine_dist/wxWINE/src/iodbc
cd ..

cd zlib
mkdir ~/wxwine_dist/wxWINE/src/zlib
cp * ~/wxwine_dist/wxWINE/src/zlib
cd ..

cd png
mkdir ~/wxwine_dist/wxWINE/src/png
cp * ~/wxwine_dist/wxWINE/src/png
cd ..

cd jpeg
mkdir ~/wxwine_dist/wxWINE/src/jpeg
cp * ~/wxwine_dist/wxWINE/src/jpeg
cd ..

cd ..

echo Utils dir..

cd utils
mkdir ~/wxwine_dist/wxWINE/utils
cp Makefile.am ~/wxwine_dist/wxWINE/utils
cp Makefile.in ~/wxwine_dist/wxWINE/utils
cd ..

echo Samples dir..

cd samples
mkdir ~/wxwine_dist/wxWINE/samples
cp Makefile.am ~/wxwine_dist/wxWINE/samples
cp Makefile.in ~/wxwine_dist/wxWINE/samples

echo Minimal sample..

cd minimal
mkdir ~/wxwine_dist/wxWINE/samples/minimal
cp Makefile.am ~/wxwine_dist/wxWINE/samples/minimal
cp Makefile.in ~/wxwine_dist/wxWINE/samples/minimal
cp minimal.cpp ~/wxwine_dist/wxWINE/samples/minimal
cp mondrian.xpm ~/wxwine_dist/wxWINE/samples/minimal
cd ..

echo Bombs sample..

cd bombs
mkdir ~/wxwine_dist/wxWINE/samples/bombs
cp Makefile.am ~/wxwine_dist/wxWINE/samples/bombs
cp Makefile.in ~/wxwine_dist/wxWINE/samples/bombs
cp *.cpp ~/wxwine_dist/wxWINE/samples/bombs
cp *.h ~/wxwine_dist/wxWINE/samples/bombs
cp *.xpm ~/wxwine_dist/wxWINE/samples/bombs
cd ..

echo Caret sample..

cd caret
mkdir ~/wxwine_dist/wxWINE/samples/caret
cp Makefile.am ~/wxwine_dist/wxWINE/samples/caret
cp Makefile.in ~/wxwine_dist/wxWINE/samples/caret
cp *.cpp ~/wxwine_dist/wxWINE/samples/caret
cp *.xpm ~/wxwine_dist/wxWINE/samples/caret
cd ..

echo Checklst sample..

cd checklst
mkdir ~/wxwine_dist/wxWINE/samples/checklst
cp Makefile.am ~/wxwine_dist/wxWINE/samples/checklst
cp Makefile.in ~/wxwine_dist/wxWINE/samples/checklst
cp *.cpp ~/wxwine_dist/wxWINE/samples/checklst
cp *.xpm ~/wxwine_dist/wxWINE/samples/checklst
cd ..

echo Config sample..

cd config
mkdir ~/wxwine_dist/wxWINE/samples/config
cp Makefile.am ~/wxwine_dist/wxWINE/samples/config
cp Makefile.in ~/wxwine_dist/wxWINE/samples/config
cp *.cpp ~/wxwine_dist/wxWINE/samples/config
cd ..

echo Controls sample..

cd controls
mkdir ~/wxwine_dist/wxWINE/samples/controls
cp Makefile.am ~/wxwine_dist/wxWINE/samples/controls
cp Makefile.in ~/wxwine_dist/wxWINE/samples/controls
cp *.cpp ~/wxwine_dist/wxWINE/samples/controls
cp *.xpm ~/wxwine_dist/wxWINE/samples/controls
cd icons
mkdir ~/wxwine_dist/wxWINE/samples/controls/icons
cp *.xpm ~/wxwine_dist/wxWINE/samples/controls/icons
cd ../..

echo Db sample..

cd db
mkdir ~/wxwine_dist/wxWINE/samples/db
cp Makefile.am ~/wxwine_dist/wxWINE/samples/db
cp Makefile.in ~/wxwine_dist/wxWINE/samples/db
cp *.cpp ~/wxwine_dist/wxWINE/samples/db
cp *.h ~/wxwine_dist/wxWINE/samples/db
cp *.xpm ~/wxwine_dist/wxWINE/samples/db
cd ..

echo DDE sample..

cd dde
mkdir ~/wxwine_dist/wxWINE/samples/dde
cp Makefile.am ~/wxwine_dist/wxWINE/samples/dde
cp Makefile.in ~/wxwine_dist/wxWINE/samples/dde
cp *.cpp ~/wxwine_dist/wxWINE/samples/dde
cp *.h ~/wxwine_dist/wxWINE/samples/dde
cp *.xpm ~/wxwine_dist/wxWINE/samples/dde
cd ..

echo Dialogs sample..

cd dialogs
mkdir ~/wxwine_dist/wxWINE/samples/dialogs
cp Makefile.am ~/wxwine_dist/wxWINE/samples/dialogs
cp Makefile.in ~/wxwine_dist/wxWINE/samples/dialogs
cp *.cpp ~/wxwine_dist/wxWINE/samples/dialogs
cp *.h ~/wxwine_dist/wxWINE/samples/dialogs
cd ..

echo DnD sample..

cd dnd
mkdir ~/wxwine_dist/wxWINE/samples/dnd
cp Makefile.am ~/wxwine_dist/wxWINE/samples/dnd
cp Makefile.in ~/wxwine_dist/wxWINE/samples/dnd
cp *.cpp ~/wxwine_dist/wxWINE/samples/dnd
cp *.xpm ~/wxwine_dist/wxWINE/samples/dnd
cd ..

echo Docview sample..

cd docview
mkdir ~/wxwine_dist/wxWINE/samples/docview
cp Makefile.am ~/wxwine_dist/wxWINE/samples/docview
cp Makefile.in ~/wxwine_dist/wxWINE/samples/docview
cp *.cpp ~/wxwine_dist/wxWINE/samples/docview
cp *.h ~/wxwine_dist/wxWINE/samples/docview
cp *.xpm ~/wxwine_dist/wxWINE/samples/docview
cd ..

echo DocvwMDI sample..

cd docvwmdi
mkdir ~/wxwine_dist/wxWINE/samples/docvwmdi
cp Makefile.am ~/wxwine_dist/wxWINE/samples/docvwmdi
cp Makefile.in ~/wxwine_dist/wxWINE/samples/docvwmdi
cp *.cpp ~/wxwine_dist/wxWINE/samples/docvwmdi
cp *.h ~/wxwine_dist/wxWINE/samples/docvwmdi
cd ..

echo Dynamic sample..

cd dynamic
mkdir ~/wxwine_dist/wxWINE/samples/dynamic
cp Makefile.am ~/wxwine_dist/wxWINE/samples/dynamic
cp Makefile.in ~/wxwine_dist/wxWINE/samples/dynamic
cp *.cpp ~/wxwine_dist/wxWINE/samples/dynamic
cp *.xpm ~/wxwine_dist/wxWINE/samples/dynamic
cd ..

echo Drawing sample..

cd drawing
mkdir ~/wxwine_dist/wxWINE/samples/drawing
cp Makefile.am ~/wxwine_dist/wxWINE/samples/drawing
cp Makefile.in ~/wxwine_dist/wxWINE/samples/drawing
cp *.cpp ~/wxwine_dist/wxWINE/samples/drawing
cp *.xpm ~/wxwine_dist/wxWINE/samples/drawing
cd ..

echo Forty sample..

cd forty
mkdir ~/wxwine_dist/wxWINE/samples/forty
cp Makefile.am ~/wxwine_dist/wxWINE/samples/forty
cp Makefile.in ~/wxwine_dist/wxWINE/samples/forty
cp *.cpp ~/wxwine_dist/wxWINE/samples/forty
cp *.h ~/wxwine_dist/wxWINE/samples/forty
cp *.xpm ~/wxwine_dist/wxWINE/samples/forty
cp *.xbm ~/wxwine_dist/wxWINE/samples/forty
cd ..

echo Fractal sample..

cd fractal
mkdir ~/wxwine_dist/wxWINE/samples/fractal
cp Makefile.am ~/wxwine_dist/wxWINE/samples/fractal
cp Makefile.in ~/wxwine_dist/wxWINE/samples/fractal
cp *.cpp ~/wxwine_dist/wxWINE/samples/fractal
cd ..

echo Grid sample..

cd grid
mkdir ~/wxwine_dist/wxWINE/samples/grid
cp Makefile.am ~/wxwine_dist/wxWINE/samples/grid
cp Makefile.in ~/wxwine_dist/wxWINE/samples/grid
cp *.cpp ~/wxwine_dist/wxWINE/samples/grid
cd ..

echo Help sample..

cd help
mkdir ~/wxwine_dist/wxWINE/samples/help
cp Makefile.am ~/wxwine_dist/wxWINE/samples/help
cp Makefile.in ~/wxwine_dist/wxWINE/samples/help
cp *.cpp ~/wxwine_dist/wxWINE/samples/help
cp *.xpm ~/wxwine_dist/wxWINE/samples/help
cd doc
mkdir ~/wxwine_dist/wxWINE/samples/help/doc
cp * ~/wxwine_dist/wxWINE/samples/help/doc
cd ../..

echo Image sample..

cd image
mkdir ~/wxwine_dist/wxWINE/samples/image
cp Makefile.am ~/wxwine_dist/wxWINE/samples/image
cp Makefile.in ~/wxwine_dist/wxWINE/samples/image
cp *.cpp ~/wxwine_dist/wxWINE/samples/image
cp horse.png ~/wxwine_dist/wxWINE/samples/image
cp horse.gif ~/wxwine_dist/wxWINE/samples/image
cp horse.jpg ~/wxwine_dist/wxWINE/samples/image
cd ..

echo Internat sample..

cd internat
mkdir ~/wxwine_dist/wxWINE/samples/internat
cp Makefile.am ~/wxwine_dist/wxWINE/samples/internat
cp Makefile.in ~/wxwine_dist/wxWINE/samples/internat
cp *.cpp ~/wxwine_dist/wxWINE/samples/internat
cp *.xpm ~/wxwine_dist/wxWINE/samples/internat
cp readme.txt ~/wxwine_dist/wxWINE/samples/internat
cp wxstd.po ~/wxwine_dist/wxWINE/samples/internat
cd fr
mkdir ~/wxwine_dist/wxWINE/samples/internat/fr
cp *.?o ~/wxwine_dist/wxWINE/samples/internat/fr
cd ../..

echo Layout sample..

cd layout
mkdir ~/wxwine_dist/wxWINE/samples/layout
cp Makefile.am ~/wxwine_dist/wxWINE/samples/layout
cp Makefile.in ~/wxwine_dist/wxWINE/samples/layout
cp *.cpp ~/wxwine_dist/wxWINE/samples/layout
cp *.h ~/wxwine_dist/wxWINE/samples/layout
cd ..

echo Listctrl sample..

cd listctrl
mkdir ~/wxwine_dist/wxWINE/samples/listctrl
cp Makefile.am ~/wxwine_dist/wxWINE/samples/listctrl
cp Makefile.in ~/wxwine_dist/wxWINE/samples/listctrl
cp *.cpp ~/wxwine_dist/wxWINE/samples/listctrl
cp *.h ~/wxwine_dist/wxWINE/samples/listctrl
cp *.xpm ~/wxwine_dist/wxWINE/samples/listctrl
cd bitmaps
mkdir ~/wxwine_dist/wxWINE/samples/listctrl/bitmaps
cp *.xpm ~/wxwine_dist/wxWINE/samples/listctrl/bitmaps
cd ../..

echo MDI sample..

cd mdi
mkdir ~/wxwine_dist/wxWINE/samples/mdi
cp Makefile.am ~/wxwine_dist/wxWINE/samples/mdi
cp Makefile.in ~/wxwine_dist/wxWINE/samples/mdi
cp *.cpp ~/wxwine_dist/wxWINE/samples/mdi
cp *.h ~/wxwine_dist/wxWINE/samples/mdi
cp *.xpm ~/wxwine_dist/wxWINE/samples/mdi
cd bitmaps
mkdir ~/wxwine_dist/wxWINE/samples/mdi/bitmaps
cp *.xpm ~/wxwine_dist/wxWINE/samples/mdi/bitmaps
cd ../..

echo Memcheck sample..

cd memcheck
mkdir ~/wxwine_dist/wxWINE/samples/memcheck
cp Makefile.am ~/wxwine_dist/wxWINE/samples/memcheck
cp Makefile.in ~/wxwine_dist/wxWINE/samples/memcheck
cp *.cpp ~/wxwine_dist/wxWINE/samples/memcheck
cp *.xpm ~/wxwine_dist/wxWINE/samples/memcheck
cd ..

echo Minifram sample..

cd minifram
mkdir ~/wxwine_dist/wxWINE/samples/minifram
cp Makefile.am ~/wxwine_dist/wxWINE/samples/minifram
cp Makefile.in ~/wxwine_dist/wxWINE/samples/minifram
cp *.cpp ~/wxwine_dist/wxWINE/samples/minifram
cp *.h ~/wxwine_dist/wxWINE/samples/minifram
cp *.xpm ~/wxwine_dist/wxWINE/samples/minifram
cd bitmaps
mkdir ~/wxwine_dist/wxWINE/samples/minifram/bitmaps
cp *.xpm ~/wxwine_dist/wxWINE/samples/minifram/bitmaps
cd ../..

echo Notebook sample..

cd notebook
mkdir ~/wxwine_dist/wxWINE/samples/notebook
cp Makefile.am ~/wxwine_dist/wxWINE/samples/notebook
cp Makefile.in ~/wxwine_dist/wxWINE/samples/notebook
cp *.cpp ~/wxwine_dist/wxWINE/samples/notebook
cp *.h ~/wxwine_dist/wxWINE/samples/notebook
cd ..

echo PNG sample..

cd png
mkdir ~/wxwine_dist/wxWINE/samples/png
cp Makefile.am ~/wxwine_dist/wxWINE/samples/png
cp Makefile.in ~/wxwine_dist/wxWINE/samples/png
cp *.cpp ~/wxwine_dist/wxWINE/samples/png
cp *.h ~/wxwine_dist/wxWINE/samples/png
cp *.png ~/wxwine_dist/wxWINE/samples/png
cd ..

echo Printing sample..

cd printing
mkdir ~/wxwine_dist/wxWINE/samples/printing
cp Makefile.am ~/wxwine_dist/wxWINE/samples/printing
cp Makefile.in ~/wxwine_dist/wxWINE/samples/printing
cp *.cpp ~/wxwine_dist/wxWINE/samples/printing
cp *.h ~/wxwine_dist/wxWINE/samples/printing
cp *.xpm ~/wxwine_dist/wxWINE/samples/printing
cd ..

echo Proplist sample..

cd proplist
mkdir ~/wxwine_dist/wxWINE/samples/proplist
cp Makefile.am ~/wxwine_dist/wxWINE/samples/proplist
cp Makefile.in ~/wxwine_dist/wxWINE/samples/proplist
cp *.cpp ~/wxwine_dist/wxWINE/samples/proplist
cp *.h ~/wxwine_dist/wxWINE/samples/proplist
cd ..

echo Resource sample..

cd resource
mkdir ~/wxwine_dist/wxWINE/samples/resource
cp Makefile.am ~/wxwine_dist/wxWINE/samples/resource
cp Makefile.in ~/wxwine_dist/wxWINE/samples/resource
cp *.cpp ~/wxwine_dist/wxWINE/samples/resource
cp *.h ~/wxwine_dist/wxWINE/samples/resource
cp *.wxr ~/wxwine_dist/wxWINE/samples/resource
cd ..

echo Sashtest sample..

cd sashtest
mkdir ~/wxwine_dist/wxWINE/samples/sashtest
cp Makefile.am ~/wxwine_dist/wxWINE/samples/sashtest
cp Makefile.in ~/wxwine_dist/wxWINE/samples/sashtest
cp *.cpp ~/wxwine_dist/wxWINE/samples/sashtest
cp *.h ~/wxwine_dist/wxWINE/samples/sashtest
cd ..

echo Scroll sample..

cd sashtest
mkdir ~/wxwine_dist/wxWINE/samples/scroll
cp Makefile.am ~/wxwine_dist/wxWINE/samples/scroll
cp Makefile.in ~/wxwine_dist/wxWINE/samples/scroll
cp *.cpp ~/wxwine_dist/wxWINE/samples/scroll
cp *.h ~/wxwine_dist/wxWINE/samples/scroll
cd ..

echo Splitter sample..

cd splitter
mkdir ~/wxwine_dist/wxWINE/samples/splitter
cp Makefile.am ~/wxwine_dist/wxWINE/samples/splitter
cp Makefile.in ~/wxwine_dist/wxWINE/samples/splitter
cp *.cpp ~/wxwine_dist/wxWINE/samples/splitter
cd ..

echo Tab sample..

cd tab
mkdir ~/wxwine_dist/wxWINE/samples/tab
cp Makefile.am ~/wxwine_dist/wxWINE/samples/tab
cp Makefile.in ~/wxwine_dist/wxWINE/samples/tab
cp *.cpp ~/wxwine_dist/wxWINE/samples/tab
cp *.h ~/wxwine_dist/wxWINE/samples/tab
cd ..

echo Text sample..

cd text
mkdir ~/wxwine_dist/wxWINE/samples/text
cp Makefile.am ~/wxwine_dist/wxWINE/samples/text
cp Makefile.in ~/wxwine_dist/wxWINE/samples/text
cp *.cpp ~/wxwine_dist/wxWINE/samples/text
cd ..

echo Thread sample..

cd thread
mkdir ~/wxwine_dist/wxWINE/samples/thread
cp Makefile.am ~/wxwine_dist/wxWINE/samples/thread
cp Makefile.in ~/wxwine_dist/wxWINE/samples/thread
cp *.cpp ~/wxwine_dist/wxWINE/samples/thread
cd ..

echo Toolbar sample..

cd toolbar
mkdir ~/wxwine_dist/wxWINE/samples/toolbar
cp Makefile.am ~/wxwine_dist/wxWINE/samples/toolbar
cp Makefile.in ~/wxwine_dist/wxWINE/samples/toolbar
cp *.cpp ~/wxwine_dist/wxWINE/samples/toolbar
cp *.h ~/wxwine_dist/wxWINE/samples/toolbar
cp *.xpm ~/wxwine_dist/wxWINE/samples/toolbar
cd bitmaps
mkdir ~/wxwine_dist/wxWINE/samples/toolbar/bitmaps
cp *.xpm ~/wxwine_dist/wxWINE/samples/toolbar/bitmaps
cd ../..

echo TreeCtrl sample..

cd treectrl
mkdir ~/wxwine_dist/wxWINE/samples/treectrl
cp Makefile.am ~/wxwine_dist/wxWINE/samples/treectrl
cp Makefile.in ~/wxwine_dist/wxWINE/samples/treectrl
cp *.cpp ~/wxwine_dist/wxWINE/samples/treectrl
cp *.h ~/wxwine_dist/wxWINE/samples/treectrl
cp *.xpm ~/wxwine_dist/wxWINE/samples/treectrl
cd ..

echo typetest sample..

cd typetest
mkdir ~/wxwine_dist/wxWINE/samples/typetest
cp Makefile.am ~/wxwine_dist/wxWINE/samples/typetest
cp Makefile.in ~/wxwine_dist/wxWINE/samples/typetest
cp *.cpp ~/wxwine_dist/wxWINE/samples/typetest
cp *.h ~/wxwine_dist/wxWINE/samples/typetest
cp *.xpm ~/wxwine_dist/wxWINE/samples/typetest
cd ..

echo Validate sample..

cd validate
mkdir ~/wxwine_dist/wxWINE/samples/validate
cp Makefile.am ~/wxwine_dist/wxWINE/samples/validate
cp Makefile.in ~/wxwine_dist/wxWINE/samples/validate
cp *.cpp ~/wxwine_dist/wxWINE/samples/validate
cp *.h ~/wxwine_dist/wxWINE/samples/validate
cp *.xpm ~/wxwine_dist/wxWINE/samples/validate
cd ..

echo wxPoem sample..

cd wxpoem
mkdir ~/wxwine_dist/wxWINE/samples/wxpoem
cp Makefile.am ~/wxwine_dist/wxWINE/samples/wxpoem
cp Makefile.in ~/wxwine_dist/wxWINE/samples/wxpoem
cp *.cpp ~/wxwine_dist/wxWINE/samples/wxpoem
cp *.h ~/wxwine_dist/wxWINE/samples/wxpoem
cp *.xpm ~/wxwine_dist/wxWINE/samples/wxpoem
cp wxpoem.dat ~/wxwine_dist/wxWINE/samples/wxpoem
cp wxpoem.txt ~/wxwine_dist/wxWINE/samples/wxpoem
cp wxpoem.idx ~/wxwine_dist/wxWINE/samples/wxpoem
cd ..

echo wxSocket sample..

cd wxsocket
mkdir ~/wxwine_dist/wxWINE/samples/wxsocket
cp Makefile.am ~/wxwine_dist/wxWINE/samples/wxsocket
cp Makefile.in ~/wxwine_dist/wxWINE/samples/wxsocket
cp *.cpp ~/wxwine_dist/wxWINE/samples/wxsocket
cp *.xpm ~/wxwine_dist/wxWINE/samples/wxsocket
cd ../..

cd ~/wxwine_dist
tar ch wxWINE | gzip -f9 > wxWINE-2.1.0-b7.tgz
