# Purpose: makefile for treectrl example (VC++ 32bit)
# Created: 2000-03-15

# Set WXDIR for your system
WXDIR = $(WXWIN)

PROGRAM=treectrl
OBJECTS = $(PROGRAM).obj

!include $(WXDIR)\src\makeprog.vc

