# Purpose: makefile for typetest example (VC++ 32bit)
# Created: 2000-03-14

# Set WXDIR for your system
WXDIR = $(WXWIN)

PROGRAM=typetest
OBJECTS = $(PROGRAM).obj

!include $(WXDIR)\src\makeprog.vc

