#
# File:		makefile.nt
# Author:	Julian Smart
# Created:	1997
# Updated:	
#
# "%W% %G%"
#
# Makefile : Builds cube example (MS VC++).
# Use FINAL=1 argument to nmake to build final version with no debugging
# info

# Set WXDIR for your system
WXDIR = $(WXWIN)

WXUSINGDLL=0

EXTRAINC=-I..\..\win
EXTRALIBS=$(WXDIR)\lib\glcanvas.lib glu32.lib opengl32.lib

!include $(WXDIR)\src\ntwxwin.mak

THISDIR = $(WXDIR)\utils\glcanvas\samples\cube
PROGRAM=cube

OBJECTS = $(PROGRAM).obj

$(PROGRAM):    $(PROGRAM).exe

all:    wx $(PROGRAM).exe

wx:
        cd $(WXDIR)\src\msw
        nmake -f makefile.nt FINAL=$(FINAL)
        cd $(THISDIR)

wxclean:
        cd $(WXDIR)\src\msw
        nmake -f makefile.nt clean
        cd $(THISDIR)

$(PROGRAM).exe:      $(DUMMYOBJ) $(WXLIB) $(OBJECTS) $(PROGRAM).res
	$(link) @<<
-out:$(PROGRAM).exe
$(LINKFLAGS)
$(DUMMYOBJ) $(OBJECTS) $(PROGRAM).res
$(LIBS)
<<


$(PROGRAM).obj:      $(PROGRAM).$(SRCSUFF) $(PROGRAM).h $(DUMMYOBJ)
        $(cc) @<<
$(CPPFLAGS2) /c /Tp $*.$(SRCSUFF)
<<

$(PROGRAM).res :      $(PROGRAM).rc $(WXDIR)\include\wx\msw\wx.rc
    $(rc) -r /i$(WXDIR)\include -fo$@ $(PROGRAM).rc


clean:
        -erase *.obj
        -erase *.exe
        -erase *.res
        -erase *.map
        -erase *.sbr
        -erase *.pdb
