#
# File:		makefile.unx
# Author:	Julian Smart
# Created:	1998
# Updated:	
# Copyright:	(c) 1998 Julian Smart
#
# "%W% %G%"
#
# Makefile for drawing example (UNIX).

PROGRAM=drawing

OBJECTS=$(PROGRAM).o

include ../../src/makeprog.env

