#!/bin/sh

# you need to change this if you run from outside this dir. 
if [ "$WXROOT" = "" ]; then
  scriptDir="$(cd $(dirname $0);pwd)"
  WXROOT=$scriptDir/../../..
fi

. $WXROOT/distrib/scripts/includes/configure_build.inc

. $WXROOT/distrib/scripts/mac/mac_options.inc

# most of this script is shared with other Mac-based and other
# configure-based build scripts, which is why this looks a little empty.

if [ "$UNIVERSAL" = "1" ]; then
  OTHER_OPTS="$OTHER_OPTS --enable-universal_binary --with-libjpeg=builtin --with-libpng=builtin"
fi

mkdir -p builds
cd builds
do_build

make prefix=$INSTALLDIR install

if [ "$WXPYTHON" == "1" ]; then
    make -C contrib/src/gizmos prefix=$INSTALLDIR install
    make -C contrib/src/stc prefix=$INSTALLDIR install
fi 

cd $OLDDIR