#
# File:		makefile.nt
# Author:	Stefan Hammes (stefan.hammes@urz.uni-heidelberg.de) / Julian Smart / Petr Houser (1996)
# Created:	1995
# Updated:=09
#
# "%W% %G%"
#
# Makefile : Builds wxSock library for Windows NT / Win95

# Change WXDIR or WXWIN to wherever wxWindows is found
!include <..\..\src\ntwxwin.mak>

WXMMEDDIR = $(WXDIR)\utils\wxmmedia
WXMMEDINC = $(WXMMEDDIR)
WXMMEDLIB = $(WXDIR)\lib\wxmmedia.lib
INC=-I$(WXBASEINC) -I$(WXINC) -I$(WXMMEDINC)

WXLIB = $(WXDIR)\lib\wx.lib

LIBS=$(WXSOCKLIB) $(LIBS)
#LIBS=$(WXLIB) $(WXSTRINGLIB) oldnames libw llibcew llibce commdlg shell

OBJECTS = mmdata.obj mmfile.obj sndfile.obj sndsnd.obj sndwin.obj\
	sndwav.obj sndfrag.obj vidbase.obj

all: $(WXMMEDLIB)

wx:
        cd $(WXDIR)\src\msw
        nmake -f makefile.nt
        cd $(ITSYDIR)

demo:

$(WXMMEDLIB): $(OBJECTS)
        -erase $(WXSOCKLIB)
        $(implib) @<<
-out:$(WXSOCKLIB)
-machine:$(CPU)
$(OBJECTS)
<<

MMdata.obj: MMdata.$(SRCSUFF)
        cl @<<
$(CPPFLAGS) /c /Tp $*.$(SRCSUFF)
<<

MMfile.obj: MMfile.$(SRCSUFF)
        cl @<<
$(CPPFLAGS) /c /Tp $*.$(SRCSUFF)
<<

SNDfile.obj: SNDfile.$(SRCSUFF) SNDfile.h
        cl @<<
$(CPPFLAGS) /c /Tp $*.$(SRCSUFF)
<<

SNDwav.obj: SNDwav.$(SRCSUFF) SNDwav.h
        cl @<<
$(CPPFLAGS) /c /Tp $*.$(SRCSUFF)
<<

SNDwin.obj: SNDwin.$(SRCSUFF) SNDwin.h
        cl @<<
$(CPPFLAGS) /c /Tp $*.$(SRCSUFF)
<<

SNDsnd.obj: SNDsnd.$(SRCSUFF) SNDsnd.h
        cl @<<
$(CPPFLAGS) /c /Tp $*.$(SRCSUFF)
<<

SNDfrag.obj: SNDfrag.$(SRCSUFF) SNDfrag.h
        cl @<<
$(CPPFLAGS) /c /Tp $*.$(SRCSUFF)
<<

VIDbase.obj: VIDbase.$(SRCSUFF) VIDbase.h
        cl @<<
$(CPPFLAGS) /c /Tp $*.$(SRCSUFF)
<<

clean:
        -erase *.obj
        -erase *.exe
        -erase *.lib
        -erase *.res
        -erase *.sbr
        -erase *.pdb
