#
# File:		makefile.vc
# Author:	Julian Smart
# Created:	2000
# Updated:
# Copyright:	(c) Julian Smart
#
# "%W% %G%"
#
# Makefile : Builds wxconvert
# Use FINAL=1 argument to nmake to build final version with no debugging
# info
# Set WXDIR for your system
WXDIR = $(WXWIN)

PROGRAM=wxconvert

FINAL=0

!if "$(FINAL)" == "0"
EXTRALIBS=$(WXDIR)\lib\wxxrcd.lib
!else
EXTRALIBS=$(WXDIR)\lib\wxxrc.lib
!endif

OBJECTS=convert.obj rc2xml.obj rc2wxr.obj wxr2xml.obj

!include $(WXDIR)\src\makeprog.vc

