name: No Response

on:
  issue_comment:
    types: [created]
  schedule:
    # Schedule to run once per day
    - cron: '27 20 * * *'

jobs:
  no-response:
    permissions:
      issues: write

    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/no-response@v0.5.0
        with:
          token: ${{ github.token }}
          daysUntilClose: 100
          responseRequiredLabel: "repro needed"
          closeComment: >
            This issue has been automatically closed because there has been no response
            to our request for more information from the original author since 100 days
            and we're unable to do anything about the problem without more information.
            Please comment on this issue if you can provide any additional data so that
            we could investigate it further.
