#!/bin/sh

/usr/bin/sudo -u $USER /bin/rm -rf \
    $2/Library/Frameworks/Python.framework/Versions/2.2/lib/python2.2/site-packages/wxPython \

#    $2/usr/local/bin/wx* \
#    $2/usr/local/include/wx \
#    $2/usr/local/lib/wx \
#    $2/usr/local/lib/libwx*

exit 0
