
# Top dir of wxWindows
top_builddir = /gtm/bart/wxGTK

PROGRAM=dbbrowser_gtk


OBJECTS= dbbrowser.o doc.o pgmctrl.o wxtbpgwin.o\
         browserdb.o dbtree.o dbgrid.o  dlguser.o
	



include $(top_builddir)/src/makeprog.env

