#
# File:         makefile.g95
# Author:       Julian Smart
# Created:      1999
# Updated:
# Copyright:    (c) Julian Smart, 1999
#
# Makefile for wxWindows sample (Cygwin/Mingw32).

# Set WXDIR for your system
WXDIR = $(WXWIN)

TARGET=dbbrowser
OBJECTS = dbbrowse.o     doc.o        pgmctrl.o tabpgwin.o \
          browsedb.o     dbtree.o     dbgrid.o  dlguser.o


include $(WXDIR)/src/makeprog.g95

