#
# File:         makefile.vc
# Author:       Mark Johnson, mj10777@gmx.net
# Created:      19990808
# Updated:
# Copyright:    (c) Mark Johnson
#
# Makefile : Builds sample (VC++, WIN32)
# Use FINAL=1 argument to nmake to build final version with no debug info.

# Set WXDIR for your system
WXDIR = $(WXWIN)

PROGRAM=dbbrowse
OBJECTS = $(PROGRAM).obj doc.obj    pgmctrl.obj    tabpgwin.obj \
           browsedb.obj dbtree.obj dbgrid.obj     dlguser.obj

!include $(WXDIR)\src\makeprog.vc

